### ISSUE TITLE
Quasar ClientNo connection

### ISSUE THREAD

**Issue by ysdxj** [quasar/Quasar#1000]
This problem did not occur in version 1.3
After upgrading to version 1.4, the problem keeps appearing

**Comment by MaxXor** [comment]
Did you [follow the steps](https://github.com/quasar/Quasar/wiki/Updating-a-Client) to update Quasar server + clients?

**Comment by pank4you** [comment]
Team please share source code for Quasar Golden Edition

**Comment by BurntDog** [comment]
> Team please share source code for Quasar Golden Edition

Never heard of this Golden Edition, you on the right project?

**Comment by ErickDaGamer** [comment]
> > Team please share source code for Quasar Golden Edition
> 
> Never heard of this Golden Edition, you on the right project?

It's a closed source fork of Quasar: https://blackspigot.com/threads/quasar-rat-golden-edition-v-1-4-1-0.28445/

**Comment by BurntDog** [comment]
Coming from Russia, yea I wouldn't trust it and they are withholding the code which isn't even theirs other then the several addons. Most likely designed to drop a backdoor on a users pc.
