### ISSUE TITLE
How to connect to a PC

### ISSUE THREAD

**Issue by BluGithub711** [quasar/Quasar#1003]
how is it possible to connect to another computer to Keylog, etc
i downloaded the program properly but i wanna know how i can connect to another computer.

**Comment by yourbankempty666** [comment]
Tell me the step you have done to ldownload, have you built a panel? Do you
have a dedicated rdp host?

**Comment by BurntDog** [comment]
First you need their (owner of the computer) permission and after you have compiled Quasar server and Client. Using Quasar Server Configure your Client and build. Then install Client onto computer you wish to control.

**Comment by BluGithub711** [comment]
> First you need their (owner of the computer) permission and after you have compiled Quasar server and Client. Using Quasar Server Configure your Client and build. Then install Client onto computer you wish to control.

its my second laptop, i tried plugging in a lan cable to both computers and googled a ton

**Comment by BurntDog** [comment]
You can search our data base here in issues or you will find several videos on YouTube to walk you thru the setup.
