### ISSUE TITLE
i need Help  (discord bot)

### ISSUE THREAD

**Issue by Disrespectfish** [quasar/Quasar#1005]
this is the error
/home/runner/JavaScript-2/node_modules/discord.js/src/rest/RESTManager.js:32
    const token = this.client.token ?? this.client.accessToken;
                                     ^

SyntaxError: Unexpected token '?'

this is the link to the script https://replit.com/@Disrespectfish/JavaScript-2#index.js

the Token form the discord bot: ODc1NjM5Mzc3NzM5NTMwMjUw.YRYcuA.5pojdsIdGqdEN-G1vONmSVQ_B_c

**Comment by priyansh32** [comment]
Hey @Disrespectfish I guess You should not share your Token, It is private key used to communicate with your bot. Reset your Token to avoid anything unexpected.

**Comment by BurntDog** [comment]
@Disrespectfish You're in the wrong place. This Github Repository is for "Quasar" not a Discord Bot...

**Comment by Disrespectfish** [comment]
Ups wrong place thanks thanks @BurntDog 

And this is a token from my test bot @priyansh32

**Comment by D4RKH0R1Z0N** [comment]
What the hell...
