### ISSUE TITLE
Product Version problem

### ISSUE THREAD

**Issue by bros739** [quasar/Quasar#1006]
When i try to BUILD clients in Assembly it shows 
-
Please Enter a valid Product version Number 
Ex : 1.2.3.4 
-
but when i type 1.2 or 1 it is again showing this error.

How To fix this? what do i need to type ? Thank You Quaser

**Comment by D4RKH0R1Z0N** [comment]
You have to enter a value for the version ex : 0.0.0.1 or 0.0.2.8 it should be 4 numbers that's what I think

**Comment by D4RKH0R1Z0N** [comment]
Enter something like :
```
0.2.1.3
0.8.1.1
0.8.1.1
8.2.0.0
8.3.1.9
7.1.2.5
5.7.8.9
1.4.2.9
2.3.4.5
1.2.3.9
```

**Comment by D4RKH0R1Z0N** [comment]
I hope it helped

- D4RKH0R1Z0N

**Comment by D4RKH0R1Z0N** [comment]
Also btw if you want 1.2 like that then enter 0.0.1.2

**Comment by BurntDog** [comment]
It shouldn't be asking for a version number at any point. Are you using "Quasar the remote admin tool"?

**Comment by MaxXor** [comment]
It's in the client builder -> assembly information. See here https://github.com/quasar/Quasar/wiki/Client-deployment-settings#assembly-information

As already mentioned it needs all 4 digits.
