### ISSUE TITLE
Requirement issue

### ISSUE THREAD

**Issue by D4RKH0R1Z0N** [quasar/Quasar#1007]
So the quasar rat needs .net installed to work (I think so)... Does that mean that .net framework should also be installed on client aka target? Or just the host or both?

**Comment by abdullah2993** [comment]
both

**Comment by D4RKH0R1Z0N** [comment]
wtf

**Comment by D4RKH0R1Z0N** [comment]
WHAT THE HELL

**Comment by D4RKH0R1Z0N** [comment]
DOES IT NEED TO BE INSTALLED ON THE TARGET TOO???
