### ISSUE TITLE
Can you make a selector for the output format ?

### ISSUE THREAD

**Issue by Kalvelign** [quasar/Quasar#1015]
hi , can you make a selector for the output of the file befor the generation of the agent for selecting the os like 

What operating system you would use this agent on ? 

- windows 
- linux 
- osx

The solution for that is developping the possiblity for the generator to generate agent for linux , windows and osx , i fink is doable because all the code is in C so you just need to make some change for the file path and all the other path of the agent is using and after just change the compilation at the end for making it into .elf , .exe format. So i fink you got what i mean and i fink im not the first persone to fink its possible and it would be great if you can do it. It would be great if you reply to this by saying if you gonna do it or not and thanx you if you plan to do it.

**Comment by ErickDaGamer** [comment]
It is possible, but different operating systems have different executable formats (as well as different APIs), so MaxXor would have to rewrite some (or all) parts of the client C# code, as well as figure out how to sign the clients generated for OSX with a key.

You could _probably_ use [Wine](https://www.winehq.org/) to run the generated client though.

**Comment by Kalvelign** [comment]
the operating system im intresting in now is more linux ( debian , ubuntu , ect ) but the pcs im working with got low capaciti in storage so i cant use wine because is too ig for the pcs so if is possible to make it only for linux its would be really cool .

**Comment by MaxXor** [comment]
It's not simply adding a selector for the output format. Making the Quasar client run on Linux and OSX will require a very large effort. However I've started upgrading Quasar to .NET Core which will definitely help with this task.

As there are other issues open for Linux support I'll close this one.
