### ISSUE TITLE
Not Connecting to Quasar Control Module

### ISSUE THREAD

**Issue by Career707** [quasar/Quasar#1017]
Downloaded this v1.4.0 installed on Windows 10, Router Port Forwarding is done correctly (I have a good level of experience with Using RAT's on remote Machines), Built two types of Clients and  these are run 1 at a time, 1 with NoIP Host name and the other with simple IP address, on execution, on remote machine, both types are sending SYN/ACK Packets to my router and to my Local Host (where Quasar is running) also, I have Wireshark running to confirm this, however, Quasar has failed to connect to both.

Any Idea's?

**Comment by BurntDog** [comment]
> Downloaded this v1.4.0 installed on Windows 10, Router Port Forwarding is done correctly (I have a good level of experience with Using RAT's on remote Machines), Built two types of Clients and these are run 1 at a time, 1 with NoIP Host name and the other with simple IP address, on execution, on remote machine, both types are sending SYN/ACK Packets to my router and to my Local Host (where Quasar is running) also, I have Wireshark running to confirm this, however, Quasar has failed to connect to both.
> 
> I know 100% that my system is set up correctly as I am a ScamBaiter and use RAT's to infiltrate Scammers PC's, I'm just hunting for another RAT to ad to my Weapons Cache.
> 
> Any Idea's?

Quasar is a legit admin tool and does not promote or encourage illegal use. You clearly stated your full intent to use in a illegal fashion and knowing this anyone who aides you in this can be implicated and charged in a crime. I myself won't be part of that.
Unless you have the pc owner's or courts approval (a warrant) you're committing a crime. Sorry this isn't spy school

**Comment by MaxXor** [comment]
You can run a Debug version of Quasar and try to see if there is any exception message.
