### ISSUE TITLE
Import Wizard error? 

### ISSUE THREAD

**Issue by Darkisters** [quasar/Quasar#1023]
I am confused on what I put here, I saved that file with the info saying if lost you will lose all clients. Please help I am confused
![image](https://user-images.githubusercontent.com/75067034/134259440-09448343-d2c7-4fb0-b239-da8bedc93fd5.png)

**Comment by MaxXor** [comment]
This is not the Quasar import wizard but instead the Windows certificate store import wizard. Don't double click the certificate file.

Simply backup the certificate file and if you ever need to restore it in a fresh Quasar installation, choose import.
