### ISSUE TITLE
Idk why

### ISSUE THREAD

**Issue by MarosDuris** [quasar/Quasar#1028]
Hello. When Im trying to use software it is okey and it is very very cool, when I build a client a open it on my computer I can see my pc and all the stuff, BUT when I send client so my friend or someone else nothing will happened. IDK WHY. I put my ip, port is 4782 and I really really dont know why it isnt working. Can someone HELP ME plz. ;D

**Comment by vozxko** [comment]
Hi, try to port forward using portmap, you can find some tutorials on youtube.
