### ISSUE TITLE
Unhandled expectation has occurred in client builder 

### ISSUE THREAD

**Issue by NeosDanger** [quasar/Quasar#1029]
![Error](https://user-images.githubusercontent.com/69181702/139522624-ec22ab69-5580-4f9e-abd7-444ec1f860d1.JPG)

Hello. I'm getting this error when I get to the client builder. I don't know what happened. Can anyone help? I've reinstalled the program multiple times and deleted all files. Nothing works

**Comment by BurntDog** [comment]
Need to know the details, click the "Details" button take a screen shot the post.
