### ISSUE TITLE
remote desktop audio

### ISSUE THREAD

**Issue by furtuna-dev** [quasar/Quasar#1032]
You should add a feature that should allow you the desktop of the user that you have access to; It would be a very usefull feature especially for debugging specific things. =)

**Comment by BurntDog** [comment]
By desktop audio you do mean "audio heard thru speakers"? Because MaxXor has no plans on adding mic or cam. That was removed in this version for privacy concerns to mention one. However feel free to add the code, it is open source.

**Comment by ErickDaGamer** [comment]
#135
