### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by Angelo1553** [quasar/Quasar#1034]
hi, someone told me that if i lose the certs my pc gonna die..and i don t rlly know what to do right now.Thanks!

**Comment by BurntDog** [comment]
No, the certificate is security to connect to a client without the proper cert you simply won't be connected to a client.

**Comment by Angelo1553** [comment]
so that means i can t connect to any pc?

**Comment by BurntDog** [comment]
The certificate is for the clients you build. No one can hijack your clients and only you control your clients..

**Comment by Angelo1553** [comment]
Thank you for helping!
