### ISSUE TITLE
Quasar Client won't stay open

### ISSUE THREAD

**Issue by qks123** [quasar/Quasar#1035]
I have problem with my build. After I open the file on my vm or my desktop pc, it stays opened for couple of seconds and then it disappears from the task manager. I don't have firewall on. Any help would be obliging. Thank you already.

**Comment by qks123** [comment]
My port is open so its not an issue with the firewall

**Comment by Nicicalu** [comment]
Maybe the Windows Defender or another Anti-Virus?
