### ISSUE TITLE
does this rat support https? also rat does not work when run on a vm

### ISSUE THREAD

**Issue by Azzerzz** [quasar/Quasar#1039]
does this rat work with http/s?
and whenever i run the rat on a VM it does not show any connection, but if i use any services like any.run it works fine, but im worried because last time i had a connection all that happened was that the person restarted there pc and i lost the connection for good even with startup enabled and they did not remove it
so i need to test it out with a vm so i can see if it will do that agian 
and the reason i want to know if it supports http/s is because i wanna use Cloudflare or NGINX as a reverse proxy

**Comment by rockpapersissors** [comment]
What are you talking about? https, dude you have no clue how this work from bottom to top , lmao.

**Comment by BurntDog** [comment]
Use the search function, this has been answered numerous times.
