### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by martovasko** [quasar/Quasar#1040]
Hi, i don't know hot to open this because there is no .bat files :?

**Comment by ErickDaGamer** [comment]
Are you trying to compile this yourself or open the precompiled version?

**Comment by j4ck-code** [comment]
@martovasko I feel like you don't understand the base concepts of computers;
.bat files are Batch files, which aren't responsible for most of the runnable stuff, more like a "shortcut".

Please provide further information if you mean something else.
