### ISSUE TITLE
wont open the exe

### ISSUE THREAD

**Issue by OusmBlueNinja** [quasar/Quasar#1042]
it loads then nothong happens no window no error and i  have all my antiviruses off

**Comment by ErickDaGamer** [comment]
Are you referring to the server or the generated client?

**Comment by OusmBlueNinja** [comment]
the one that is used to make the server (not the one thats a rat the build
tool)

**Comment by ErickDaGamer** [comment]
If you're trying to compile this yourself, then you need to download Visual Studio with the C# programming language. Download the Quasar repository, and open the Quasar.sln file. Then click on Build > Build Solution or press Ctrl + Shift + B.

**Comment by SmurkOC** [comment]
> it loads then nothong happens no window no error and i have all my antiviruses off

where do i open the server

**Comment by SmurkOC** [comment]
> Are you referring to the server or the generated client?
> 
> If you're talking about the client, the client isn't supposed to show a GUI when run. It runs in the background.
> 
> If you're talking about the server, I would wait for someone like BurntDog or MaxXor, or one of the contributors.

wait for them where? and what is the server and how do i use it or create it?

**Comment by BurntDog** [comment]
After you compile the project you will be using the "Server.exe" to build/Setup your "Client.exe". You run the Client.exe on the pc you want to control and run the Server.exe to accept connection from Client.exe and have remote control.

**Comment by MaxXor** [comment]
This is a bug tracker, for actual software bugs. Please refer to the guide for setup instructions: https://github.com/quasar/Quasar/wiki/Getting-Started
