### ISSUE TITLE
Telegram notifications

### ISSUE THREAD

**Issue by SuperSnake802** [quasar/Quasar#1043]
Hello,

I wanna get notifications when my clients connected via discord or telegram. This feature is not available in quasar RAT. So, could you please add it?

**Comment by ErickDaGamer** [comment]
#1037 Solves this.

**Comment by SuperSnake802** [comment]
> #1037 Solves the Telegram bot issue.

Oh, thanks! One more question please, do I need to update my clients?

**Comment by ErickDaGamer** [comment]
Please read this wiki page: https://github.com/quasar/Quasar/wiki/Updating-a-Client
