### ISSUE TITLE
Unable to Setup Quasar RAT

### ISSUE THREAD

**Issue by k24h1** [quasar/Quasar#1044]
Hi there, I'm new to RATs and I'm not really sure how I should install this, I watched a hackersploit video but that shows the files from 2017 and the current version doesn't have those .bat files and I don't know how to install quasar now, can someone guide me on what I should do?

**Comment by ErickDaGamer** [comment]
To compile it yourself, download Visual Studio 2019 (I think you need to check the .NET desktop development workload), download the Quasar source code, open the Quasar.sln file, and click Build > Build solution. Wait for it to compile and you can use Quasar.

**Comment by ErickDaGamer** [comment]
To compile it yourself, download Visual Studio 2019 with .NET Desktop Development. Download this repository, open the Quasar.sln (once Visual Studio 2019 has finished installing), and click Build > Build Solution. Once you've done that, you can open the compiled program.

You could also just download the binaries without downloading Visual Studio 2019 [here](https://github.com/quasar/Quasar/releases/download/v1.4.0/Quasar.v1.4.0.zip).

I meant to answer this three hours ago but my browser crashed and I forgot.

**Comment by BurntDog** [comment]
Also make sure you compile in Release mode not Debug.

**Comment by SmurkOC** [comment]
where do you find the finished compiled program?

**Comment by BurntDog** [comment]
After you compile the project you will use the "Server.exe" to setup the "Client.exe". Then use the newly created Client.exe you saved to Desktop/Or where ever you want to run on the system to control. Test using LoopBack method using localhost/127.0.0.1

**Comment by MaxXor** [comment]
This is a bug tracker, for actual software bugs. Please refer to the guide for setup instructions: https://github.com/quasar/Quasar/wiki/Getting-Started
