### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by k24h1** [quasar/Quasar#1045]
I downloaded .NET 6 and .NET SDKs 4.52 as well, but while compiling in VS CODE it said 773 errors with c# plug  in ; how do I fix that? also how to I get access to the client.exe and server.exe programs that I've heard about previously, how do I proceed? could someone tell me?#1044

**Comment by MaxXor** [comment]
It's described here: https://github.com/quasar/Quasar#compiling Don't forget to restore the nuget packages and be sure to install target framework 4.5.2 with Visual Studio.
