### ISSUE TITLE
win7 x32 client can't connect to win10 server ,but can telnet

### ISSUE THREAD

**Issue by introspection3** [quasar/Quasar#1047]
**Describe the bug**
win7 x32 client can't connect to server ,but can telnet

**To Reproduce**

**Expected behavior**

**Screenshots**

**System**
 - Server OS: [e.g. Windows 10]
 - Client OS: [e.g. Windows 7]
 - Server installed .NET Framework version: [e.g. v4.8]
 - Client installed .NET Framework version: [e.g. v4.8]
 - Quasar Version: [e.g. 1.3.0 or commit-id]
 - Build configuration: [e.g. Debug/Release]

**Additional context**

**Comment by ErickDaGamer** [comment]
This is the default template. No information is provided here.

**Comment by BurntDog** [comment]
> This is the default template. No information is provided here.

2nd post like this one in two days ,one more and it's a official Troll, if you ask me..
