### ISSUE TITLE
I can't open it 

### ISSUE THREAD

**Issue by plssssubba** [quasar/Quasar#1049]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System**
 - Server OS: [e.g. Windows 10]
 - Client OS: [e.g. Windows 7]
 - Server installed .NET Framework version: [e.g. v4.8]
 - Client installed .NET Framework version: [e.g. v4.8]
 - Quasar Version: [e.g. 1.3.0 or commit-id]
 - Build configuration: [e.g. Debug/Release]

**Additional context**
When i download it and i try to open it its says cant open it and when i try to extract it doesnt let me and shows me a error of that its a virus and a malware

**Comment by ErickDaGamer** [comment]
?????

**Comment by BurntDog** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **System**
> 
> * Server OS: [e.g. Windows 10]
> * Client OS: [e.g. Windows 7]
> * Server installed .NET Framework version: [e.g. v4.8]
> * Client installed .NET Framework version: [e.g. v4.8]
> * Quasar Version: [e.g. 1.3.0 or commit-id]
> * Build configuration: [e.g. Debug/Release]
> 
> **Additional context** Add any other context about the problem here. When i download it and i try to open it its says cant open it and when i try to extract it doesnt let me and shows me a error of that its a virus and a malware

Need information not the default example...
