### ISSUE TITLE
Finding the file and the ip address it is from

### ISSUE THREAD

**Issue by Once4thewin** [quasar/Quasar#1051]
Hi, I was wondering, how do I find it on the pc its installed? If I do like a prank, how could the person find the RAT and see the ip address it's sending the information to,? Also, if I delete the a connected device, does it remove the RAT from that pc? I would really appreciate if someone could answer :)

**Comment by BurntDog** [comment]
When you made the client you configured (in left Menu "Installation Settings" ) on the right it will show you where. And "yes" if you clicked on "uninstall" which shows up in the Server interface right mouse click under "Connection" "uninstall" option.
