### ISSUE TITLE
What kind of server is this ? (ec2-3-232-242-170.compute-1.amazonaws.com)

### ISSUE THREAD

**Issue by Kela2022** [quasar/Quasar#1053]
What kind of server is this (ec2-3-232-242-170.compute-1.amazonaws.com )? After building the solution in VS 2022 , the client connects through this server . What role does this server play ? And also the client file has a very large size.

**Comment by MaxXor** [comment]
It's one of the geo ip services: https://github.com/quasar/Quasar/blob/master/Quasar.Client/IpGeoLocation/GeoInformationRetriever.cs
