### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by arin2115** [quasar/Quasar#1058]
It would be good if You will add something like port forwarding, so if ratted pc (for example my laptop) have something on port for example 3001, I can access it from my main pc.

Port forwarding from client's pc to server

**Comment by BurntDog** [comment]
You can already accomplish this by adding other/alternate connect back address and different port.

**Comment by arin2115** [comment]
> You can already accomplish this by adding other/alternate connect back address and different port.

Can you explain further more, please? Or add me on Discord / Telegram (arin#1000 | t.me/arin2115)

**Comment by BurntDog** [comment]
Just add another/different address and port when building your client. You can add several (more than one) as you see here in the box it will hold and use (alternate which address it tries to connect un till it makes a connect). Understand
![Screenshot_1](https://user-images.githubusercontent.com/62985894/159174882-219fc061-f02c-43f1-b714-60066a1c9798.png)
?

**Comment by MaxXor** [comment]
As @BurntDog suggested, this is the best way to accomplish this. The other way around would be unsuitable in most situations as client PCs are usually behind a firewall/router which do NAT and dont allow incoming ports.
