### ISSUE TITLE
release/debug profile does not exist 

### ISSUE THREAD

**Issue by Pizza-Prime** [quasar/Quasar#1059]
![image](https://user-images.githubusercontent.com/82731605/159388330-9dc8f3f8-5efb-4682-99e3-3261e090d0f0.png)
I keep getting this error, how do i fix this?

**Comment by MaxXor** [comment]
Your AV is probably deleting the file right after creation. Please add an exception in your AV for your build directory. You can also try building in debug mode first to see if any errors occur.
