### ISSUE TITLE
keylogger not working properly

### ISSUE THREAD

**Issue by Sheelia** [quasar/Quasar#1060]
keylogger not working properly

**Comment by Sheelia** [comment]
I click the get logs button and it doesn't work

**Comment by Sheelia** [comment]
doesn't write live

**Comment by BurntDog** [comment]
Make sure to delete manually if you need to, the old key log encrypted file. I gets corrupted times and won't store or show (live) key press if corrupted. Deleting the old file usually fixes this issue.
