### ISSUE TITLE
Framework 2.0 for client file?

### ISSUE THREAD

**Issue by markleeit** [quasar/Quasar#1061]
How can I make the client file downgrade to framework 2.0 ?
Thank you.

**Comment by BurntDog** [comment]
First you need the framework 2.0 SDK installed so Visual Studio can find and use it and before compiling the source code you need to select (Target framework: what you want) it in "Quasar.Client Properties"

**Comment by MaxXor** [comment]
Downgrading to .NET 2.0 is not supported and requires the re-implementation of many missing methods.
