### ISSUE TITLE
Is it possible to use the ip of my vps, with port open

### ISSUE THREAD

**Issue by pentest01** [quasar/Quasar#1064]
I have tried using portmap.io which doesn't work well for me.

![image](https://user-images.githubusercontent.com/103268912/162470410-2bbc716d-7b50-4161-bd71-c00096d7e631.png)

![image](https://user-images.githubusercontent.com/103268912/162470778-e424c9fc-2642-4465-94a4-f1f1e8f70f32.png)

i used this as host name: tobi101-52814.portmap.io while i used this as port: 52814. But i still get no connection. i'm connected to the openvpn config, while using my expressvpn on. Should the use of my expressvpn be the issue??

**Comment by MaxXor** [comment]
From the looks it seems like you need to enter port 52814. However this is not a support channel for your VPN setup.
