### ISSUE TITLE
Connection issues, even after port forwading

### ISSUE THREAD

**Issue by pentest01** [quasar/Quasar#1065]
After you closed my first issues, I went into looking at portmap.io, i thought i did everything right, the open vpn config is connected, port forwading works well, but i still have issues connecting, i followed @BurntDog instruction on this #896 , but i still can't receive a connection. these are screenshots

![image](https://user-images.githubusercontent.com/103268912/162491048-68bdc314-d4db-4997-8c64-0551ad5aece7.png)

and this is my connection settings

![image](https://user-images.githubusercontent.com/103268912/162491139-c60362e0-8166-49c1-aa2c-850d1898743c.png)
 i used tobi101-61566.portmap.io as hostname and  61566  as port. i ran the client on another pc and i still can't get a connection. I have searched through the issues and followed all instructions, i don't know what i'm still doing wrong.

this is a screenshot of my window's firewall

![image](https://user-images.githubusercontent.com/103268912/162491798-2344e626-55e0-4515-8c97-7b691de48135.png)

**Comment by BurntDog** [comment]
Hmm. Okay you Reset Network TCP/IP stack just to eliminate that as a possible issue and your firewall allows Quasar Server access for traffic it seems (you use port 4782 or or other).  You can check if port is open by running "Quasar Server" then go to "https://canyouseeme.org/" to make sure that port (4782 or any other port you decide to use) is in fact open. Also when you "build" the "client" be sure to use as the port "61566" add host port Not 4782 as portmap will forward to port 4782 which Quasar will be listening on and of course you have OpenVPN running as well. I hope this helps.

**Comment by pentest01** [comment]
Seems https://canyouseeme.org/ works with your internet ip, and won't accept any other input. I used you get signal and it showed port was open, i also deployed a vps and was able to port forward successfully, but it won't receive connection. But i got something yesterday when i was checking, anytime i upload to virus total, i get two connection, and when i try to remote desktop it to it, the interface looks like a vm which wasn't mine. I used ngrok for this, 

![image](https://user-images.githubusercontent.com/103268912/162680601-3f4d4204-1d0e-468c-b2c2-a289ac72661b.png)
 i can't seem to use it for checking any other ip.

**Comment by Gmann101** [comment]
Just asking but is it because of that second picture you had where it says Port: 4782? Try to change it to 61566 I guess, see if that works or not. I don't know the situation nor I know this program very well but that could be an issue maybe? Just try and see if that works.
