### ISSUE TITLE
Cannot connect to other PC's

### ISSUE THREAD

**Issue by robloxtalentshow** [quasar/Quasar#1067]
Hey!
I build a client with my noip adress and the port 1604!
I added the UDP/TCP 1604 Port in my router.

*but...*
The client only works on my pc and not on others.
i tried on a pc with in the same network but still not works!
please help!

https://canyouseeme.org/ says that he can see me you know!
![image](https://user-images.githubusercontent.com/102692707/163584591-0c6a4975-f4c9-46d7-acc4-d3c685028a0a.png)

**Comment by crisponshrooms** [comment]
I used this tutorial it worked for me https://www.youtube.com/watch?v=AcbRpDX5NIo

**Comment by crisponshrooms** [comment]
i can help you on discord aswell Crisp#1954

**Comment by robloxtalentshow** [comment]
> i can help you on discord aswell Crisp#1954

added you

**Comment by yesitshazza** [comment]
> 

did you find a fix if so how?? I can't connect to other pcs

**Comment by MaxXor** [comment]
https://portforward.com/
