### ISSUE TITLE
I lost my client while trying to update.

### ISSUE THREAD

**Issue by crisponshrooms** [quasar/Quasar#1068]
The second i updated my client disconnected and i couldent get it back.The client now doesent reconnect, and even though the build was ran again, nothing is showing up. Ive tried reinstalling quasar and using the same Client key thing. Nothing happens, what do i do? It worked untill i clicked update.

**Comment by MaxXor** [comment]
Did you follow the wiki? https://github.com/quasar/Quasar/wiki/Updating-a-Client

There is a recovery method (via backup) mentioned.
