### ISSUE TITLE
Client-build.exe wont create

### ISSUE THREAD

**Issue by 6stitch9** [quasar/Quasar#1069]
So when I press the "Build Client" button it prompts me with where to save it. I select my wanted loacation, and it says it worked. It was working on 1.3, but now it just says it does and there is no file, its just gone. I scanned for it by just searching the exact name and it is no-where.  How do I fix this?

**Comment by ErickDaCoder** [comment]
windows defender?

**Comment by 6stitch9** [comment]
all my windows defenders are disabled, anything else?

**Comment by MaxXor** [comment]
If Quasar says the file has been built, it's a problem of your OS and/or AV.
