### ISSUE TITLE
Client.exe is getting suspended

### ISSUE THREAD

**Issue by pinak77** [quasar/Quasar#1070]
Whenever I run the client.exe file it runs in background for few seconds and after that when I check my task manager, there it shows that the client.exe process is getting suspended & after that it restarts & again gets suspended & it repeats, what should I do? It was working fine a few weeks ago

**Comment by BurntDog** [comment]
Just checking but you did compile as a release build and not debug? Did you try recompiling and still having this issue?

**Comment by pinak77** [comment]
I'll try recompiling & let you know but, it was working fine a few weeks ago in windows 10 but maybe after a recent update of windows 10, its suspending the process even without the defender, that's the problem I guess

**Comment by pinak77** [comment]
> Just checking but you did compile as a release build and not debug? Did you try recompiling and still having this issue?

hey my problem is solved! there was just a little problem in configuration of RAT, that's it sorry for wasting your time & thank you for helping me out!
