### ISSUE TITLE
Question regarding SQLiteHandler.cs

### ISSUE THREAD

**Issue by MoistCoder** [quasar/Quasar#1072]
I find the SQLiteHandler.cs very interesting and I'm trying to get a better understanding of it.
My question would be: What does CVL & GVL stand for and what are those methods supposed to do?

**Comment by MaxXor** [comment]
Well, thats a good question. :) GVL returns the endindex of a variable length integer. CVL converts the bytes between start- & endindex to a variable length integer (stored as int64). It's much simpler in a official SQLite library, but the dependency was avoided at the time.
