### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by yesitshazza** [quasar/Quasar#1073]
I used portmap.io i port forward and everything read other posts and I do not understand what do i do after i port forward Like i don't know if openVPN will do anything for me if i have to change the port or the ip i have no clue if you can help add me on discord or reply to this Hazza™#9999 - discord

**Comment by MaxXor** [comment]
Check out the wiki: especially part 6 https://github.com/quasar/Quasar/wiki/Getting-Started#6-connecting-the-server-and-client=
