### ISSUE TITLE
Port forwarding wont work

### ISSUE THREAD

**Issue by 6stitch9** [quasar/Quasar#1076]
I followed someones tutorial on how to do it with port.io, becuase I dont have admin access to my router, becuase it wont let me sign in. I added the adress trying both port 8080 which is what i set it too, and for 50196 which is the port for portmap.
still wont work and idk how to fix or what to do. Also it used to work with just i think it was my ipv4 and defualt port, but even that doesnt seem to want to work now

![image](https://user-images.githubusercontent.com/86562545/169590457-aebd19b3-a00c-4efd-9d19-d866ac0ab529.png)
![image](https://user-images.githubusercontent.com/86562545/169590498-47141895-8bcc-4960-9e76-70679f98dcfb.png)
![image](https://user-images.githubusercontent.com/86562545/169591507-0664b3f8-7bba-4577-8cf9-1dcceffeb024.png)
as u can see my open vpn is connected to it

**Comment by MaxXor** [comment]
This is a bug tracker for software bugs, not support requests. Please check out this guide: https://github.com/quasar/Quasar/wiki/Getting-Started Especially check out the Windows firewall rule.
