### ISSUE TITLE
can't connect to client on window 7.

### ISSUE THREAD

**Issue by Tienanh1234** [quasar/Quasar#1077]
Hi guys,
I use quasar and build client on window 11, and client in win 7. But I can't connect to client. I try connect client on win 10 and 11 other, it's working, but on win 7 it's not working. I need help

**Comment by ErickDaCoder** [comment]
already tested on windows 7; did not work. I don't think Quasar is compatible with win7.

**Comment by BurntDog** [comment]
Supported operating systems (32- and 64-bit)
Windows 10
Windows Server 2019
Windows Server 2016
Windows 8/8.1
Windows Server 2012
Windows 7
Windows Server 2008
Windows Vista
For older systems please use [Quasar version 1.3.0](https://github.com/quasar/Quasar/releases/tag/v1.3.0.0)

**Comment by Futureman83** [comment]
Did you insatall in the Win7 Machine the .NET Framework 4.5.2?

**Comment by Tienanh1234** [comment]
> 
I think so
