### ISSUE TITLE
this being updated anymore?

### ISSUE THREAD

**Issue by azzerzzzeqwe** [quasar/Quasar#1078]
hasnt been updated in 2 years. is it discontinued?

**Comment by BlaBlak2** [comment]
idk doesnt look like it tho

**Comment by ErickDaCoder** [comment]
#974

**Comment by yankejustin** [comment]
Realistically, I think it's comfortable to assume that a bunch of people with the knowledge to make this as good as it can be are inevitably way more busy with other ventures. It isn't easy making business-class software without some form of incentive for developers. Hobby projects are easy to put on the shelf.

It's open source- it's never necessarily discontinued. Anyone can be the next person to pick things like this up and make it better.

**Comment by BurntDog** [comment]
[Roadmap](https://github.com/quasar/Quasar/blob/master/ROADMAP.md) and the [associated discussion](https://github.com/quasar/Quasar/issues/674).

Please use the search option before posting other issues. Issue may have already been addressed.
Thank you
