### ISSUE TITLE
Quasar can wake up a computer on lan ? (wol)

### ISSUE THREAD

**Issue by Tienanh1234** [quasar/Quasar#1079]
Hi guys, I have a question. I do not know how use Quasar to wake up or power on my computer from far. Sometimes my house power outage.

**Comment by MaxXor** [comment]
It's possible to power on other PCs in the same network using WoL, but it's not implemented in Quasar. To power on your own PC after a power outage you can set a BIOS option which might be called "Restore PC state on AC/Power Loss".
