### ISSUE TITLE
Unexpected Listen Error

### ISSUE THREAD

**Issue by Endity123** [quasar/Quasar#1082]
Quasar.exe > Settings > Click "Start Listening"

When you do these steps the and press  "Start Listening"  i got an "Unexpected Listen Error"
![2022-06-18 20_53_02-Movies   TV](https://user-images.githubusercontent.com/93891590/174446822-7d77dbc4-819e-4975-8815-b1473e4d67b4.png)

It should have listening on that port but instead gave me that error.

Im using windows 10
Java SE 18 
Microsoft .net 6.0.6 runtime
C++ Redistrib

**Comment by MaxXor** [comment]
Please use a different port on your system. The port you've chosen is already in use by some other software.
