### ISSUE TITLE
How to Setup Quasar for Visual studio 2022

### ISSUE THREAD

**Issue by maxim207** [quasar/Quasar#1084]
Hello guys, I have tried to download the quasar source code and edit it in VS22 and I keep getting errors. Not even dnspy works. + I ca build, debug, or release. I have.NET 6 and I cant install 4.8 because it says your PC already has 4.8 or higher.

**Comment by BurntDog** [comment]
Did you restore the NuGET packages?

**Comment by maxim207** [comment]
How?

**Comment by maxim207** [comment]
> 

How?

**Comment by BurntDog** [comment]
Once you load the project in VS you will see a menu on the right side and on the very first line the project name. Right click on it to see the drop down menu that will have the option to restore NuGET packages. Also make sure any and all anti virus software is disabled or put your project folder in it's exclusion list to avoid AV from deleting certain files.

If this doesn't help please do a search here in issues Topic as I believe similar problems have already been addressed.

**Comment by maxim207** [comment]
> Once you load the project in VS you will see a menu on the right side and on the very first line the project name. Right click on it to see the drop down menu that will have the option to restore NuGET packages. Also make sure any and all anti virus software is disabled or put your project folder in it's exclusion list to avoid AV from deleting certain files.
> 
> If this doesn't help please do a search here in issues Topic as I believe similar problems have already been addressed.

can u edit it in dnspy I just wanna change icon name button text etc

**Comment by BurntDog** [comment]
Are you on the correct GitHub project page? This Quasar is a Remote Administrator Tool. I ask because others have confused this project with a Kodi or some kind of streaming addon called "Quasar"

**Comment by maxim207** [comment]
> Are you on the correct GitHub project page? This Quasar is a Remote Administrator Tool. I ask because others have confused this project with a Kodi or some kind of streaming addon called "Quasar"

Iam I know it a rat is there A way because I cant get it to work.

**Comment by BurntDog** [comment]
It can be any number of things. First do a search you may find a fix or post more information/screen shot on the errors, error code(s) you are getting.

**Comment by maxim207** [comment]
> his Quasar is a Remote Administrator Tool. I ask because others have confused this project with a Kodi or some kind of streaming addon called "Quasar"

could you  send a zip file with quasar already compiled?  + the sln

**Comment by ErickDaCoder** [comment]
pre-compiled binaries are already available in the releases section.

**Comment by maxim207** [comment]
<

> It can be any number of things. First do a search you may find a fix or post more information/screen shot on the errors, error code(s) you are getting.

Severity Code Description Project File Line Suppression state
Error MSB3821 The Forms\FrmAbout.resx file could not be processed because it is on the Internet, in the Restricted Sites zone, or has the Web markup. Remove the web mark if you want to process these files

**Comment by maxim207** [comment]
Fixed it all
