### ISSUE TITLE
Compilation with 4 errors and no EXE

### ISSUE THREAD

**Issue by oHeckGage** [quasar/Quasar#1087]
**Describe the bug**
Whenever I compile Quasar, 4 errors come up.

**Expected behavior**
Get Server.exe and setup the client

**Screenshots**
![image](https://user-images.githubusercontent.com/68713542/180234358-eed00928-3bb0-4f48-8c8d-371c939bdad0.png)
(I have installed 4.8 SDK)
![image](https://user-images.githubusercontent.com/68713542/180234589-06bd77ef-5412-43af-b568-bb722ab1fa6b.png)

**System**
 - Server OS: ?
 - Client OS: ?
 - Server installed .NET Framework version: 4.8
 - Client installed .NET Framework version: 6
 - Quasar Version: 1.4.0
 - Build configuration: ?

**Additional context**

**Comment by BeneathTheOrion** [comment]
Do you need to compile it? There are binaries already compiled for release at 
https://github.com/quasar/Quasar/releases/download/v1.4.0/Quasar.v1.4.0.zip

**Comment by MaxXor** [comment]
The errors describe what you need to do.
