### ISSUE TITLE
virus en el archivo zip

### ISSUE THREAD

**Issue by pipounix** [quasar/Quasar#1091]
![quasar](https://user-images.githubusercontent.com/84748588/184256240-9b31bb25-0348-493a-9e14-5a61703a0f7b.png)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System**
 - Server OS: [e.g. Windows 10]
 - Client OS: [e.g. Windows 7]
 - Server installed .NET Framework version: [e.g. v4.8]
 - Client installed .NET Framework version: [e.g. v4.8]
 - Quasar Version: [e.g. 1.3.0 or commit-id]
 - Build configuration: [e.g. Debug/Release]

**Additional context**

**Comment by ErickDaCoder** [comment]
no es un virus. creo que se arregla con presionar ctrl+j y click allow download.

**Comment by BurntDog** [comment]
smh.....

**Comment by ErickDaCoder** [comment]
> smh..... 

this isn't even an issue about quasar

**Comment by BurntDog** [comment]
> > smh.....
> 
> this isn't even an issue about quasar
> 
> they also didn't fill the fields with information.

Yes, I agree
