### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by CoreLine76** [quasar/Quasar#1094]
Can you provide the compiled version?

**Comment by ErickDaCoder** [comment]
[Check the releases page](https://github.com/quasar/Quasar/releases)
your browser and your av will say its a virus, but it isnt. just add an exception to quasar's folder.

**Comment by CoreLine76** [comment]
> [Check the releases page](https://github.com/quasar/Quasar/releases) your browser and your av will say its a virus, but it isnt. just add an exception to quasar's folder.

Could you please give the compiled version of 1.4.1?

**Comment by CoreLine76** [comment]
Thank you. Please closed ticket.
