### ISSUE TITLE
FuD

### ISSUE THREAD

**Issue by CoreLine76** [quasar/Quasar#1095]
What should we do about FUD, sir? Also, which dialog lines should be renamed with dnspy.

**Comment by BurntDog** [comment]
Sorry since this is not a Hacker forum we don't discuss methods here. Also this software is meant for legal use and you can simply add a exclusion to your AV llist.

**Comment by ErickDaCoder** [comment]
this is a remote administration tool, not a remote access trojan. if you want to use it on another computer, add an exclusion to it in windows defender / your av.
