### ISSUE TITLE
ProtoBuf Deserialization

### ISSUE THREAD

**Issue by Senc3951** [quasar/Quasar#1096]
Hi, I tried making a project based on this rat, but according to ProtoBuf documentation, in order to deserialize parent object to a child one, eg. IMessage to ClientIdentification, IMessage must contain an attribute saying [ProtoInclude... child object] which in this project wasn't done, but somehow it still works, but when I tried deserializing IMessage to a child without this attribute, it didn't work. Only when I included the attribute, it worked.

**Comment by Senc3951** [comment]
The problem is not deserializing to IMessage, but converting from iMessage to the wanted class

**Comment by MaxXor** [comment]
This is shown here: https://github.com/quasar/Quasar/blob/16a4702d0e2064070ee7e6319bd708b786294820/Quasar.Client/Networking/QuasarClient.cs#L99-L112

**Comment by Senc3951** [comment]
I probably didn't explain myself well, This project depends heavily on the ability to convert from IMessage to any class that inherits from it. This conversion should only work when adding the ProtoInclude attribute, to inform ProtoBuf that IMessage may actually be a child class, but this project doesn't include this attribute and somehow the conversion still works.

You can find an example here: https://stackoverflow.com/questions/12988964/how-to-serialize-inherited-class-with-protobuf-net

**Comment by MaxXor** [comment]
Can you test using the same Protobuf version used in this project? Maybe it only works with the rather "outdated" version here.

**Comment by Senc3951** [comment]
From some reason it still doesn't work, here is my serialization, deserialization code

```cs
public static byte[]? Serialize<T>(T message) where T : notnull, IMessage
{
    try
    {
        using MemoryStream ms = new();
        Serializer.Serialize(ms, message);
        
        return ms.ToArray();
    }
    catch { return null; }
}

public static IMessage? Deserialize(byte[] data)
{
    try
    {
        using MemoryStream stream = new(data);
        return Serializer.Deserialize<IMessage>(stream);
    }
    catch { return default; }
}
```
