### ISSUE TITLE
Will hosting this program on my computer put me at risk?

### ISSUE THREAD

**Issue by tomjonesius** [quasar/Quasar#1097]
I downloaded the .zip file, extracted it to a folder, then moved it to my external hard drive. I then disconnected and did a virus scan, and three issues were found by BitDefender in locations nowhere near where I originally saved the files. Have I just inadvertently infected myself? I have removed the 'threats' and will leave my hard drive disconnected for the time being.

**Comment by ErickDaCoder** [comment]
_which_ zip file.

**Comment by tomjonesius** [comment]
The one found here (this repository)

https://github.com/quasar/Quasar/archive/refs/tags/v1.4.0.zip

**Comment by ErickDaCoder** [comment]
are you sure they were exe's and not just data files?

**Comment by BurntDog** [comment]
Make sure you get this software from here only. FYI just by being connected to the internet alone your at risk. This program itself has proven secure.

**Comment by tomjonesius** [comment]
I don't think any of the 3 were .exe files. However I never actually ran the program so how would the files have gotten in my system?

**Comment by BurntDog** [comment]
https://github.com/quasar/Quasar/releases/download/v1.4.0/Quasar.v1.4.0.zip

**Comment by ErickDaCoder** [comment]
if you didnt run quasar then theyre 100% unrelated.

**Comment by tomjonesius** [comment]
My AV identified them as Quasar and one came up as a password stealer (i think client.bin?)

**Comment by ErickDaCoder** [comment]
client.bin is a file that quasar uses to **___generate the client___**

**Comment by tomjonesius** [comment]
How did it end up in my files without me opening the program though? That's the part that's got me concerned

**Comment by ErickDaCoder** [comment]
client.bin is _part_ of quasar. it's in the zip file.

**Comment by tomjonesius** [comment]
I know, however, the .zip file was not even on my machine when I did the scan

**Comment by ErickDaCoder** [comment]
your av probably quarantined it. explains why client.bin wasnt where you put quasar.

**Comment by BurntDog** [comment]
If you don't understand how these programs work it's best for you not to use it until you do.

**Comment by tomjonesius** [comment]
Can you point me in a helpful direction to find out more

**Comment by BurntDog** [comment]
There are videos on YouTube that help you better understand this app. That client.bin file along can't do anything. It's used in both compiling or setting up this app.

**Comment by tomjonesius** [comment]
Ok so just to clarify.
BitDefender is tripping and my computer is fine?

**Comment by ErickDaCoder** [comment]
yes

**Comment by MaxXor** [comment]
@ErickDaCoder @BurntDog Thanks for covering this issue. I think everything to get in the right direction has been said. You can also check out this guide: https://github.com/quasar/Quasar/wiki/Getting-Started

However, @tomjonesius I don't think this AV scan is meaningful if you didn't do a scan BEFORE and AFTER downloading Quasar. It could be possible that you had a virus on your computer for weeks and just now noticed it.

**Comment by knackrack615** [comment]
Probably what happened here is OP used WinRAR's drag and drop function to extract Quasar, WinRAR will temporarily drop the files on %temp% when extracting that way, that's most likely what was detected.
