### ISSUE TITLE
Server migration?

### ISSUE THREAD

**Issue by hexclann** [quasar/Quasar#1099]
I have 2 windows 10 clients currently connected to Qusar server on my laptop. I will be upgrading to a new machine soon and I will not be cloning my current OS. Is it possible to install the new quasar client and migrate the existing clients to the new server?

**Comment by MaxXor** [comment]
Yes, no problem. Just copy the Quasar directory with the config and the `quasar.p12` file to the new computer. Check your firewall settings and port forwardings at your router.

**Comment by hexclann** [comment]
Thanks!
