### ISSUE TITLE
Cant manage to get the victim connection

### ISSUE THREAD

**Issue by KeparYTbcc** [quasar/Quasar#1102]
I started the rat on my second computer and it wont connect to the my panel

firewall rules are opened (port 2222 inbound/outbound udp/tcp Accepted)

![image](https://user-images.githubusercontent.com/67996155/202351465-10a57e89-e527-4b1a-a52c-9a5a23277890.png)

**Comment by BurntDog** [comment]
Did it work using Loopback? To the best of my knowledge you can not connect back on the same network running both Server and Client other then using Loopback on the same machine. Have you tries setting up and using portmap.io with OpenVPN?

If you have connection issues using OpenVPN do the steps listed below (has always fixed my issue).

Reset Network TCP/IP stack
If your TCP/IP stack is corrupted it can be reseted with the following commands.

Windows XP:
1. Search for Command Prompt > Run As Administrator
2. netsh winsock reset
3. netsh int ip reset
4. ipconfig /flushdns
5. Restart computer

Windows Vista, 7, 8, 10:
1. Search for Command Prompt > Run As Administrator
2. netsh winsock reset catalog
3. netsh int ipv4 reset reset.log
4. netsh int ipv6 reset reset.log
5. Restart computer

Scenario 1: you need to make sure that these below services are started and made automatic.

DNS Client service started and on automatic
SSDP Discovery service started and on automatic
UPnP Device Host service started and on automatic
Function Discovery Resource Publication service started and on automatic

**Comment by KeparYTbcc** [comment]
already tried

**Comment by BurntDog** [comment]
Please explain. Did Loopback work? Did portmap.io work and if not what were the issues? ect...

**Comment by MaxXor** [comment]
Please double-check your firewall settings and/or router settings. This is a bugtracker for actual bugs with Quasar, not port forwarding issues.
