### ISSUE TITLE
Help me please.

### ISSUE THREAD

**Issue by localidiotwithtoomuchtime** [quasar/Quasar#1105]
So i have port forward on port 4782 and i can see my self on (https://portchecker.co/checking) with a open port.
pic; https://imgur.com/a/56pUpSX

And i build a client with my no ip domain (also if i check the port forward with the domain it works. )
it wont connect on my pc.
I tried difreent ports but no luck. help me please.

**System**
 - Server OS: [ Windows 7 myself]
 - Client OS: [Windows 7 myself]
- Quasar Version: [v1.4.0]

**Comment by ErickDaCoder** [comment]
did you do the no-ip configuration correctly?

**Comment by MaxXor** [comment]
Please check your windows firewall and the https://github.com/quasar/Quasar/wiki/Getting-Started guide. This is an issue tracker for actual bugs about the software.

**Comment by localidiotwithtoomuchtime** [comment]
i think i did the no-ip configuraton corectly https://imgur.com/a/t5d66mJ

and i disabled the firewall complitly

and how to change the topic tracker

**Comment by localidiotwithtoomuchtime** [comment]
shit i leaked my ip

**Comment by BurntDog** [comment]
> shit i leaked my ip

If you own and use a regular router you can change your MAC address and get assigned a new ip. There are videos on how to, it's easy.

**Comment by localidiotwithtoomuchtime** [comment]
i know but i need help with this shit

**Comment by BurntDog** [comment]
> i know but i need help with this shit

If you didn't find a answer doing a search here s this has been addressed numerous times you can search YouTube there are step by step videos floating around on there.
