### ISSUE TITLE
update

### ISSUE THREAD

**Issue by warn69** [quasar/Quasar#1107]
Ever gonna be a new update?

**Comment by ErickDaCoder** [comment]
slow development, but highly probable.

**Comment by warn69** [comment]
its not working can u help me? warn#7609

**Comment by ErickDaCoder** [comment]
> its not working can u help me? warn#7609

did you follow the wiki's instructions?

**Comment by BurntDog** [comment]
> its not working can u help me? warn#7609

Search YouTube there are a few how to videos.
