### ISSUE TITLE
No new connections on external pc

### ISSUE THREAD

**Issue by Matteo02p** [quasar/Quasar#1112]
I need help please

**Comment by ErickDaCoder** [comment]
maxxor gonna have to hit you with the getting started wiki because SOMEBODY didn't use their eyes!

**Comment by Matteo02p** [comment]
> maxxor gonna have to hit you with the getting started wiki because SOMEBODY didn't use their eyes!

How to see new connections?

**Comment by MaxXor** [comment]
Please use the issue template and provide some more information of what you have tried. Also, check out [Getting Started guide](https://github.com/quasar/Quasar/wiki/Getting-Started).
