### ISSUE TITLE
Add active window

### ISSUE THREAD

**Issue by Jackxxon** [quasar/Quasar#1113]
Can anyone help me to add active window
Thank you

**Comment by ErickDaCoder** [comment]
what is an active window

**Comment by Jackxxon** [comment]
display the active window at the current moment
![Screenshot_1](https://user-images.githubusercontent.com/121407683/209484509-952de247-da9c-446a-bbf3-5adfdece5fe4.png)

**Comment by MaxXor** [comment]
Please use the search function, there is an open feature request for this already: https://github.com/quasar/Quasar/issues/629
