### ISSUE TITLE
Can't connect to my port through another PC even though it's open

### ISSUE THREAD

**Issue by dacukun** [quasar/Quasar#1115]
Hi

My problem is that when I try to listen to the default port after having opened the client-built.exe on both this computer and a computer from a different IP address only this computer shows up in the menu. I know that it's possible to circumvent this by opening a port at portmap.io but when I do it only gives me 3-4 FPS at most whereas when I connect through my own local IP it gives me anywhere between 20 and 40 FPS. I've also looked through my firewall settings and checked with telnet command on cmd if the port from my own IP address is open and all seems to be clear. So my questions are 1. is it possible to connect through my own local IP address? and 2. if not, is there any way to substantially increase the FPS through my portmap.io connection

**Comment by MaxXor** [comment]
Hey, the current remote desktop implementation is not the best, it's best to decrease the quality a bit using the slider at the top. That should help!
