### ISSUE TITLE
Trojan:MSIL/Perseus.AKR!rfn detected when downloading Quasar.

### ISSUE THREAD

**Issue by DeGuindos** [quasar/Quasar#1120]
**Describe the bug**
Windows Defender blocks the download of Quasar upon detection of Trojan:MSIL/Perseus.AKR!rfn

**To Reproduce**
1. Go to https://github.com/quasar/Quasar/releases
2. Click on [Quasar.v1.4.0.zip](https://github.com/quasar/Quasar/releases/download/v1.4.0/Quasar.v1.4.0.zip)

**Expected behavior**
Get the installer
![Captura de pantalla 2023-01-24 100303](https://user-images.githubusercontent.com/45500142/214250755-50342fcb-d82b-4988-9188-3df22bd22fb8.jpg)
.

**Screenshots**

**System**
 - Client OS: Windows 11

**Comment by DeGuindos** [comment]
New Trojan detected: Trojan:Win32/Masson.A
![Captura de pantalla 2023-01-24 100535](https://user-images.githubusercontent.com/45500142/214251725-0c35aa81-db82-4b29-a46c-2d4a62ae9825.jpg)

**Comment by BurntDog** [comment]
This is normal and if you use our search function you will find more in-depth answers. Thank you
