### ISSUE TITLE
How to obfuscate client

### ISSUE THREAD

**Issue by Computerist-Virus** [quasar/Quasar#1125]
I just want to know that in which file do we have to do obfuscation in order to make our client.exe FUD

**Comment by BurntDog** [comment]
Sorry buddy we don't discus those topics here. You'll need to seek out that information else where.

**Comment by ErickDaCoder** [comment]
> I just want to know that in which file do we have to do obfuscation in order to make our client.exe FUD

Quasar does not support FUD as Quasar was made for legitimate use.
