### ISSUE TITLE
The option “Restore NuGet Packages“ is not able for me 

### ISSUE THREAD

**Issue by caraidenome** [quasar/Quasar#1126]
**Describe the bug**
II just can't Restore NuGet Packages

**To Reproduce**
1. Go to 'Quasar-master'
2. Click on 'Quasar'
3. Right Click on 'Solution Quasar'

**Expected behavior**
The option to Restore NuGet Packages will not be able

**Screenshots**
![Print Quasar](https://user-images.githubusercontent.com/110922781/217398000-391c9686-fab1-4672-93b1-69e5b1be8389.png)

**System**
 - Server OS: Windows 11
 - Client OS: nobody
 - Server installed .NET Framework version: v4.8
 - Client installed .NET Framework version: v4.8
 - Quasar Version: 1.4.0
 - Build configuration: actualy I don't know

**Additional context**

**Comment by ErickDaCoder** [comment]
you didn't fill out the form einstein

**Comment by caraidenome** [comment]
kkkkkk true

**Comment by MaxXor** [comment]
Please check out the microsoft docs: https://learn.microsoft.com/en-us/nuget/consume-packages/package-restore#restore-using-visual-studio
