### ISSUE TITLE
Using Quasar on Kali Linux

### ISSUE THREAD

**Issue by SirArda19** [quasar/Quasar#1130]
Hello, I am using KALI LINUX over the vm VirtualBox program, because I was looking for a RAT with a panel, they recommended Quasar as the best, but  it needed .NET.
In short, how can I run Quasar on kali linux, can someone tell me step by step?

**Comment by MaxXor** [comment]
Please see here for a possible workaround: https://github.com/quasar/Quasar/issues/1116
