### ISSUE TITLE
What does Reverse Proxy do? And how do I use it? 

### ISSUE THREAD

**Issue by DannyBrock123** [quasar/Quasar#1135]
Hello, I just want to know how to use Reverse Proxy and what does it do also what is it used and helpful for.

**Comment by MaxXor** [comment]
Basically you can use a connected Quasar client as a proxy server and browse the web as if it originated from the clients PC. Once you started the reverse proxy on a client, you configure your browser to use 127.0.0.1 and your selected port as SOCKS5 proxy. There are many use cases for that, e.g. accessing internal web resources which are not reachable from the outside or bypassing IP restrictions by using the clients IP address.

See here (replace Internet with Quasar Server and Proxy with Quasar Client): 
![image](https://user-images.githubusercontent.com/7271470/224494860-7f993c14-2765-4c36-b269-736124bc180e.png)
