### ISSUE TITLE
My security software says this software is a virus

### ISSUE THREAD

**Issue by liujian1368928** [quasar/Quasar#1137]
### Quasar version

Latest version

### Server installed .NET version

Net6

### Server operating system

Windows 7/Server 2008 R2

### Client installed .NET version

Net6

### Client operating system

Windows 10/Server 2019/2016

### Build configuration

Debug

### Describe the bug

![1678764141256](https://user-images.githubusercontent.com/23169722/224885061-17ef8520-6016-4073-b278-d244350f586d.jpg)

I unzip and start up locally, and my security software says virus

### How to reproduce

1

### Expected behavior

1

### Actual behavior

Decompression start

### Additional context

1

**Comment by BurntDog** [comment]
Please use our search option. This has been answered sever times (It is 100% Safe). Thank you

**Comment by MaxXor** [comment]
https://github.com/quasar/Quasar/issues/979
