### ISSUE TITLE
password recovery not working

### ISSUE THREAD

**Issue by ehack01** [quasar/Quasar#1138]
I tried this tool to help recover my windows password, it won't work. I even tried saving password in my browser to check if it can recover the password but still not able to recover password. how can I modify the code to help me with this feature.
![Capture](https://user-images.githubusercontent.com/127857976/225009495-a50dda15-4f7f-409d-8cc5-5ae2dc5c208f.JPG)

**Comment by BurntDog** [comment]
Are you running the client as user or admin?

**Comment by MaxXor** [comment]
Windows account passwords are not supported. Only browsers. Please use the complete issue template and describe at least which browsers you tried.
