### ISSUE TITLE
Keylogger issue

### ISSUE THREAD

**Issue by thepersonalcomputer** [quasar/Quasar#1140]
### Quasar version

1.4.1

### Server operating system

Windows 11/Server 2022

### Client operating system

Windows 11/Server 2022

### Build configuration

Debug

### Describe the bug

I'm running v 1.4.1 and for some reason some of the logs of the key logger will not decrypt and it just shows random symbols. Could somebody please help?

### How to reproduce

Try key logger

### Expected behavior

To be able to read logs.

### Actual behavior

Cannot read them.

**Comment by BurntDog** [comment]
When this happens, Deleting the old log file prior to using keylogger may help.

**Comment by thepersonalcomputer** [comment]
> When this happens, Deleting the old log file prior to using keylogger may help.

On the client machine? On the host I assume that has to stay on all the time for the keylogger too?

**Comment by BurntDog** [comment]
client machine

**Comment by MaxXor** [comment]
Did you update your clients from 1.4.0 to 1.4.1?

**Comment by SKRecreated** [comment]
The solution is (if you selecetd appdata in quasar builder settings) is to remote access the machine, go to the user's appdata, then open the defaulty titled 'Logs' folder and delete all the logs. Then wait a minute and go back to quasar manager and click on the keylogging tool and make sure to select get logs and it should work.

**Comment by BurntDog** [comment]
> The solution is (if you selecetd appdata in quasar builder settings) is to remote access the machine, go to the user's appdata, then open the defaulty titled 'Logs' folder and delete all the logs. Then wait a minute and go back to quasar manager and click on the keylogging tool and make sure to select get logs and it should work.

What I said but in lesser words like over a month ago.

**Comment by MaxXor** [comment]
Do you think we should handle old keylogger logs differently, e.g. upgrading them (re-encrypt) to the new keys during a client update?

**Comment by BurntDog** [comment]
> Do you think we should handle old keylogger logs differently, e.g. upgrading them (re-encrypt) to the new keys during a client update?

Only if you feel it's worth the time and would solve the occasional issue.
I realize you have enough to do.
