### ISSUE TITLE
Help needed 

### ISSUE THREAD

**Issue by yesitshazza** [quasar/Quasar#1141]
I need help setting up quasar if im being honest I have no fucking clue how to set it to work over the place yk just lmk

**Comment by yesitshazza** [comment]
yes I do know that there is, but how do I get it to work on different pc's that are not near me yk

**Comment by yesitshazza** [comment]
> Did you try finding a video on YouTube? The visual may help avoid misunderstandings. I know there was several tuts a few years ago.
yes I do know that there is, but how do I get it to work on different pc's that are not near me yk

**Comment by BurntDog** [comment]
You'll need to explain what you have tried and how it has failed in as much detail as possible. We also have a search function here where this topic has been answered and solved, you'll find a faster solution using our search function.
