### ISSUE TITLE
Password Recovery doesn't work on most computers

### ISSUE THREAD

**Issue by jamiekarvans** [quasar/Quasar#1145]
### Quasar version

1.4.1

### Server operating system

Windows 10/Server 2019/2016

### Client operating system

Windows 10/Server 2019/2016

### Build configuration

Release

### Describe the bug

password recovery doesn't work on 80% of computers, and account type of all of them is Admin so they run as admin aswell
doesn't matter the windows, i have tried on windows 7,8,10,11 and its mostly 50/50 and those that it sends the password are not complete
just to make sure i have run the tool from https://www.nirsoft.net/utils/web_browser_password.html and it shows all the passwords correctly but not showing in the quasar tested chrome,firefox,edge browsers

### How to reproduce

testing on 20 computers 14 of them don't show any passwords while passwords are saved 

### Expected behavior

saved browser passwords

### Actual behavior

N/A 
no passwords

### Additional context

please fix the issue, maybe by adding code to just taking the login data file in appdata and taking encrypted key from local state,(atleast that's how it is for chrome) and decrypting and sending passwords

also would be nice to have the cookies aswell and maybe even better to have the option to send the keylogs and passwords to email on start up so no need to wait for server and client be online at same time to see the keylogs and passwords

**Comment by jamiekarvans** [comment]
Yes I know, that's what I'm asking to add it to quasar
It's also alot better if these files would be sent for you on startup, most of the time clients are not online at same time with server and even most of the time clients get disconnected for ever and only run for onetime which you will lose that data, so it's alot wise to have this option to be sent to email

**Comment by BurntDog** [comment]
It's my understanding that setting a Master password provides an extra layer of protection which would need to be cracked or as previously stated, intercepted. That is not the intended purpose of Quasar (Quasar is not a Spy Tool). And for reason of privacy concerns I don't see this being implemented anytime soon (being open source you're free to add or subtract features at will).

**Comment by jamiekarvans** [comment]
1.In none of the browsers there is a master key,
And the app that I mentioned recovers the password pretty well
2.making the password recovery to actually work is not intended of the quasar app?
3. It's interesting you talk instead of the author, you're not, so get out of your head and don't give people wrong information.

**Comment by 0xE232FE** [comment]
Quasar should only used for Admins, not as spyware and not as Trojan horse.

**Comment by BurntDog** [comment]
Did you try running it with Admin privilege's as well?

**Comment by jamiekarvans** [comment]
Yes I added to the binder and the binder itself asks for admin privilege
Also they show account type is admin

**Comment by BurntDog** [comment]
Another thing you can try if you haven't is to delete the LOG file on the client machine (a new one will be auto generated). A common issue is if it gets corrupt it would cause such issues.

**Comment by MaxXor** [comment]
I tested latest Edge again, with no master password set. It works fine. What do you mean by "Yes I added to the binder and the binder itself asks for admin privilege"???

**Comment by BurntDog** [comment]
If you're using a Binder or Cryptor type of third party software it is very possible Quasar's coding/functions were altered in such a way it broke the client.
