### ISSUE TITLE
Cannot Download Entire Folder

### ISSUE THREAD

**Issue by kangming06** [quasar/Quasar#1146]
### Problem description

When I use `File Manager`, I am currently not able to download entire folders from the client side. Instead, I am limited to downloading files one by one, which can be time-consuming and inconvenient when I need to transfer multiple files within a folder.

### Proposal

To improve the experience and streamline the file transfer process, I propose implementing a feature that allows me to download entire folders from the client side.

**Comment by MaxXor** [comment]
Duplicate of https://github.com/quasar/Quasar/issues/262
