### ISSUE TITLE
Startup not working

### ISSUE THREAD

**Issue by DogusCzk** [quasar/Quasar#1147]
### Quasar version

1.4.2

### Server operating system

Windows 11/Server 2022

### Client operating system

Windows 11/Server 2022

### Build configuration

Release

### Describe the bug

Startup not working

### How to reproduce

Startup not working

### Expected behavior

Startup not working

### Actual behavior

Startup not working

### Additional context

when i restart my computer it won't turn on again

**Comment by DogusCzk** [comment]
Could it be that the loader I'm using is breaking the startup because it shows up at startup but won't open?

**Comment by MaxXor** [comment]
Most likely yes. This is a bug tracker for Quasar-related issues, not problems with other tools.
