### ISSUE TITLE
STARTUP PROBLEM

### ISSUE THREAD

**Issue by DogusCzk** [quasar/Quasar#1148]
### Quasar version

1.4.2

### Server operating system

Windows 11/Server 2022

### Client operating system

Windows 11/Server 2022

### Build configuration

Debug

### Describe the bug

Startup not working

### How to reproduce

Startup not working

### Expected behavior

Startup not working

### Actual behavior

Startup not working

**Comment by DogusCzk** [comment]
the problem is not in the loader but in the starting position

**Comment by DogusCzk** [comment]
Why doesn't it work when I set the starting file location like this?
C:\Program Files\Common Files\CheckUpdate.exe

**Comment by DogusCzk** [comment]
Is it because it doesn't start as administrator after restarting the computer?

**Comment by DogusCzk** [comment]
yes i found the problem where quasar restarts the computer does not work again in places that require admin permission

**Comment by DogusCzk** [comment]
Quasar not running as standalone administrator how can I fix this

**Comment by DogusCzk** [comment]
Bruh why u closing my issue

**Comment by BurntDog** [comment]
If you would like it to start/run with "adman rights" the easiest way is to use Task Manager.
