### ISSUE TITLE
Quasar Client

### ISSUE THREAD

**Issue by ananinamisa** [quasar/Quasar#1149]
### Problem description

When any user opens rat, it shows as quasar client in task manager, is there any way to hide it?
![image](https://user-images.githubusercontent.com/129632219/230421365-5b1c424a-f3e4-497f-819a-50705f2d5fc5.png)

### Proposal

When any user opens rat, it shows as quasar client in task manager, is there any way to hide it?
![image](https://user-images.githubusercontent.com/129632219/230421365-5b1c424a-f3e4-497f-819a-50705f2d5fc5.png)

**Comment by BurntDog** [comment]
Since Quasar is mean as a legit legal Admin Tool no such info here or on any future roadmap plans.
