### ISSUE TITLE
Quaser Rat doesnt show connections

### ISSUE THREAD

**Issue by Sindoes** [quasar/Quasar#1150]
### Quasar version

Lastest

### Server installed .NET version

.NET 60

### Server operating system

Windows 11/Server 2022

### Client installed .NET version

.NET 60

### Client operating system

Windows 11/Server 2022

### Build configuration

Release

### Describe the bug

I dont know whats wrong but it isnt working when i build exe i open app in my other laptop nothing happens
this is my settings
whatiszatman.ddns.net
i use no ip
port: 4782

### How to reproduce

I dont know whats wrong but it isnt working when i build exe i open app in my other laptop nothing happens
this is my settings
whatiszatman.ddns.net
i use no ip
port: 4782

### Expected behavior

i excepted it to work

### Actual behavior

nothing

### Additional context

whatiszatman.ddns.net
i use no ip
port: 4782

**Comment by BurntDog** [comment]
Did you set the compiler to build (Release and Not Debug) and then test the client.exe using loopback 127.0.0.1?

**Comment by Sindoes** [comment]
whats loopback
wdym compiler i download from release

**Comment by Sindoes** [comment]
btw do u have discord i dont wanna talk here

**Comment by MaxXor** [comment]
Please just follow this guide, especially part 4 and 6: https://github.com/quasar/Quasar/wiki/Getting-Started

You most likely have a router inbetween your PC and the web. So add port forwarding rules accordingly.
