### ISSUE TITLE
Unexpected Socket Error Code: 10013 (on free ports)

### ISSUE THREAD

**Issue by CodeShane** [quasar/Quasar#1151]
### Quasar version

1.4.0, 1.4.1

### Server installed .NET version

.NET Framework v4.0.30319

### Server operating system

Windows 10/Server 2019/2016

### Client installed .NET version

n/a, the same I think

### Client operating system

Windows 10/Server 2019/2016

### Build configuration

Release

### Describe the bug

Not sure if this is just my issue or if default port and docs should be updated?

Control server can't start listening on port 4782 through 4836, or randomly on other ports below 4782 or above 4836, giving an error on start (or clicking "start listening"):
```
Unexpected Socket Error

An unexpected socket error occurred: An attempt was made to access a socket in a way forbidden by its access permissions.

Error Code: 10013
```

**Troubleshooting done:**

1) Verified these ports are not being used using two methods:
`netstat -ano | findstr "YourPortHere"`
`nirsoft currports x64 (cports.exe)`
2) Problem occurs with Firewall and Antivirus both disabled.
3) Occurs even when "run as administrator"
4) Occurs for v1.4.0 and v1.4.1

**Research done**
Similar user-specific issues:
2021 issue - https://github.com/quasar/Quasar/issues/945
2018 issue - https://github.com/quasar/Quasar/issues/651

**Next steps**
I'm going to try updating .NET framework (don't expect this to do much).
Will try building locally from source.

**Use case**
Doubt it's relevant, but wanted to thank you for this tool, it's very helpful for managing my kids' PCs remotely. Getting Windows defender to leave the client installers and client binaries alone is very challenging, if I ever get this scripted or otherwise solved I'll share but this isn't my forte. Thanks again!

### How to reproduce

Download release from github and extract.
Attempt to listen (on "listen on start" setting or using "Start listening" button) with listen port set to any 4782 through 4836, inclusive.

### Expected behavior

Server UI will show "listening" and begin seeing client connections.

### Actual behavior

Server will receive an error and display pop-up.

### Additional context

![2023-04-07 12_43_35-C__bin_Quasar v1 4 1](https://user-images.githubusercontent.com/1733824/230664081-ad96f80c-6c27-40bb-9306-90699cf14c39.png)

**Comment by MaxXor** [comment]
Hey, thanks for the feedback. :)

I'm not entirely convinced that this issue is related to Quasar. As you already mentioned, the previously opened similar issues were unresolved as well... I am not able to reproduce this. What AV do you use exactly, maybe it's not "really" disabled?

There is a neat little software called [TCP/IP Builder](https://www.drk.com.ar/en/legacy/tcp-ip-builder/) which can create TCP sockets on specific ports, just like Quasar. Can you please check if that tool works if you enter "0.0.0.0", port 4782, TCP and click "Create Socket"? The same error should appear there too if my theory is right.

**Comment by CodeShane** [comment]
I'm not at all convinced this is related to Quasar, either, but since the port didn't appear in use I thought it might be worth looking into except..

1. Verified Quasar still wouldn't listen on 4782.
2. Installed TCP-IP-Builder, ran with settings as described, tested with `ncat` and it connected.
3. Destroyed socket.
4. Checked Quasar again and it says it's listening on port 4782 now, although clients built for that server port never connect even after restarting the client/agents. After switching server to an alternate port, the one PC client/agent built for that connects within 30 seconds.

![2023-04-11 18_31_01-TCP_IP Builder - Copy](https://user-images.githubusercontent.com/1733824/231317413-996b32e4-3a79-4b8f-ac55-984593bc4b71.png)

Quasar works on other ports, and I can no longer reproduce. Thank you for your help.

If I encounter the problem again I'll try and capture some more useful info.
