### ISSUE TITLE
Client won’t show up

### ISSUE THREAD

**Issue by Anido273** [quasar/Quasar#1152]
### Quasar version

1.4.1

### Server installed .NET version

.NET 6.0

### Server operating system

Windows 10/Server 2019/2016

### Client installed .NET version

.NET 6.0

### Client operating system

Windows 10/Server 2019/2016

### Build configuration

Release

### Describe the bug

I created the software for the client and send it to them. I turned listening on. But as they opened it (with admin rights) nothing happened on my dashboard. All windows security features are off on their PC and it is brand new (now other software installed). So I tried opening the software on my own laptop and it worked just fine. Why is that? And is there anything I could do about it? Thank you.

### How to reproduce

Install Quasar, click on „build“, build the software, send it to your client, start to listen

### Expected behavior

The client‘s PC should show up on my dashboard.

### Actual behavior

My dashboard stays completely empty and nothing happens.

**Comment by MaxXor** [comment]
Hello, this is a port forwarding and/or firewall issue, not Quasar issue.
