### ISSUE TITLE
Unexpected disconnection makes the client undetectable from the server.

### ISSUE THREAD

**Issue by Kabir404** [quasar/Quasar#1153]
### Quasar version

1.4.1

### Server installed .NET version

Whatever ships with Windows by default

### Server operating system

Windows 10/Server 2019/2016

### Client installed .NET version

Whatever ships with Windows by default

### Client operating system

Windows 10/Server 2019/2016

### Build configuration

Release

### Describe the bug

After creating the client and setting its host and ports to [Portmap](https://portmap.io), The client runs on the target machine and gets connected to the server pretty much instantly for the first time. But whenever the client gets disconnected unexpectedly(Like BSOD/Power Loss), The server doesnt connect to the client anymore.

At first I thought it was my own Windows install but same thing happened in my Windows 10 VM as well...

### How to reproduce

1. Download and Open Quasar 1.4.1
2. Create an client and set its tcp hosts to portmap.io
3. Install the client to the target machine.
4. Look at the server for connection and check if its connected or not(It would be connected)
5. Try force shutting down or crashing the server.
6. Restart the server and look at the server for connection and check if its connected or not(It would NOT be connected)

### Expected behavior

Even after crashes or power losses it should get detected as the client is unaffected.

### Actual behavior

After crashes or power loss, It doesnt connect to the client anymore, UNLESS the client has been rebuilt and reinstalled to the target machine.

**Comment by xuebinboy** [comment]
me too,Has the problem been solved?

**Comment by OskY-Git** [comment]
me too

**Comment by BurntDog** [comment]
I assume you enabled AutoStart and you added client file and location to the Antivirus exclusion list? If not the Antivirus (Windows Defender or third party Antivirus software) will prevent the "client" from running and delete the file.

**Comment by Kabir404** [comment]
> I assume you enabled AutoStart and you added client file and location to the Antivirus exclusion list? If not the Antivirus (Windows Defender or third party Antivirus software) will prevent the "client" from running and delete the file.
> Also make sure the client's install location can be accessed by non Admin users since you are most likely running client in non elevated user mode upon AutoStart .

The problem is with the server IMO, as if it didn't crashed it worked...

**Comment by MaxXor** [comment]
The steps you describe to reproduce the issue and the bug description are different. Is it the client machine which crashes or the server machine with the Quasar UI to control the clients? Also, the client connects to the server. Not the other way around.

**Comment by MaxXor** [comment]
The only change which could hinder the client from starting up between v1.4.0 and v1.4.1 is this: https://github.com/quasar/Quasar/commit/1c7874e7313f79f9b3ff15e87ecbac27fac5297b

It is required to enable the installation of the client for the autostart feature to work correctly.

**Comment by Kabir404** [comment]
> The steps you describe to reproduce the issue and the bug description are different. Is it a crash of the client machine which causes the client to not connect anymore to the server after a reboot? Or is it a crash of the server machine with the Quasar UI to not accept any new clients after reboot? Also, the client connects to the server. Not the other way around.

So basically when I was interacting with the client though the server ui, power went out and after booting my PC and the server back up, it did not connect anymore....then I did some more testing and came to conclusion **that when server unexpectedly shuts down, restarting it makes the client unable to communicate with the server. But if the server was shut down gracefully(without any crashes during a connected session) then restarting the server works as it should.... **

**Comment by Kabir404** [comment]
So my bad for describing incorrectly as I didn't understand properly.


And also AV was disabled on the client as well as the host

**Comment by BurntDog** [comment]
> So my bad for describing incorrectly as I didn't understand properly.
> 
> And also AV was disabled on the client as well as the host

The AV would have been turned back on by default upon reboot killing the client's process then most like deleted the file. Make sure to put the client file in the AV exclusion list to avoid this.

**Comment by Kabir404** [comment]
> > So my bad for describing incorrectly as I didn't understand properly.
> > 
> > And also AV was disabled on the client as well as the host
> 
> The AV would have been turned back on by default upon reboot killing the client's process then most like deleted the file. Make sure to put the client file in the AV exclusion list to avoid this.

Yes it's in the exceptions list but the thing that bugs me out is that even reinstalling the same client doesn't work it has to be a new one...

**Comment by xtremegamer1** [comment]
Do you have a lot connection addresses specified?

**Comment by BurntDog** [comment]
> > > So my bad for describing incorrectly as I didn't understand properly.
> > > And also AV was disabled on the client as well as the host
> > 
> > 
> > The AV would have been turned back on by default upon reboot killing the client's process then most like deleted the file. Make sure to put the client file in the AV exclusion list to avoid this.
> 
> Yes it's in the exceptions list but the thing that bugs me out is that even reinstalling the same client doesn't work it has to be a new one...

I guess you also changed the Mutex to avoid conflicts?

**Comment by AlphaCharry** [comment]
what f？ Can somebody tell me? Can somebody tell me what this bug is?
