### ISSUE TITLE
is this safe?

### ISSUE THREAD

**Issue by bitliandenis** [quasar/Quasar#1156]
hi, im thinking of downloading quasar to control my local computers with ease but for some reason chrome says its a virus. so is it a false postive or not?

**Comment by BurntDog** [comment]
Yes, It's open source so you or a friend can view ALL the coding. It also uses a certificate specific to your client (you make when on first run of the Server prior to building the client which gets embedded into your client) that ensures no one else will hijack your client.

**Comment by bitliandenis** [comment]
thank you, but i’m still having a prinl because whenever i run the app
![IMG_2151](https://user-images.githubusercontent.com/76787654/232392682-04df67ff-04e5-4b30-a517-7533f5e3fd04.png)
 i get an error
