### ISSUE TITLE
How to disable "Remote Desktop" feature in Builder?

### ISSUE THREAD

**Issue by m2acgi** [quasar/Quasar#1159]
### Problem description

How to disable "Remote Desktop" feature in Builder? Thanks.

### Proposal

Disable "Remote Desktop" as default like "keyboard logging" in Builder

**Comment by BurntDog** [comment]
It's disabled by default you must activate it thru the Server. Or edit the code to remove/edit the code to disable it completely.

**Comment by MaxXor** [comment]
It's not possible to disable specific features in the builder and not planned. However you are free to edit the source code as @BurntDog mentioned.
