### ISSUE TITLE
 launch problem

### ISSUE THREAD

**Issue by AnisXneyZ** [quasar/Quasar#1161]
### Quasar version

1.4.1

### Server operating system

Windows 10/Server 2019/2016

### Client operating system

Windows 11/Server 2022

### Build configuration

Debug

### Describe the bug

when I give the executable to someone I do not receive anything how to do? (me too when I run it on me it does nothing)

### How to reproduce

.

### Expected behavior

receive

### Actual behavior

.

### Additional context

.

**Comment by BurntDog** [comment]
First you need to change Build configuration from "Debug" to "Release". Also Add Server/Client to your anti-virus exclusion list or temporarily turn AV off. Also make sure you forwarded your chosen port(s).

**Comment by AnisXneyZ** [comment]
how do you do all this I don't really understand RAT plz

**Comment by MaxXor** [comment]
By reading guides: https://github.com/quasar/Quasar/wiki/Getting-Started
