### ISSUE TITLE
when victim opens it won't show up unless I run it on my computer

### ISSUE THREAD

**Issue by DevBaccon** [quasar/Quasar#1162]
### Quasar version

1.4.1

### Server operating system

Windows 11/Server 2022

### Client installed .NET version

.NET 6.0

### Client operating system

Windows 11/Server 2022

### Build configuration

Debug

### Describe the bug

I'm using a windows 10 vm I send the exe and it doesn't work then I made the exe on the vm and ran it on my pc and it doesn't work. It only worked when I made it on my pc and ran it on the device it was made on same thing with the vm.
Any Help?

### How to reproduce

s

### Expected behavior

s

### Actual behavior

s

### Additional context

s

**Comment by jhoni409** [comment]
Leave me a message on discord jhonig#1547  I will guide you step by step on how to make it work.

**Comment by MaxXor** [comment]
https://github.com/quasar/Quasar/wiki/Getting-Started
