### ISSUE TITLE
virus

### ISSUE THREAD

**Issue by 593172440** [quasar/Quasar#1168]
Is there a problem with the way I opened it? After downloading it, it was directly killed by Huorong

病毒名称：Backdoor/Quasar.f
病毒ID：9877DFC918556493
病毒路径：D:\Soft\Quasar-master\bin\Debug\net452\Quasar.exe
操作类型：修改 
操作结果：已处理

进程ID：7088
操作进程：C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\MSBuild.exe
操作进程命令行："C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\MSBuild.exe" /nologo /nodemode:1 /nodeReuse:true /low:false
父进程：C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.exe

病毒名称：TrojanSpy/PassStealer.ak
病毒ID：DA70380FFE6C48E5
病毒路径：C:\Users\Administrator\Downloads\Quasar.v1.4.1\Quasar v1.4.1\client.bin
操作类型：修改 
操作结果：已处理

进程ID：7240
操作进程：C:\Program Files\WinRAR\WinRAR.exe
操作进程命令行："C:\Program Files\WinRAR\WinRAR.exe" x -iext -ow -ver -- "C:\Users\Administrator\Downloads\Quasar.v1.4.1.zip" C:\Users\Administrator\Downloads\Quasar.v1.4.1\
父进程：C:\Windows\explorer.exe

病毒名称：Backdoor/Quasar.f
病毒ID：9877DFC918556493
病毒路径：C:\Users\Administrator\Downloads\Quasar.v1.4.1\Quasar v1.4.1\Quasar.exe
操作类型：修改 
操作结果：已处理

进程ID：7240
操作进程：C:\Program Files\WinRAR\WinRAR.exe
操作进程命令行："C:\Program Files\WinRAR\WinRAR.exe" x -iext -ow -ver -- "C:\Users\Administrator\Downloads\Quasar.v1.4.1.zip" C:\Users\Administrator\Downloads\Quasar.v1.4.1\
父进程：C:\Windows\explorer.exe

**Comment by ErickDaCoder** [comment]
not a virus

**Comment by BurntDog** [comment]
If you do a search here you will find more in-depth and detailed information on what to do to run without having this issue.
