### ISSUE TITLE
Cant use Quasar

### ISSUE THREAD

**Issue by nosoncookies** [quasar/Quasar#1169]
### Quasar version

1.4.1

### Server operating system

Windows 11/Server 2022

### Client operating system

Windows 11/Server 2022

### Build configuration

Debug

### Describe the bug

After downloading and decompressing the zip i cant setup run or execute anything, theres just a bunch of files that wont run. Help plz

### How to reproduce

Download and decompress the 1.4.1 zip

### Expected behavior

Being able to execute the client

### Actual behavior

Nothing happens

**Comment by BurntDog** [comment]
You need to give much more detail in order to get any help at all. "Can't use" can mean a thousand things. Also please try using our Search function here you'll most like find a helpful answer vs having some repeat something that has been solved. Thank you

**Comment by nosoncookies** [comment]
You are right. I am using Win11, and I have tried both in virtual box and in my pc. I have tried both cloned and downloaded the zip to run the client. Got visual studio and opened it as a file, carpet and project and pressed this green "play" arrow on the top menu, and I am getting these errors: "Unable to start debugging. The startup project could not be launched", or "The debug executable C:Users/Desktop/etc...Quasar.exe specified in the 'Quasar.Server' debug profile does not exist". I have installed the .NET pack 4.5.2 as well. In my pc I have another issue in where it detects a malware and interrupts the process, and i dont know why cant deactivate WinDefender. This error is only popping in my pc tho. Hope This is useful and we can find a solution.

**Comment by MaxXor** [comment]
Sounds like your AV is deleting all executable files. It's a known false positive for quasar. Please add an exception for the files/directories, also on the client PCs!

**Comment by nosoncookies** [comment]
> Sounds like your AV is deleting all executable files. It's a known false positive for quasar. Please add an exception for the files/directories, also on the client PCs!

sorry english is not my 1st language, what does AV mean? And any tips on how I should be adding the exception?

**Comment by BurntDog** [comment]
> > Sounds like your AV is deleting all executable files. It's a known false positive for quasar. Please add an exception for the files/directories, also on the client PCs!
> 
> sorry english is not my 1st language, what does AV mean? And any tips on how I should be adding the exception?

Anti Virus software or Windows Defender

**Comment by nosoncookies** [comment]
> > > Sounds like your AV is deleting all executable files. It's a known false positive for quasar. Please add an exception for the files/directories, also on the client PCs!
> > 
> > 
> > sorry english is not my 1st language, what does AV mean? And any tips on how I should be adding the exception?
> 
> Anti Virus software or Windows Defender

i shouldnt have antivirus in my vm, so what is stopping it? Cant get rid of Windows defender, it is not possible

**Comment by BurntDog** [comment]
Add an exception to antivirus list and temporarily disable Defender.
