### ISSUE TITLE
Anti virus

### ISSUE THREAD

**Issue by SoylentX** [quasar/Quasar#1171]
### Quasar version

1.4.0

### Server installed .NET version

.NET 60

### Server operating system

Windows 11/Server 2022

### Client operating system

Windows 10/Server 2019/2016

### Build configuration

Release

### Describe the bug

Why does it let go off an anti virus? I thought it  didnt show an anti virus

### How to reproduce

?

### Expected behavior

?

### Actual behavior

?

### Additional context

?

**Comment by BurntDog** [comment]
You need to add both client and server to your anti virus? exclusion list.

**Comment by SoylentX** [comment]
Sorry im new to this, and just trying little things out, what do i have to do, so it doesnt get removed on the other person's pc? and its not marked as a virus(if thats possble) Also do I have to download Quasar-master or only v 1.4.1?

**Comment by BurntDog** [comment]
> Sorry im new to this, and just trying little things out, what do i have to do, so it doesnt get removed on the other person's pc? and its not marked as a virus(if thats possble) Also do I have to download Quasar-master or only v 1.4.1?

You need to add both client .exe Machine and server .exe Machine to the anti virus exclusion list.
Quasar-master if you wish to compile the code yourself or
Quasar- v 1.4.1 already compiled (download only from here to avoid issues)
