### ISSUE TITLE
doesnt work with port map

### ISSUE THREAD

**Issue by Keepslus** [quasar/Quasar#1173]
### Quasar version

latest

### Server installed .NET version

6.0

### Server operating system

Windows 10/Server 2019/2016

### Client installed .NET version

6.0

### Client operating system

Windows 10/Server 2019/2016

### Build configuration

Release

### Describe the bug

it doesnt work

### How to reproduce

use without port forwarding, with port map

### Expected behavior

expected it to work

### Actual behavior

doesnt detect connections

**Comment by BurntDog** [comment]
Working just fine.
Did you update to the latest OpenVPN GUI client? https://openvpn.net/community-downloads/
After I updated My OpenVPN GUI and checked to confirm that Port Map did not auto delete my config (which it will do on free accounts when not used for a period of time), All works as it should.

**Comment by Keepslus** [comment]
> Working just fine. Did you update to the latest OpenVPN GUI client? https://openvpn.net/community-downloads/ After I updated My OpenVPN GUI and checked to confirm that Port Map did not auto delete my config (which it will do on free accounts when not used for a period of time), All works as it should.

its up to date, maybe something wrong with my config, can u add me on discord? janokee_never_dies#2535

**Comment by BurntDog** [comment]
> discord

Sorry I don't do Discord or other communications regarding Quasar outside this repository for both safety and security for both myself and the project.

**Comment by Keepslus** [comment]
> > discord
> 
> Sorry I don't do Discord or other communications regarding Quasar outside this repository for both safety and security for both myself and the project.

Oh okay, I set the port in portmap to forward from (forgot) to 788 and in quasar i set everything up and when i ran it, it says in tray not connected, i tried doing it with remcos rat and it timed out, openvpn was on

**Comment by Keepslus** [comment]
I found a solution, i just used ssh instead of openvpn
