### ISSUE TITLE
Open website not working

### ISSUE THREAD

**Issue by Keepslus** [quasar/Quasar#1176]
### Quasar version

latest

### Server installed .NET version

6.0

### Server operating system

Windows 10/Server 2019/2016

### Client installed .NET version

6.0

### Client operating system

Windows 10/Server 2019/2016

### Build configuration

Release

### Describe the bug

When I open the website hidden, I can't find it anywhere (maybe not quasar issue)

### How to reproduce

open website with hidden mode on client pc

### Expected behavior

expected it to show the website on my

### Actual behavior

nothing happens

### Additional context

it might not be a bug mayve just me being stupid

**Comment by MaxXor** [comment]
No, hidden means hidden...... it's basically like sending a request to a webpage. If you are the administrator of the webpage, you can see that the qusar client visited it in your server logs...

Please stop spamming new issues.
