### ISSUE TITLE
how to host it on a Static IP/Domain?

### ISSUE THREAD

**Issue by BBOIII** [quasar/Quasar#1180]
### Quasar version

1.4.0

### Server operating system

Windows 10/Server 2019/2016

### Client operating system

Windows 10/Server 2019/2016

### Build configuration

Release

### Describe the bug

my External Ip address changes from time to time, that is something the ISP does every now and then, which would break the connection between the Host and all the clients and also make them vulnerable for attack.

(( _I'm using this RAT for maintenance purposes only of multiple company devices and servers_ )) 

How do I use a domain instead of my external IP address ?

### How to reproduce

restarting your router might change your external IP address, breaking the connection for good.

### Expected behavior

to be more reliable.

### Actual behavior

un reliable using the external Ip Address

**Comment by MaxXor** [comment]
Either update the DNS name manually each time the Ip changes, let the router handle this for you, use the integrated NoIP-Updater. In the client builder then enter your DNS you want to use.

**Comment by BBOIII** [comment]
> Either update the DNS name manually each time the Ip changes, let the router handle this for you, use the integrated NoIP-Updater. In the client builder then enter your DNS you want to use.

I'm sorry I don't know what are you talking about ?, where is the NoIP-updater?
![image](https://github.com/quasar/Quasar/assets/136642685/37c1020c-ad4b-4954-90f3-aa454d3c673b)

**Comment by BurntDog** [comment]
Please use our search function, many of these questions/concerns have been answered several times (You'll find your answer much quicker). The NoIP-updater is a download from NoIP's website.
