### ISSUE TITLE
Mic and cam

### ISSUE THREAD

**Issue by VladChihaibit** [quasar/Quasar#1181]
### Problem description

can you add mic and cam?

### Proposal

.

### Additional context

.

**Comment by ErickDaCoder** [comment]
they were removed.
"Sorry accessing the desktop and the whole computer is powerful enough for a remote ADMINISTRATION tool. No need to directly spy on the user." - MaxXor
#1117
#1011
no point in having an issues tab if none of the issues are actually useful.

**Comment by MaxXor** [comment]
* they were never added in the first place :)
