### ISSUE TITLE
remote desktop screen is partly shown

### ISSUE THREAD

**Issue by Subjoel** [quasar/Quasar#1182]
### Quasar version

1.4.1

### Server installed .NET version

.Net 6.0

### Server operating system

Windows 11/Server 2022

### Client installed .NET version

.Net 6.0

### Client operating system

Windows 10/Server 2019/2016

### Build configuration

Release

### Describe the bug

so, whenever i test it and use remote desktop feauture i get to see their screen but only the top right part of it. i think its with the aspect ratio or resolution but idk. see this image for details.
![image](https://github.com/quasar/Quasar/assets/89309881/cd9d87b4-dc4f-4d1f-a31a-b219791b5437)

### How to reproduce

i just downloaded quasar 1.4.1 from release and ran quasar.exe and build the client. after that i ran the client on multiple different rdp's to test.

### Expected behavior

see the full screen with taskbar and just their screen.

### Actual behavior

it shows zoomed in screen or something.

### Additional context

/

**Comment by BurntDog** [comment]
Never had this happen myself but, just to check did you ever try to change your Desktop resolution to see if that made any difference (what is your Desktop resolution set to now)?

**Comment by Subjoel** [comment]
Fixed, all my rdp's i used where kinda squared shape, that's why, on normal monitors it works
