### ISSUE TITLE
add being able to access microphone 

### ISSUE THREAD

**Issue by Nuclearpotato69** [quasar/Quasar#1183]
### Problem description

it would be nice to access this

### Proposal

i want to be able to record and hear whats happening thru the mic

**Comment by BurntDog** [comment]
Please do a search here to see this answered and why it would not be added and there are no plans on doing so, unless you yourself added that function. If you did a search you may find OLD information on doing so. It's a open source project so feel free to customize it for your own "Legal" usage. 

Listening to private conversations with out the written consent of the person(s) involved is illegal in most states and providences no matter where you live.
