### ISSUE TITLE
Client error, This app can't run on your PC 

### ISSUE THREAD

**Issue by sayrats** [quasar/Quasar#1186]
### Quasar version

1.4.1

### Server operating system

Windows 11/Server 2022

### Client operating system

Windows 11/Server 2022

### Build configuration

Debug

### Describe the bug

When I try to run the client I get the "This app can't run on your PC", I have added permission for the file disabled all the windows protection and still can't run it.
Is there anything I could have missed?
I also tried to run the file directly from the cmd in admin mod, get access denied message error.

### How to reproduce

Try to run the client.exe in a new windows 11 installation that has all windows protection disabled and permission for the client.exe file

### Expected behavior

client.exe to run

### Actual behavior

This app can't run on your PC

**Comment by sayrats** [comment]
It works when using version 1.3.0

**Comment by BurntDog** [comment]
First make sure you have the correct .NET version installed.

**Comment by MaxXor** [comment]
Quasar running on Windows 11 Pro server + client: ![image](https://github.com/quasar/Quasar/assets/7271470/ecb0be34-1e07-4cd6-9847-435d035d9f93)

.NET Framework 4.8 is pre-installed with Windows 11, so it's working fine without any modifications. However you need to add an exception to your AV and/or temporarily disable Microsoft SmartScreen to allow it to run.
