### ISSUE TITLE
any help with my windows reset?

### ISSUE THREAD

**Issue by ILoveFreaks** [quasar/Quasar#1187]
hi so ive ran the client multiple times on my own pc and sometimes this happens
![image](https://github.com/quasar/Quasar/assets/138148827/468e69cb-4374-4b7e-992b-9d2d79a4d84b)
and then when I try to reset my pc I get this
![image](https://github.com/quasar/Quasar/assets/138148827/9e419262-d9ce-4375-9e1e-4073993a01e9)
ive tried all the methods on resseting my pc even looking at old cmd commands no luck tho ive checked my subdir where it can be located but nothing is there in my testing every time I was done I uninstalled it from the user interface

**Comment by MaxXor** [comment]
Hello, this seems like a larger problem with your Windows installation - unrelated to Quasar. I'm sorry but this is a bug-tracker for Quasar-related issues. I'd recommend you do a fresh install of Windows.

**Comment by BurntDog** [comment]
Doing a Hard reboot (Complete proper Shutdown as oppose to using Restart) would clear that out. It can happen when resources are low such as Memory. Just reboot after you removed the Client.
