### ISSUE TITLE
how fix it 

### ISSUE THREAD

**Issue by Sir4004** [quasar/Quasar#1188]
### Quasar version

1.4.1

### Server operating system

Windows 11/Server 2022

### Client operating system

Windows 11/Server 2022

### Build configuration

Debug

### Describe the bug

![Screenshot 2023-07-03 155515](https://github.com/quasar/Quasar/assets/94808279/a0d456b7-fcc3-4363-b4ba-3cd5d988e5e9)

### How to reproduce

![Screenshot 2023-07-03 160130](https://github.com/quasar/Quasar/assets/94808279/6b39d5ff-96b6-4505-9f70-adc911c1c304)

### Expected behavior

![image](https://github.com/quasar/Quasar/assets/94808279/bb1c7a22-f458-4828-a146-89249f411640)

### Actual behavior

![image](https://github.com/quasar/Quasar/assets/94808279/acad2474-ae5c-4f11-940d-ae97e60e732a)

### Additional context

![image](https://github.com/quasar/Quasar/assets/94808279/7f34ba0b-bccc-41f7-b3d6-687ce0ef6967)

**Comment by MaxXor** [comment]
The field `_typeIndex` is not used anymore. It's not a bug, just a warning.
