### ISSUE TITLE
[BUG]A black screen is displayed when a user locks the screen or enters the screen lock password screen

### ISSUE THREAD

**Issue by AlphaCharry** [quasar/Quasar#1191]
### Quasar version

1.4.0

### Server operating system

Windows 10/Server 2019/2016

### Client installed .NET version

.NET 4.5.2

### Client operating system

Windows 10/Server 2019/2016

### Build configuration

Release

### Describe the bug

A black screen is displayed when a user locks the screen or enters the screen lock password screen

### How to reproduce

A black screen is displayed when a user locks the screen or enters the screen lock password screen

### Expected behavior

A black screen is displayed when a user locks the screen or enters the screen lock password screen

### Actual behavior

A black screen is displayed when a user locks the screen or enters the screen lock password screen

**Comment by MaxXor** [comment]
If you don't provide the steps to reproduce this is not helpful. How does Quasar have anything to do with black screens when the user locks the PC?
