### ISSUE TITLE
[BUG]When the remote client locks the system or enters the password input screen, the remote control screen displays black

### ISSUE THREAD

**Issue by AlphaCharry** [quasar/Quasar#1192]
### Quasar version

1.4.0

### Server installed .NET version

.NET 4.5.2

### Server operating system

Windows 10/Server 2019/2016

### Client installed .NET version

.NET 4.5.2

### Client operating system

Windows 10/Server 2019/2016

### Build configuration

Release

### Describe the bug

![48c450eaf14fd7d35d159730f03dce8](https://github.com/quasar/Quasar/assets/38164385/88759e7a-c291-4fd3-b401-9275e7496de5)
**When the remote host is in the state of user input password, or the system such as WindowsServer 2019 is in the lock state, it cannot display the remote desktop properly！！！**However, you must manually enter the password on the remote host to enter the desktop

### How to reproduce

1. You can use WindowsServer 2008 2019 2022. After RDP leaves, you cannot enter it again, and the remote desktop displays a black background
3. Common Windows11 When you enter the startup password in Windows10, the remote desktop cannot be displayed normally and turns black

### Expected behavior

Should display normally but cant

### Actual behavior

The remote desktop is all black

**Comment by MaxXor** [comment]
Now I understand, thank you. Unfortunately it's a known issue and not fixed yet:

**Comment by MaxXor** [comment]
https://github.com/quasar/Quasar/issues/733

**Comment by AlphaCharry** [comment]
> #733

UAC？

**Comment by MaxXor** [comment]
User Access Control

**Comment by MaxXor** [comment]
-----> https://github.com/quasar/Quasar/issues/733
