### ISSUE TITLE
Quasar Didn't worked on Client Site

### ISSUE THREAD

**Issue by TvojeMamaSmrdiJakNoha** [quasar/Quasar#1193]
Hey, When I open Client-Build.exe on the Client computer, it doesn't show up in Quasar. I think I don't have open ports needed for Quasar TCP or UDP (I don't know about that so take it with a grain of salt) Well, simply when I open Client-Build on a computer other than mine it doesn't show as Connected Client

**Comment by MaxXor** [comment]
https://github.com/quasar/Quasar/wiki/Getting-Started

**Comment by TvojeMamaSmrdiJakNoha** [comment]
But how do i know what port i have
