### ISSUE TITLE
MaxXor, please do not close this ticket. It still didn't worked.

### ISSUE THREAD

**Issue by TvojeMamaSmrdiJakNoha** [quasar/Quasar#1194]
Yesterday you closed my ticket, i tried what it said but nothing happend:) So please do not close this ticket. 

Tried DNS configuration - Google
Tried Ip Forwarding - Nothing Happend
Tried Both my Ip Adresses - Nothing Happend

**Comment by BurntDog** [comment]
Are you using our search function? You'll most likely find a answer that helps.
