### ISSUE TITLE
Installing / Setting up

### ISSUE THREAD

**Issue by Nitrozena** [quasar/Quasar#1196]
### Problem description

Hey im new to this and when i build it and run it on my network everything works fine but when someone else downloads and runs it on their network i dont get their connection.

### Proposal

Can someone please tell me step by step how to set this thing correctly up pelase?

**Comment by MaxXor** [comment]
https://github.com/quasar/Quasar/wiki/Getting-Started

**Comment by Nitrozena** [comment]
> https://github.com/quasar/Quasar/wiki/Getting-Started

thanks but i already have followed the instruction and just tested it with my friend i have firewall and stuff allowed on all ports and he opened it as admin and normal too and it didnt show up to me
