### ISSUE TITLE
"Quasar Client" shows in processes tab

### ISSUE THREAD

**Issue by fizzylemon87** [quasar/Quasar#1201]
Works like a charm, just one quick thing I've noticed.

After launching the built agent on my second target pc, having a remote connection and everything setup I was checking some things and noticed "Quasar Client" with a default executable logo was showing in the "Processes" tab under "Background Processes" in Task Manager on the target pc. Right Click > Go To Details > "FAKE_NAME_I_PUT_INTO_BUILDER".EXE  <-- this is okay!

I thought I might have done something wrong but since I didn't type any terms like "Quasar" into the builder, I guess it should not be visible in Task Manager except for some other issue. Maybe make it able to inject into Windows process or a clone.

**Comment by MaxXor** [comment]
If you don't change any [assembly information](https://github.com/quasar/Quasar/wiki/Client-deployment-settings#assembly-settings) it will show up normally.
