### ISSUE TITLE
Connection Problems

### ISSUE THREAD

**Issue by yesitshazza** [quasar/Quasar#1203]
Hi! so I am having problems getting a connection to the client from my pc, the client is of course my other pc and my host pc. It may also be useful to know I am using PortMap/OpenVPN for the port stuff, anyway When the I run the .exe on both of my pc's/laptop it opens and just simply doesnt get a connection for either computers.

**Comment by MaxXor** [comment]
Sorry, this is not a place for port forwarding problems.
