### ISSUE TITLE
Cannot download a folder from remote client

### ISSUE THREAD

**Issue by heroes1412** [quasar/Quasar#1208]
### Quasar version

1.4.1

### Server installed .NET version

.NET 4.8

### Server operating system

Windows 10/Server 2019/2016

### Client installed .NET version

.NET 4.8

### Client operating system

Windows 11/Server 2022

### Build configuration

Release

### Describe the bug

  Quasar just can download single file. it cannot download a folder

### How to reproduce

click a folder within multiple file, select download. nothing appears.

### Expected behavior

download full folder and its content

### Actual behavior

nothing

**Comment by MaxXor** [comment]
Downloading directory contents is not yet supported, please see here: https://github.com/quasar/Quasar/issues/1208

A work-around *for now* is to download all files of the directory manually.
