### ISSUE TITLE
i cant find the EXE. i have looked on the github in all available files and in my pcs cloned ones, even with file explorer search i cant find it

### ISSUE THREAD

**Issue by VrBeatSaber** [quasar/Quasar#1213]
### Quasar version

1.4.1

### Server operating system

Windows 11/Server 2022

### Client operating system

Windows 11/Server 2022

### Build configuration

Release

### Describe the bug

even using the explorer's search bar i cant find the exe. i also cant find it in the files that are on github

### How to reproduce

reproduce??? idk what that means

### Expected behavior

hopefully to get to run it

### Actual behavior

i cant find the exe

**Comment by MaxXor** [comment]
On this page: https://github.com/quasar/Quasar/releases/tag/v1.4.1 -> Assets -> Quasar.v1.4.1.zip
