### ISSUE TITLE
Quasar.Server.Controls.AeroListView

### ISSUE THREAD

**Issue by BundeskriminalamtInv0lved** [quasar/Quasar#1225]
### Quasar version

Newest

### Server installed .NET version

.NET 6.0 

### Server operating system

Windows 10/Server 2019/2016

### Client operating system

Windows 10/Server 2019/2016

### Build configuration

Release

### Describe the bug

Quasar.Server.Controls.AeroListView When trying to Modify it comes in almost any other form i know its a Stupid question

### How to reproduce

Open The Repository

### Expected behavior

Errors at Forms

### Actual behavior

Errors a lot of them Lmao

**Comment by MaxXor** [comment]
You have to modify it by right-clicking the file in VS and choosing "View Code".

**Comment by BundeskriminalamtInv0lved** [comment]
> You have to modify it by right-clicking the file in VS and choosing "View Code".

And the designer lmao?
