### ISSUE TITLE
Next Release Goals

### ISSUE THREAD

**Issue by yankejustin** [quasar/Quasar#244]
<h1>Possible Goals for the next release</h1>
- Multi-Language support
- Add ability to install Client as Windows Service
- Control re-designs and other large visual improvements (likely to move to WPF)
- Usability improvements / ease of use changes
- Search in Keylogger Logs
- Add Registry Editor (assigned to @yankejustin)
- Improve File Manager (#262)
- Add ability to group clients
- Fix Keylogger missing some key combinations (#243)
- Add more ways to obtain GeoIP information (#248)

**Comment by MaxXor** [comment]
I'll improve the implementation of `OnClientFail` in RELEASE4 already! Good job on this list. :+1:
We'll use this first post to update the list, so newest information is always at the top of this issue.

**Comment by tidusjar** [comment]
Is this in priority order?

**Comment by MaxXor** [comment]
@tidusjar No special order.

**Comment by tidusjar** [comment]
OK cool, mind If I give a go attempting something? I'd like to start contributing more to this project.

**Comment by MaxXor** [comment]
@tidusjar Sure, any help is appreciated.

**Comment by yankejustin** [comment]
@tidusjar Work on what interests you. These are not in order as stated, but know it is not the <b>only<\b> things that can be added. :)

**Comment by yankejustin** [comment]
Just going to put this near the top. :)

**Comment by tidusjar** [comment]
I know MaxXor is not a fan of using 3rd party libs but for running the client as a Windows service we may want to look at [Topshelf](http://topshelf-project.com/)

**Comment by yankejustin** [comment]
This should be good: http://www.c-sharpcorner.com/UploadFile/sachin.nigam/InstallingWinServiceProgrammatically11262005061332AM/InstallingWinServiceProgrammatically.aspx

**Comment by yankejustin** [comment]
As an additional note on the link I provided above, please read the comment section of the article to avoid little issues that may result from ServiceController. :hankey:

**Comment by bitterypaul** [comment]
what is keylogger hotkeys

**Comment by MaxXor** [comment]
@bitterypaul it's basically this issue: https://github.com/MaxXor/xRAT/issues/243

**Comment by SandPox** [comment]
-Add ability to install Client as Windows Service

you'll lost your ability to remote desktop because QuasarRAT process will run at SYSTEM user but SYSTEM are non-real account then the screen you capture just fully black

**Comment by MaxXor** [comment]
I think I'm going to release the first version of Quasar before everything here is done. Just to complete the name change and provide everyone with a new stable version.

**Comment by tidusjar** [comment]
What's Quasar?

**Comment by MaxXor** [comment]
@tidusjar xRAT is now Quasar, if you didn't notice yet.^^
And for Quasar: "An extremely distant, and thus old, celestial object whose power output is several thousand times that of our entire galaxy."

**Comment by tidusjar** [comment]
Ah! Yes I didn't notice!

**Comment by yankejustin** [comment]
Perhaps we could add a few languages after the update to the GUI. That would be a nice addition for the next major release.
MaxXor, I am assuming you also speak German. :)

**Comment by MaxXor** [comment]
@yankejustin Multi-Language support would be nice, indeed.

**Comment by rabbitsmith** [comment]
What happened to the plugin system? That was another of the best enhancements ever suggested.

**Comment by werkamsus** [comment]
@rabbitsmith It is very difficult to implement since it requires an almost complete restructuring of the client. MaxXor himself said that would be more realistic as a release goal of Quasar 2.

**Comment by rabbitsmith** [comment]
What is the estimated release date of quasar2

**Comment by MaxXor** [comment]
Not this year. :(

**Comment by yankejustin** [comment]
<a href="https://github.com/quasar/QuasarRAT/issues/419">Potentially useful link to make a client a Windows Service.</a>

**Comment by GodsVictory** [comment]
I have successfully created a windows service by modifying the startup.cs file by replace the current schtasks command with the following:

```
ProcessStartInfo startInfo = new ProcessStartInfo("sc")
{
    Arguments = "create \"" + Settings.STARTUPKEY + "\" start=auto binpath= \"" + ClientData.CurrentPath + "\"",
    UseShellExecute = false,
    CreateNoWindow = true
};

Process p = Process.Start(startInfo);
p.WaitForExit(1000);
if (p.ExitCode == 0) return true;
```
