### ISSUE TITLE
Sort numbers (and files size)

### ISSUE THREAD

**Issue by dz-z3r0** [quasar/Quasar#618]
I see that all sorting fields are using alphabetically sort so no results are correct.
And the second thing is sorting files size
<img width="571" alt="File Manager
" src="https://user-images.githubusercontent.com/30845020/29093521-fefa453e-7c81-11e7-91c5-34414628255f.png">
<img width="325" alt="untitled2323" src="https://user-images.githubusercontent.com/30845020/29093615-514995e2-7c82-11e7-99b1-59a110256b0e.png">

**Comment by ValonK** [comment]
This would be a quick fix, if I get time later I could write it.
