### ISSUE TITLE
ADD:Mic&Speaker Access

### ISSUE THREAD

**Issue by sunnybhasin** [quasar/Quasar#718]
Hey can anybody Please add Remote Mic & Speaker Access

**Comment by ggregor** [comment]
Is there a more recent version that has Microphone integrated, because this pull is very old?

**Comment by Thorsir** [comment]
I am also searching for a version microphone  included. Where can I find one?
Thank you.

**Comment by sunnybhasin** [comment]
Not found one, if you get it please let me know..

**Comment by ValonK** [comment]
hej guys, I Implemented the Microphone feature and removed the code...since many of you are asking i will upload it and post the link here ....

**Comment by sunnybhasin** [comment]
If you can please add mic and speaker access both..

**Comment by ValonK** [comment]
Here is the link to the Project: **https://www29.zippyshare.com/v/wPvW0beU/file.html** . Don't ask me for any kind of Support, I wrote this code a long time ago.... if you find bugs fix it yourself.

**Comment by Thorsir** [comment]
thank you.

was the version a kind of stable?

**Comment by yankejustin** [comment]
If I remember correctly, it was. Quasar has made a lot of improvements since then so i'd recommend pulling the changes from ValonK's implementation and just plopping them into Quasar's current source.
Pretty copy and paste.

**Comment by Thorsir** [comment]
sorry..I have no clue how ro do that.....could you quickly do that copy and
paste and post the latest version including microphone?
That would be great..Thank you so much...
