### ISSUE TITLE
UAC Causes Remote Desktop to freeze

### ISSUE THREAD

**Issue by pixel375** [quasar/Quasar#754]
Not sure if it's happening just for me.. but when I'm in a clients Remote Desktop, and I open any program that open up the UAC window, my remote desktop session freezes until the UAC times out or gets exited from the other side. 

What would be causing that? And how could I get around this issue?

Btw, I'm using the latest stable built V1.3.0.0
https://github.com/quasar/QuasarRAT/releases/tag/v1.3.0.0

**Comment by MaxXor** [comment]
I think it's the same issue as https://github.com/quasar/QuasarRAT/issues/733. Didn't had time to look into it yet.

**Comment by H4xl0r** [comment]
Normal behavior, when UAC is running , the screen capture is not able to interact.
Its everywhere the same. 

No workaround ....(safety feature , or you could trigger uac and klick yes via remote) !

**Comment by Tylerkiller2345** [comment]
How does team viewer get around this?

**Comment by H4xl0r** [comment]
they have a software cert as a company .... and that can bypass many things !

**Comment by MaxXor** [comment]
Closing this in favor of https://github.com/quasar/Quasar/issues/733.
