### ISSUE TITLE
Import own .p12

### ISSUE THREAD

**Issue by H4xl0r** [quasar/Quasar#757]
Would be nice to import own .p12 certs.

It would work , but he prompts with some PW wrong errors.
(generating randoms at moment)

So when importing , asking for PW.... Or print out PW when generating one. 
Help would be nice thanks

**Comment by ndragon798** [comment]
Fixed in pull request #786

**Comment by H4xl0r** [comment]
good job !

**Comment by MaxXor** [comment]
If you have the permissions restrictive enough on the private key (e.g. only letting Quasar user read it) this would probably be good enough. Quasar will have to keep the private key loaded in memory anyway; this might be harder for an attacker to recover, but if they have root access to the box you should consider the key compromised regardless.

I'd recommend locking down permissions on the certificate file and not having a password on it.
