### ISSUE TITLE
How can I add my package (feature)?

### ISSUE THREAD

**Issue by AleGor1902** [quasar/Quasar#775]
I need add my feature to Quasar rat. How can i do this?

**Comment by yankejustin** [comment]
Clone the code to your machine, make the modifications, then build the code. Make sure to build the client project so the binary can be used by the server. :)

**Comment by AleGor1902** [comment]
If i add packets, then not added clients. P.S i built client.
Where do i need to add packages, to register them? If you are not difficult to describe the instructions on how to add their functions in Quasar RAT...
