### ISSUE TITLE
Help with customization

### ISSUE THREAD

**Issue by BowenGIT** [quasar/Quasar#812]
My dad is using this software to spy on my laptop.
I obviously cant let that happen, so im planning on changing displaying a message box every time Quasar.exe is opened.
I will do this using the quasar remote task manager, as I have also RATed his computer :)
Even though Im only in middle school, I do have considerable programming experience, and Im pretty confident I can get the message box to work.
After changing the code, how would I re-build (you know what I mean) Quasar so I get the modified and parent proof

Also, can I change the icon to visual studio code or file explorer or something?

**Comment by Finguimbrine** [comment]
lmfao

**Comment by ReactorCore17** [comment]
You can use ResourceHacker to change the icon. I'm not sure about any of the other programming things, but you could use WinRAR to set a password for the Quasar.exe file which would be much simpler.

**Comment by dogo99** [comment]
> My dad is using this software to spy on my laptop.
> I obviously cant let that happen, so im planning on changing displaying a message box every time Quasar.exe is opened.
> I will do this using the quasar remote task manager, as I have also RATed his computer :)
> Even though Im only in middle school, I do have considerable programming experience, and Im pretty confident I can get the message box to work.
> After changing the code, how would I re-build (you know what I mean) Quasar so I get the modified and parent proof
> 
> Also, can I change the icon to visual studio code or file explorer or something?

<<<VISUAL STUDIO not VISUAL STUDIO CODE>>>

its really simple to edit UI things and stuff, just make sure you have advanced knowledge.

you must use visual studio, and uhh what the fuck do your parents do like... if you want help I can try to help send you a version that makes a fake remote desktop and message box display etc or requires you to click yes on a popup if you want the remote desktop / keylog to happen when he wants keylogs and stuff. if you have a discord dm me on there.

**Comment by BowenGIT** [comment]
@dogo99 Thanks for the offer, but my dad has already found my rat, and threatened some pretty horrible things if i do it again. Hes a software security guy, so this is prob going nowhere. I've found a solution, though! Get rid of windows and use ubuntu instead! Yay!

**Comment by dogo99** [comment]
> @dogo99 Thanks for the offer, but my dad has already found my rat, and threatened some pretty horrible things if i do it again. Hes a software security guy, so this is prob going nowhere. I've found a solution, though! Get rid of windows and use ubuntu instead! Yay!
next time you try to do things like these, don't try using a commercial rat made for bussiness owners lol.
