### ISSUE TITLE
Host won't appear in Quasar

### ISSUE THREAD

**Issue by coconutbutt11** [quasar/Quasar#818]
**Describe the bug**
I have successfully port forwarded and canyouseeme.com agrees.

**Expected behavior**
They click, it shows up in my Quasar.

**What actually happens**
They click, nothing happens.

**System**
 - Server OS: Win 10
 - Client OS: Win 10
 - Server installed .NET Framework version:no clue
- Client installed .NET Framework version: no clue
 - Quasar Version: newest
 - Build configuration: release

**Comment by ReactorCore17** [comment]
Make sure in settings you are listening on the correct port and you selected the correct hostname.

**Comment by harr092** [comment]
Hello can you please show me how I will bypass the windows defender??

**Comment by harr092** [comment]
Which file contains this Backdoor:Msil/quasar.GG!MTB

**Comment by harr092** [comment]
Hello

**Comment by harr092** [comment]
How do I make the rat not vulnerable to windows defender even when it on ???

**Comment by BurntDog** [comment]
> How do I make the rat not vulnerable to windows defender even when it on ??? >

Simply add it (both Server and Client exes) to Defender and or third part Anti Virus exclusion list.

**Comment by harr092** [comment]
Thanks for the tip!

**Comment by harr092** [comment]
What about not adding to exclusion but still bypassing the defender ????

What file does the defender scans??

**Comment by BurntDog** [comment]
> What about not adding to exclusion but still bypassing the defender ???? What file does the defender scans?? > >

It's a false positive set off by the functions the Tool has. You could try eliminating functions you have no use for (ie. password recovery ect.) one by one. But, if you don't know what you're doing you can break the client/server. We don't not discuss or give tips on how to evade anti virus as this is a legit admin tool and not meant on any level to be used without the knowledge and permission of all parties involved.

**Comment by harr092** [comment]
Onay thanks 🙏

**Comment by harr092** [comment]
What about taking down the executions ??
