### ISSUE TITLE
Port is Listening but no connections are popping up.

### ISSUE THREAD

**Issue by Tokka3** [quasar/Quasar#821]
Here is what I have done.
1. Went to my Gateway and opened a new port..
![image](https://user-images.githubusercontent.com/8098185/83869177-c1e50e80-a75e-11ea-8839-d1f38d0822f6.png)
The bottom one is the one I'm using for the RAT. External host is my public IP, Internal Host is my IPV4..
2.  I went to canyouseeme.org to check if the port was open (It wasn't.. Good sign because I didn't listen to it yet)
3. I went on quasar rat, started listening to the port 7361.
4. Went on canyouseeme.org to check if it was listening and it was. So the rat was working from now..
5. Built a stub, put my public IP as the host name, put the port as the port.. 
6. Opened it, didn't work.
Any issues of what's wrong?? The port is definitely working :/

**Comment by MaxXor** [comment]
Can you confirm that you entered the correct public IP address by going to this site: https://tools.keycdn.com/geo (it will be shown in the textbox)? Try to connect with `ncat` or similar tools to the public IP and port to confirm this.

**Comment by dogo99** [comment]
not local ip, correct ports on both things, correct password, user / client has application whitelisted / defender bypassed etc. make sure all those happen.
