### ISSUE TITLE
Opening a remote shell from file manager on a secondary drive fails

### ISSUE THREAD

**Issue by danteblades** [quasar/Quasar#822]
If you go to a secondary drive on a client (D drive in my example) and you right click to open a remote shell, it will try to cd to the directory but it fails and leaves you still at the root of the C drive. This seems to be an issue on 1.3.0.0 as well as the newest release 1.4.0

Since I switched to 1.4.0 remote desktop frame rates are about half of what they used to be on previous version. 

![Screenshot_1](https://user-images.githubusercontent.com/46517869/83939857-1663aa80-a7ae-11ea-83d3-13c82aca4203.png)

**Comment by MaxXor** [comment]
Thanks for the report, I can confirm that opening a remote shell on a secondary drive from the file manager doesn't work. It should be changed by `d:` first and then `cd D:\Documents`. However I can't reproduce the worse frame rate in the latest version.

**Comment by danteblades** [comment]
Even if you do cd d: it still fails to switch drives

Could it be a video card or driver issue? I do not have a great video card

**Comment by MaxXor** [comment]
Only type `d:` without `cd`. Currently the remote desktop frame rate is capped by the Windows Forms renderer which is slow and runs on the CPU only. In the future Quasar will change the GUI interface to a more modern one that supports GPU-acceleration. This will allow 30+ FPS RDP sessions.

**Comment by danteblades** [comment]
Gotcha! Hopefully that bug gets sorted in an update. I'm glad to see you still support this project. It is really fantastic

**Comment by MaxXor** [comment]
Thanks, yes after a long period of silence I'll continue with it now.
