### ISSUE TITLE
Firefox & Chrome Passwords not recovered

### ISSUE THREAD

**Issue by azsde** [quasar/Quasar#827]
Issue on Quasar 1.4.0.

I have a virtual machine with the latest version of windows 10 running.
Latest versions of Firefox & Chrome are installed.
Passwords are saved in both Firefox and Chrome.

When I go into password recovery, it remains empty, no matter how many times I press refresh.

**Expected behavior**
Passwords should have been retrieved.

**Screenshots**

**System**
 - Server OS: Windows 10
 - Client OS: Windows 10
 - Server installed .NET Framework version: 4.8.03752
 - Client installed .NET Framework version: 4.8.04084
 - Quasar Version: 1.4.0
 - Build configuration: Release

![broken](https://user-images.githubusercontent.com/6370231/84052553-07007f00-a9b1-11ea-9b54-6486ce702546.PNG)

**Comment by MaxXor** [comment]
Have you set a master password in Firefox or Chrome? If so, this explains why.

**Comment by azsde** [comment]
Hello MaxXor,

No, I haven't set master password.

I can provide you a teamviewer access to my VirtualMachine if you want to do some testing.

**Comment by MaxXor** [comment]
Did you install Windows 64bit? AFAIK only the 64 bit versions of the browsers are supported then. Please make sure you have Firefox and Chrome 64 bit installed.

**Comment by azsde** [comment]
Yes, this is Windows 10 Pro 64 Bits, build 2004.

Firefox was installed automatically in the default 64 bit program location (Program Files), Chrome did install in Program Files x86, but it seems to be a normal usecase as it is the same folder for all my computers running Windows 10 64 bit.

**Comment by MaxXor** [comment]
Okay, thanks for confirming. I'll check it out and report back.

**Comment by MaxXor** [comment]
There seems to be a problem with Chrome version 80+. [The password storage has changed a bit](https://stackoverflow.com/questions/60230456/dpapi-fails-with-cryptographicexception-when-trying-to-decrypt-chrome-cookies). I've pushed some changes to a [password-recovery](https://github.com/quasar/Quasar/tree/password-recovery) branch. You can download the [latest CI build](https://ci.appveyor.com/project/MaxXor/quasar/builds/33394394) or compile from source.

However this requires BouncyCastle crypto library on the client. I'm not entirely sure if it would be better to decrypt the passwords on the server side to prevent this huge new dependency on the clients.

For Firefox I need some further information as I cant reproduce the problem, do you store the profile locations in a different path than `%APPDATA%\Mozilla\Firefox\Profiles`?

**Comment by azsde** [comment]
No I didn't change a thing, they are stored at their default path.

**Comment by MaxXor** [comment]
If this is a fresh installation and no sensitive information is contained, would you send me the profile contents from `%APPDATA%\Mozilla\Firefox\Profiles` as a zip file?

**Comment by azsde** [comment]
There you go:

[Profiles.zip](https://github.com/quasar/Quasar/files/4750759/Profiles.zip)

**Comment by MaxXor** [comment]
Your profile directory is perfectly fine and I can retrieve the account on Windows 10 64bit. The only reason I can think of it doesn't work for you is that Firefox was either installed in a non-default location or it is the 32 bit version on a 64 bit OS, very strange...

Btw. thanks to your profile I discovered a small bug when handling multiple profiles in Firefox.

**Comment by azsde** [comment]
Do you want a teamviewer access to the VM ?

**Comment by MaxXor** [comment]
Do you have Visual Studio installed? That would be very helpful. Please mail me the teamviewer credentials to `admin at maxxor d0t org`.

I will connect in ~1 hour. I hope the credentials are valid for that time, or just send me them in one hour.

**Comment by azsde** [comment]
I have visual studio installed on my non-VM machine, do you want me to install it into the VM ?

**Comment by MaxXor** [comment]
Yes, that would be great.

**Comment by speedboy17** [comment]
Can you fix this like Asyncrat has? they can collect from every browser right now you cant get all passwords. I only get ftp pass.
