### ISSUE TITLE
Reducing "Remote Desktop" Window cause client to briefly disconnect

### ISSUE THREAD

**Issue by azsde** [quasar/Quasar#830]
When viewing a client's remote desktop, reducing the window (by pressing the "-" button), cause the client to disconnect. 

1. Go to a connected client "Remote Desktop"
2. Click on 'Start'
3. Click on minimize button "-"
4. Client is disconnected

**Expected behavior**

The remote desktop should keep going when the window is minized and the client should not be disconnected.

Server OS: Windows 10
Client OS: Windows 10
Server installed .NET Framework version: 4.8.03752
Client installed .NET Framework version: 4.8.04084
Quasar Version: 1.4.0

Build configuration: master

**Comment by dogo99** [comment]
I'm sorry I had to do something today but I'll make sure to respond in a couple hours or if I go to sleep when I wake up, sorry but it's 3 am right now.

**Comment by dogo99** [comment]
I need some info first to recreate the issue perfectly

What version of windows are you using? (May be a new update bugging stuff out)

What Quasar Server and Client version are you using? (Maybe you are using an old version?)

Does this happen rarely or a lot?

Are you using open source builds or release builds?

**Comment by azsde** [comment]
I already provided those informations in the original post, I build Quasar myself based on the latest master commit.

**Comment by dogo99** [comment]
I know that is why I deleted the comment, I forgot that you need to specify those.

But anyways, here's what I found:

I'm looking into it and I noticed quasar closes the connection when the async receiver gets an error.
Could maybe happen due to the client sending incorrect data that causes an error to happen, Still looking into it

**Comment by dogo99** [comment]
Update: 

My 3 main reasons for it happening are

Client sending incorrect data that can't be parsed so server drops connection
Server sending unsafe data that drops the connection
The amount of data sent is over the 5 megabyte limit MaxXor put in place.

**Comment by MaxXor** [comment]
@dogo99 It was much simpler, the local window size was set to (0,0) when minimized.

@azsde Thanks for the report. It's fixed in https://github.com/quasar/Quasar/commit/4c4cde446d1d39d917bf2459916c3aacf89579fd
