### ISSUE TITLE
When Quaser server runs on Windows Server 2012 R2 it is not able to accept connections from clients

### ISSUE THREAD

**Issue by haxpak** [quasar/Quasar#832]
**Describe the bug**
Unable to run server on Windows Server 2012 R2

**System**
 - Server OS: Windows Server 2012 R2
 - Client OS: Windows Server 2012 R2 / Windows 10 1803
 - Server installed .NET Framework version: v4.8
 - Client installed .NET Framework version: v4.8
 - Quasar Version: 4c4cde446d1d39d917bf2459916c3aacf89579fd
 - Build configuration: Both Debug and Release Tested

**Comment by MaxXor** [comment]
Hello, can you confirm that connections on the same server work with `localhost`? Next, please check with `ncat` or similar, if the TCP port is accessible from outside? If the clients connect via another network, port forwarding (NAT) must be set up on the router.

Also check out the guide "Getting started": https://github.com/quasar/Quasar/wiki/Getting-Started

**Comment by haxpak** [comment]
Hi,
Thanks for the prompt response @MaxXor 

I have been using quasar for some time now in my engagements.
I was keen on trying the new version with the updated chrome patch.
To do so, I setup the new server build on the existing server 2012 R2 where I am running Quasar currently, stopped the old server (to free up the port) and then ran the new server, after updating my .NetFramework to 4.8

I also imported the old certificate from the previous instance.

Neither did the old clients connect nor did new clients connect to the new server build.

I then ran new build server on a Windows 10 machine, where new created clients were able to connect without any problem.
So I raised this issue.

**Comment by MaxXor** [comment]
That's weird, do you still have the old quasar installation available on the windows server? If you updated directly from the previous version (1.3.0.0) to the latest commit it is required to follow this update procedure: https://github.com/quasar/Quasar/wiki/Updating-a-Client

I'll try to setup a Windows server 2012 instance in the next few days to reproduce this issue.

**Comment by MaxXor** [comment]
Okay, I've tested everything on a fully patched Windows Server 2012 R2 and it's working fine. However the firewall rule to allow remote connections needs to be manually added.

**Comment by MaxXor** [comment]
I've add the manual creation of windows firewall rules to the wiki: https://github.com/quasar/Quasar/wiki/Getting-Started#4-adding-a-firewall-rule
