### ISSUE TITLE
Please Add the Following Features:

### ISSUE THREAD

**Issue by JacobF-dev** [quasar/Quasar#833]
Please add persistence and audio capture to your program.

Many thanks,
Jacob

**Comment by haxpak** [comment]
Hi Jacob, 

Persistence already exists in the program

you have two ways to persist, 
use the client installation while building the client,
or add the program to startup from the file explorer once the client has connected to the server first time.

**Comment by MaxXor** [comment]
More intrusive mechanisms than simple persistent installation of clients are not planned. Audio capture was already suggested before.
