### ISSUE TITLE
Option to Set Password is Absent

### ISSUE THREAD

**Issue by JacobF-dev** [quasar/Quasar#836]
**Describe the bug**
The option to set a connection password is no longer present in version 1.4.0, although is was present in version 1.3.0.0.

**To Reproduce**
1. Open 'Quasar.exe'
2. Click on 'Settings'
3. Look for a 'Password' box.
4. The option is nonexistent.
5. Try the same steps on version 1.3.0.0

**System**
 - Server OS: Windows 10
 - Server installed .NET Framework version: Latest
 - Quasar Version: 1.4.0

Is the password set somewhere else, or is it completely removed?

**Comment by MaxXor** [comment]
Hey, it is no longer necessary due to the new way the client and server authenticate each other using X.509 certificates. The only thing you need to store safely now is the server certificate, called `quasar.p12`.

**Comment by JacobF-dev** [comment]
Okay, just confirming, the connection is still encrypted, but the password is stored in the quasar.p12 file. Right?

**Comment by MaxXor** [comment]
Yes the connection is still encrypted (stronger than before btw). There is no password in the `quasar.p12` file, but a server certificate including a cryptographic key pair which is more secure than a password.

**Comment by JacobF-dev** [comment]
OK! Thank you for your help and commitment!
