### ISSUE TITLE
Tested On Virtual Machine Working Fine  BUT 

### ISSUE THREAD

**Issue by h0ay** [quasar/Quasar#837]
I  am using openvpn configuration and portmap.io for port forwarding 

I added the ip of the port map as well the assigned ip 

When i run it on my virtual machine , it's runs flawlessly but when i run on a pc not connected to the same network , No client is joining 

But when i check the pc which is not in the network , i see the quasar client is running in task manager , any fix ? 

Do you have telegram to contact you /?

**Comment by MaxXor** [comment]
Please provide all necessary information of the bug report template.

**Comment by h0ay** [comment]
I am using portmap.io and openvpn configuration,i tested on my virtual machine ,it works fine but on other machines it does not even works
