### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by alinoordin** [quasar/Quasar#838]
after add my port and it connect successfull but wen build stub and run a test it will not report

**Comment by alinoordin** [comment]
after add my port and it connect successfull but wen build stub and run a test it will not report

**Comment by MaxXor** [comment]
Please provide all necessary information of the bug report template.

**Comment by alinoordin** [comment]
max i use port 1600,1800,1334 and the port are open and connecting well. but when i build stub and and run a test on pc and rdp, it will not report on the rat
