### ISSUE TITLE
Doesn’t connect to client

### ISSUE THREAD

**Issue by Ninetys99** [quasar/Quasar#840]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System**
 - Server OS: [e.g. Windows 10]
 - Client OS: [e.g. Windows 7]
 - Server installed .NET Framework version: [e.g. v4.8]
 - Client installed .NET Framework version: [e.g. v4.8]
 - Quasar Version: [e.g. 1.3.0 or commit-id]
 - Build configuration: [e.g. Debug/Release]

**Additional context**
Hi, I’m using Quasar in Win 10 and release. When someone runs the client, it will not connect. However, it works on myself when I run the client it just doesn’t work when others run the client.

**Comment by MaxXor** [comment]
Please follow this guide: https://github.com/quasar/Quasar/wiki/Getting-Started#4-adding-a-firewall-rule

Also add port forwarding rules (or use UPnP) in your router if you want to allow connections from WAN.

**Comment by Ninetys99** [comment]
I did all of that it still doesnt connect to other people
