### ISSUE TITLE
File transfer fails when transfers over 2GBs in 1 file

### ISSUE THREAD

**Issue by Airchunk** [quasar/Quasar#841]
I was using quasar to transfer files to another computer, this file was 4GBs and when it got to 50% it said "Error reading file" i tested this on a few more files that are over 2GBs none of them transferred successfully and failed when they got around the 2GB mark, this happens both ways if it is uploading or downloading files.

**Screenshots**
https://imgur.com/U2c6sjT

**System**
 - Server OS: Windows 10
 - Client OS: Windows 10
 - Quasar Version: 1.4.0
 - Build configuration: Release

**Comment by MaxXor** [comment]
Hi, thanks for reporting this issue. Are you using 32 bit or 64 bit systems on client & server?

**Comment by saoye-dve** [comment]
I'm 64 A System



---Original---
