### ISSUE TITLE
select options with '<>' is not rendered as text

### ISSUE THREAD

**Issue by rvyas** [quasar/Quasar#843]
**Describe the bug**
If I specify an option in '<' and '>', it is not rendered as text.

**To Reproduce**
1. For q-slect define options as: 
`   options: [ 'Google', '<Facebook>', 'Twitter', 'Apple', 'Oracle'  ]`
2. Click on Select for drop down options
4. Notice the option blank

**Expected behavior**
Instead of blank, it should be `<Facebook>`

**Screenshots**
![image](https://user-images.githubusercontent.com/2732444/86038567-fd899600-b9f5-11ea-832b-9900352bc645.png)

**System**
 - Quasar Version: 1.9.13 (and latest too)

**Comment by Charterino** [comment]
Try to, uh, forward this issue to Vue developers.

**Comment by MaxXor** [comment]
Hi, I think this is the wrong project, check out https://github.com/quasarframework/quasar

**Comment by rvyas** [comment]
Sorry!

**Comment by MaxXor** [comment]
No worries! :slightly_smiling_face:
