### ISSUE TITLE
Cannot compile .sln file

### ISSUE THREAD

**Issue by Xsnipe** [quasar/Quasar#848]
when opening up the .sln file in visual studio. I get an error saying some file could not be opened and no file loads

**Comment by MaxXor** [comment]
What Visual Studio version are you using? What's the exact error message?

**Comment by Xsnipe** [comment]
I am running visual studio 2019 16.6.3 and the error says "One or more projects in the solution were not loaded correctly. Please see the output Window for details" The following errors are what are in the output.

~~~
Quasar.Server\Quasar.Server.csproj : error  : The SDK 'Microsoft.NET.Sdk.WindowsDesktop' specified could not be found.  C:\Users\Name\Desktop\whitelist\quasar\Quasar\Quasar.Server\Quasar.Server.csproj

Quasar\Quasar.Client\Quasar.Client.csproj : error  : The SDK 'Microsoft.NET.Sdk.WindowsDesktop' specified could not be found.  C:\Users\Name\Desktop\whitelist\quasar\Quasar\Quasar.Client\Quasar.Client.csproj

Quasar\Quasar.Common\Quasar.Common.csproj : error  : The SDK 'Microsoft.NET.Sdk' specified could not be found.  C:\Users\Name\Desktop\whitelist\quasar\Quasar\Quasar.Common\Quasar.Common.csproj

Quasar\Quasar.Common.Tests\Quasar.Common.Tests.csproj : error  : The SDK 'Microsoft.NET.Sdk' specified could not be found.  C:\Users\Name\Desktop\whitelist\quasar\Quasar\Quasar.Common.Tests\Quasar.Common.Tests.csproj

~~~

I have installed the .Net SDK from the following link 

https://dotnet.microsoft.com/download/dotnet-core/thank-you/sdk-5.0.100-preview.6-windows-x64-installer

**Comment by MaxXor** [comment]
You don't need .NET 5.0 SDK. [Modify your VIsual Studio installation](https://docs.microsoft.com/en-us/visualstudio/install/modify-visual-studio?view=vs-2019) and add **.NET desktop development**.

**Comment by Xsnipe** [comment]
I have built the file and now I am left with the bin folder, I go into the bin folder and there is a debug folder and no release folder. Is there supposed to be a release folder.

**Comment by Xsnipe** [comment]
never mind I got it. Thank you though.
