### ISSUE TITLE
Remote Desktop started

### ISSUE THREAD

**Issue by PrismaticEwe** [quasar/Quasar#850]
Is it possible when I start a remote desktop for the notification to not pop up on the victim? They said everytime I start it they get a notification

**Comment by MaxXor** [comment]
Please read the docs: https://github.com/quasar/Quasar/wiki/Client-deployment-settings#unattended-mode

**Comment by PrismaticEwe** [comment]
so if I check unattended mode they wont get a nitofication?

**Comment by MaxXor** [comment]
Yes
