### ISSUE TITLE
Password recovery doesn’t work

### ISSUE THREAD

**Issue by Ninetys99** [quasar/Quasar#855]
**Describe the bug**
Password Recovery is not working

**To Reproduce**
Right click on a client, click password recovery 

**Expected behavior**
List of usernames and passwords should be available

**System**
 - Server OS: Windows 10
 - Client OS: Windows 10
 - Quasar Version: 1.4
 - Build configuration: Release

**Additional context**

**Comment by MaxXor** [comment]
It is fixed in the master branch, you can get it compiled here: https://ci.appveyor.com/project/MaxXor/quasar/builds/33483558/job/l9v96242u1prgbb4/artifacts
