### ISSUE TITLE
FileChunk Int32 overflow

### ISSUE THREAD

**Issue by devcore256** [quasar/Quasar#857]
**Description**
File downloading is not work correctly for files larger than Int32.MaxValue (**2147483647 bytes**). You will get error message from client "Error reading file" when you try `_fileStream.Seek(offset, SeekOrigin.Begin);` in method ReadChunk(long offset).

Bug in class **Quasar.Common.IO.FileSplit**

```
public IEnumerator<FileChunk> GetEnumerator()
        {
            for (int currentChunk = 0; currentChunk <= _fileStream.Length / MaxChunkSize; currentChunk++)
            {
                yield return ReadChunk(currentChunk * MaxChunkSize);
            }
        }

```

When pass arg to ReadChunk method currentChunk * MaxChunkSize is casting to Int32. We must declare currentChunk as **long**.

**Expected behavior**
```
public IEnumerator<FileChunk> GetEnumerator()
        {
            for (long currentChunk = 0; currentChunk <= _fileStream.Length / MaxChunkSize; currentChunk++)
            {
                yield return ReadChunk(currentChunk * MaxChunkSize);
            }
        }
```

**Comment by MaxXor** [comment]
Nice catch and very detailed error report. Thanks a lot!
