### ISSUE TITLE
Quasar is being deleted by Antivirus

### ISSUE THREAD

**Issue by solatali** [quasar/Quasar#859]
Hi, my issue is that as soon as I download and extract the zip from release version, my antivirus automatically detects the "exe" as virus and deletes it. I can add it as quarantine but that's not a permanent solution for my use case unfortunately, as I can have to run this program on many client machines and can't ask them to first quarantine the exe path. 

What is the solution for it? What are your thoughts please? 

Now, as per my research, I believe that signing the exe with a valid certificate such as "DigiCert" (used by Mozilla) will resolve the issue. I used a site "https://www.virustotal.com/" to scan the "Quasar.exe" file and found 44 issues. I self-signed it then and it produced only 24 errors, but still it's not perfect [(screenshots](url) attached for Quasar.exe scan)

My question is, do I absolutely need to purchase a certificate from valid CA like Digicert and sign the exe to resolve this problem? Would just signing be enough or it can also flag the app. while it's executing? And if certificate is not required, what are the ways I can remove this check? Maybe I have to change source code (Assembly file) or something else? 

Please let me know. This is an urgent project and I'm on a very strict deadline so I would very much appreciate your help here!

Kindest Regards,
Solat

![image](https://user-images.githubusercontent.com/30649120/89682718-a5a54f80-d910-11ea-8cf5-9401fd501dd2.png)
![image](https://user-images.githubusercontent.com/30649120/89682738-accc5d80-d910-11ea-8e60-edac3c3bd84e.png)

**Comment by MaxXor** [comment]
Hey, your options are to remotely add the AV exception first and then deploy the Quasar client or to try removing the unnecessary functions for your use-case from the Quasar client in the source code to see if it's still detected once compiled. Unfortunately Quasar is sometimes used in questionable circumstances which makes it impossible to remove the AV detections.

**Comment by solatali** [comment]
Thanks for replying. Now, I think I need all the functionality of the client and can't remove things per-say. But, what about the code signing thing? Would that work out? Like if I purchase a certificate from "DigiCert" let's say (Mozilla uses it) and then use it to sign the exe, would that suffice? 

Or can the exe still be flagged while it's running?

**Comment by MaxXor** [comment]
I think it might depend on the AV in use. Check out if all signed software is trusted by default.

**Comment by solatali** [comment]
Yes, they are. But what I was saying, is while the client is running, are there chances that app. could still be flagged? Also, has any other user ever actually mentioned this issue I'm facing?

**Comment by solatali** [comment]
Please respond on the last question!

**Comment by MaxXor** [comment]
There is no way I can tell you whether signing the client binary will 100% work for your use case. Please do your own research. Yes, other users have faced the same issue, see here: https://github.com/quasar/Quasar/issues?q=is%3Aissue+antivirus+is%3Aclosed

**Comment by solatali** [comment]
Thank you for the reply. Just 1 quick question. I checked the following closed question: 
https://github.com/quasar/Quasar/issues/658

And you mentioned "There are some suspicious functions included, that's why it's detect by antivirus." Can you please point them out? So, maybe I can decide to remove them from the code? 

Also, what are your thoughts on the following solution suggested by another user? 
![image](https://user-images.githubusercontent.com/30649120/89708878-44bf5b00-d994-11ea-93c9-83343b035173.png)

Thank you in advance

**Comment by MaxXor** [comment]
That was 2 years ago. Most of the functions are removed by now. I suspect the password recovery functions to play an important role for the detection. You can try to remove these.

**Comment by solatali** [comment]
Sure, I'll take a look. And any idea about that "App Loader" suggestion? Would that work out in this use case?

**Comment by MaxXor** [comment]
It's lots of trying to get it right. Definitely not easy.

**Comment by solatali** [comment]
Thank you for the answers Max!

Now, I contacted my client and he told me to just keep "Screen mirroring and task manager" for the client app. I believe, we can get through the AV detection then, right?

**Comment by MaxXor** [comment]
Try it out.

**Comment by solatali** [comment]
Sure, thank you so much.

**Comment by BurntDog** [comment]
Not to smart for using Virustotal to check tools like this, noob 101....
