### ISSUE TITLE
Downloading is break when reaching to 90 % 

### ISSUE THREAD

**Issue by maamirh** [quasar/Quasar#861]
I tried many times to download a large file near about 2.3GB . When downloading is reaching 90% then downloading is showing cancelled and sometimes showing reading error.

**Comment by MaxXor** [comment]
Yes, there is a problem with the latest release (https://github.com/quasar/Quasar/issues/841). It's fixed in the latest commit of the master branch. Either build the project yourself or download it from the CI: https://ci.appveyor.com/project/MaxXor/quasar/build/job/jyim27sccqhr39yw/artifacts

**Comment by maamirh** [comment]
I use this link CI: https://ci.appveyor.com/project/MaxXor/quasar/build/job/jyim27sccqhr39yw/artifacts and build the project again but still gaining same problem when downloading cross to 90% I am getting reading error and the downloaded file is disappearing.
