### ISSUE TITLE
Connections not showing

### ISSUE THREAD

**Issue by Salty-Coder** [quasar/Quasar#862]
I have port forwarded correctly and disabled antivirus on my VM (also running bridged mode). I can start the client and it will run in the background but it won't show up in the connections list. A photo of the port forwarding is below ![image](https://user-images.githubusercontent.com/59771980/90158456-eb39a080-dd86-11ea-8ed6-fe548211d900.jpeg)

**Comment by Salty-Coder** [comment]
Tried again and worked...

**Comment by Salty-Coder** [comment]
I'm pretty sure it's due to trace back as I was trying to use my external ip when testing on the same vm. I tried using my internal and it worked. If I want to try it on another device now (ethical (my other devices)) would I need to use my external ip? It's all set up with port forwarding.

**Comment by MaxXor** [comment]
Glad you figured it out! Yes, you should use your external IP for devices outside your LAN.

**Comment by Salty-Coder** [comment]
> Glad you figured it out! Yes, you should use your external IP for devices outside your LAN.

Is there any point in using No-IP? Does it work as well? Also what are the benefits of using that instead of a general External IP? I know you need to keep the DUC open at all times. The only reason I know for using No-IP is that no one can fin your IP from reverse engineering but are there any other reasons to use it? Also what would you suggest, regular External IP or No-IP?
