### ISSUE TITLE
[ Not Bug ] Can’t find camera feature

### ISSUE THREAD

**Issue by Salty-Coder** [quasar/Quasar#863]
Sorry this isn't a bug report but, I saw in the updates file that there is now a feature to view the webcam. I can't find it on the list of features. Has it been removed or does it mean there is no camera? Thanks.

**Comment by MaxXor** [comment]
It has been removed cause it has too much potential to be abused.

**Comment by Salty-Coder** [comment]
> It has been removed cause it has too much potential to be abused.

Yeah that's all fine. I completely understand that. If someone were to use it illegally it would be a bit of a problem
