### ISSUE TITLE
Still Large File Downloading is not working .

### ISSUE THREAD

**Issue by maamirh** [quasar/Quasar#864]
I use this link CI: https://ci.appveyor.com/project/MaxXor/quasar/build/job/jyim27sccqhr39yw/artifacts and build the project again but still gaining the same problem in both binaries when downloading cross to 90% I am getting reading error and the downloaded file is disappearing.

![image](https://user-images.githubusercontent.com/46965638/90185276-e220f180-ddcf-11ea-94b3-b721b16c1e70.png)

I am using Windows 7 under VM and the latest version of Visual Studio 2019.

**Comment by MaxXor** [comment]
You need to re-deploy the client.

**Comment by maamirh** [comment]
I used your given link latest version binary but face the same problem then I pull from the Master branch and again re-build the project but the problem exists again.

**Comment by MaxXor** [comment]
What I tried to say was: You need to create a new client using the Quasar.exe you just downloaded because both the client and server needs to be replaced.

**Comment by maamirh** [comment]
Now it's fixed. I update both client and server and now I successfully download 2GB files. Thanks for the wonderful product.
