### ISSUE TITLE
Host won't appear in Quasar on Windows 7

### ISSUE THREAD

**Issue by on1ytime** [quasar/Quasar#870]
**Describe the bug**
Quasar v1.3 connects normally on windows 7/8/10
Quasar v1.4 connects normally on windows 8/10
But Quasar v1.4 can't connect normally in windows 7，Whether the machine is connected to itself, or the machine is connected to other machines.
I am sure that the correct port and host are set, and I also tested that both the server and the client are installed on win7. Even if the client connects to the host through the address 127.0.0.1 and port 4782, the client cannot appear on the server.

**Expected behavior**
Fix this bug on Quasar v1.4

**System**
 - Server OS: [Windows 7/10]
 - Client OS: [Windows 7]
 - Server installed .NET Framework version: [v4.5.2/v4.8]
 - Client installed .NET Framework version: [v4.5.2/v4.8]
 - Quasar Version: [1.4]
 - Build configuration: [Release]

**Comment by MaxXor** [comment]
Be sure to install all Windows 7 updates.

![Screenshot from 2020-08-25 18-30-11](https://user-images.githubusercontent.com/7271470/91201710-14e8b500-e701-11ea-91a1-7ad22b80710e.png)
