### ISSUE TITLE
Format is broken and weird 

### ISSUE THREAD

**Issue by Quessts** [quasar/Quasar#872]
**Describe the bug**
For some reason when I open Quasar I run into this weird format https://prnt.sc/ucjzj4
**To Reproduce**
Open Quasar

**Expected behavior**
To look at a clean good looking format
**Screenshots**
https://prnt.sc/ucjzj4

**System**
 - Server OS: Windows 10
 - Client OS: None
 - Server installed .NET Framework version: v4.8
 - Client installed .NET Framework version: None
 - Quasar Version: Same result on V1.3 and V1.4
 - Build configuration: Release

**Comment by MaxXor** [comment]
What are your windows font scaling settings?

**Comment by Quessts** [comment]
It's this https://prnt.sc/uxy9bn their are the default settings I haven't changed a thing on my pc ever since I got it
