### ISSUE TITLE
quasar rat not working

### ISSUE THREAD

**Issue by hackingkid** [quasar/Quasar#875]
hi!
i have quasar rat . 
i did all the things it needed. but when i use on my own pc it works. even if i use another laptop or pc that is connected with the router it works fine. but if i connect that victim laptop with another router then it doesn't work.

what is the problem?
please help!

**Comment by AzgarDev** [comment]
You need to por foward

**Comment by hackingkid** [comment]
i did that. the IPV4 port works but pc that is connected with the same router. others not working. what should i do?

**Comment by GlowingUmbreon** [comment]
Make sure you are actually using your external IP instead of your internal IP.
