### ISSUE TITLE
i keep getting this error message

### ISSUE THREAD

**Issue by Sendoor-cyber** [quasar/Quasar#876]
when attempting to open and use quasar i keep getting this error message, but before the message occurs quasar keeps closing itself, im not really that experienced when it comes to this due to the fact that this is technically the first time i have ever tried to use quasar only for it to do this, i would be really thankful if i can get help with this 

**Screenshots**
![image](https://user-images.githubusercontent.com/71958769/94357287-9ebfd100-0065-11eb-9c77-ca2d96f86da4.png)

**System**
 - Server OS: [e.g. Windows 10]
 - Client OS: [e.g. Windows 7]
 - Server installed .NET Framework version: [e.g. v4.8]
 - Client installed .NET Framework version: [e.g. v4.8]
 - Quasar Version: [e.g. 1.3.0 or commit-id]
 - Build configuration: [e.g. Debug/Release]

**Comment by AzgarDev** [comment]
I dont have hope for humans anymore.
Just extract it man
