### ISSUE TITLE
Quasar Client Builder Error

### ISSUE THREAD

**Issue by BackdoorsForPc** [quasar/Quasar#877]
Hello, I have setup the builder normally but when i build it to the default directory it gives me this error:

![Screenshot_18](https://user-images.githubusercontent.com/71266514/94437489-198c0780-019e-11eb-8932-c818608d2dc4.png)

OS: Windows 10
Quasar Version: 1.4.0
Build configuration: Release

**Comment by MaxXor** [comment]
Please add an exception to the quasar directory in your AV. The file is being deleted by your AV.
