### ISSUE TITLE
Quasar doesn't start

### ISSUE THREAD

**Issue by sharicov** [quasar/Quasar#879]
**Describe the bug**
Quasar won't start

**To Reproduce**
Double click on quasar.exe nothing happens
Start as admin - nothing happens
Start from terminal - nothing happens

**System**
 - Server OS: Windows 10 1909 64-bit home
 - Client OS: [e.g. Windows 7]
 - Server installed .NET Framework version: v4.8

 - Quasar Version:1.4.0
 - Build configuration: Release

**Comment by GlowingUmbreon** [comment]
Same for me, began happening after a reboot.
