### ISSUE TITLE
Quasar can't connect to diffrent ip.

### ISSUE THREAD

**Issue by sahfjkchdkshfckjsd** [quasar/Quasar#880]
I have set it the port and its port is open. I try to connect to it on my other laptop and its works however when I try to connect from another ip and the client won't connect.

**Comment by MaxXor** [comment]
Please enable port-forwarding on your router if you want to to allow client connections from WAN. https://github.com/quasar/Quasar/wiki/Getting-Started

**Comment by sahfjkchdkshfckjsd** [comment]
I did that it's not working.
