### ISSUE TITLE
Client doesn't connect on my own computer

### ISSUE THREAD

**Issue by owly111** [quasar/Quasar#885]
**Describe the bug**

Hello, I am not able to get my client show up even on my local computer (using 127.0.0.1 and local Ip), same thing from remote. I disabled firewall and my ports are open.

**To Reproduce**
Build the client using 127.0.0.1 and run it.

**Expected behavior**
I expected my client to connect without problems (as it's my own network) but it didn't.

**System**
 - Server OS: Windows 7
 - Client OS: Windows 7
 - Server installed .NET Framework version: 4.5
 - Client installed .NET Framework version: 4.5
 - Quasar Version: Latest version
 - Build configuration: Release

**Comment by BurntDog** [comment]
Have you figured it out? Your AV was off as well?

**Comment by MaxXor** [comment]
Can't reproduce this on a fully updated Windows 7 system. Please install all Windows and .NET framework updates.
