### ISSUE TITLE
Notification when starting remote desktop session?

### ISSUE THREAD

**Issue by multiswagsir** [quasar/Quasar#887]
Hello, I am using the newest version of Quasar. I installed the client on my virtual machine, but when I start a remote desktop session, my Virtual machine gets a notification. The last time I used Quasar (A week ago or so) This did not happen, so I'm wondering when this was added and if there's any way to stop it. Thanks!

**Comment by multiswagsir** [comment]
Fixed it

**Comment by MaxXor** [comment]
This is the setting you are looking for: https://github.com/quasar/Quasar/wiki/Client-deployment-settings#unattended-mode
