### ISSUE TITLE
I can't download the fucking R.A.T

### ISSUE THREAD

**Issue by Ral721chanel** [quasar/Quasar#890]
When I open the file that is in .lsn and give it to download, I get an error. I don't understand why the hell they removed the .bat installer or they don't put the downloaded file directly so they don't have to do the whole process. Before I could download it perfectly but now they screwed it up

**Comment by MaxXor** [comment]
Download it on [this page](https://github.com/quasar/Quasar/releases/tag/v1.4.0) on the bottom and add an exception to your antivirus.
