### ISSUE TITLE
Remote desktop bug when using scaling

### ISSUE THREAD

**Issue by acquykhud** [quasar/Quasar#892]
**Describe the bug**
When client changes the size of text to 125%, remote desktop won't be able to see all the screen.

**To Reproduce**
Steps to reproduce the behavior (at client computer)
1. Right click on desktop
2. Click on 'Display settings'
3. Scroll down to 'Scale and layout'
4. 'Change the size of text, apps and other items' -> 125%

**Expected behavior**
Remote desktop should be able to capture the whole desktop

**Screenshots**
![image](https://user-images.githubusercontent.com/29769801/101439373-f1134d00-3946-11eb-9628-5a6646d94274.png)

**System**
 - Server OS: Windows 10
 - Client OS: Windows 10
 - Server installed .NET Framework version: 4.8
 - Client installed .NET Framework version: 4.8
 - Quasar Version: 1.2.0.0
 - Build configuration: Release

**Comment by MaxXor** [comment]
Please use the latest quasar version. Updating is explained here: https://github.com/quasar/Quasar/wiki/Updating-a-Client
