### ISSUE TITLE
::Solved::Won't connect using external ip, ports are forwarded ::Solved::

### ISSUE THREAD

**Issue by BurntDog** [quasar/Quasar#896]
**System**
 - Server OS: Windows 10
 - Client OS: Windows 10
 - Server installed .NET Framework version: v4.8 or newer
 - Client installed .NET Framework version: v4.8 or newer
 - Quasar Version: 1.4.0
 - Build configuration: Release

My issue is it connects using loopback but not with ports forwarded and using external ip. Even my Webserver software won't get outside connections (from myself) to host a webpage but, loopback works there as well. My Cable Modem Router has all necessary ports forwarded must be a windows thing.. It has to be a Windows setting I can't find..  Disabled everything ie. Firewall/AV and still no luck, please advise.
 
Tested outside my OS using a Android Rat using Data not home wifi and then it will connect.
Also using cellphone data able to connect to webserver as well.

I tested Quasar using portmap.io where port forwarding is not needed and it did work in the past but, not now.
What setting(s) in Windows am I missing? Thinking some update screwed things up.
please advise.

**Comment by BurntDog** [comment]
Solved: Reinstalling OpenVPN GUI fixed that issue I spoke about. Loopback works fine as stated but I guess using "Public IP" while one the same system as server/client will not work which I'm guess at this point is normal. Can't use public ip as a loopback. Need to use NoIp or portmap.io or normal 127.0.0.1 loopback

Feel free to close this issue.
I need to test from a outside the network windows machine which not able to at this time.
All looks good at this point. 

Port Forward without getting into Router using portmap.io
https://www.youtube.com/watch?v=cV9CtR84wSc

**Comment by MaxXor** [comment]
Thanks for also sharing the solution! Happy new year to you @BurntDog. :partying_face:

**Comment by pentest01** [comment]
I did all these, but i'm still running through issues.
