### ISSUE TITLE
Client disappeared

### ISSUE THREAD

**Issue by khan7869** [quasar/Quasar#898]
The client connected but after 10 min he disappeared automatically while he still on. then never connected back

**Comment by assadi49** [comment]
the antivirus is probably reactivated

**Comment by khan7869** [comment]
Client antivirus?

**Comment by assadi49** [comment]
> Client antivirus?

Yes.

**Comment by khan7869** [comment]
Any way to bypass antivirus?

**Comment by BurntDog** [comment]
Add exclusion within your AV software...

**Comment by khan7869** [comment]
How?

**Comment by BurntDog** [comment]
Which AV are you using?

**Comment by khan7869** [comment]
What is AV?

**Comment by BurntDog** [comment]
Antivirus software

**Comment by khan7869** [comment]
I don't use any antivirus in my computer and windows defender also turned off

**Comment by BurntDog** [comment]
On Windows 10 (fully up to date) Defender will turn back on automatically after a short while..

**Comment by khan7869** [comment]
That's my windows defender why it make disappear my client from RAT?

**Comment by BurntDog** [comment]
Why? It's a RAT, Add exclusion

**Comment by BurntDog** [comment]
Open Defender where you turn it off(manage settings). Scroll down and you will see "Exclusions" click on "Add and remove exclusions" choose folder where you have client or just the file your choice.

**Comment by khan7869** [comment]
Yesterday I tested this RAT. The client which I was testing disappears from RAT. Before it was connected then suddenly disappeared

**Comment by khan7869** [comment]
I am not talking about the file which I build but the victim disappeared after connected for 10 min

**Comment by khan7869** [comment]
It seems problem with Remote Desktop because when I open Remote Desktop it disappears

**Comment by BurntDog** [comment]
port conflict?

**Comment by khan7869** [comment]
I farwarded port and checked they were open

**Comment by MaxXor** [comment]
Please use the correct issue template. https://github.com/quasar/Quasar/issues/new?template=bug_report.md
