### ISSUE TITLE
Only working with user application data. With program files and system it don’t work when I tested on VM

### ISSUE THREAD

**Issue by khan7869** [quasar/Quasar#900]
Only working with user application data. With program files and system it don’t work when I tested on VM

**Comment by MaxXor** [comment]
It requires Administrator privileges.

**Comment by khan7869** [comment]
Administrator privileges from victim side?

**Comment by BurntDog** [comment]
Yes.............Use option "Elevate Permissions" in toolbar: https://prnt.sc/we9o9x
Client/Victim will need to except UAC. and No there is now way to bypass UAC built into Quasar.

**Comment by khan7869** [comment]
@BurntDog do you have discord?

**Comment by BurntDog** [comment]
Just installed it to see what it's all about.

**Comment by khan7869** [comment]
@BurntDog do you use any crypter for Quasar? Which can bypass windows defender and all other anti viruses?

**Comment by BurntDog** [comment]
Yes, however even though Defender doesn't detect the file itself, once it runs Defender will detect it (by behavior analysis) so I just make a exclusion within Defender.

**Comment by khan7869** [comment]
Which crypter are you using?
