### ISSUE TITLE
Clients making a connection to (questionable?) IP not added to host list 

### ISSUE THREAD

**Issue by jbmorris289** [quasar/Quasar#904]
Hi! 
I just started using Quasar a couple days ago. While installing a client to a computer, I had a program called "[Process Hacker](https://github.com/processhacker/processhacker)" open on the "Network" tab to make sure things were working as I was trying to tunnel it through my local home server to my laptop, and saw this unrecognized IP:
![firefox_SA8svNbEqw](https://user-images.githubusercontent.com/22121073/103427251-57297380-4b85-11eb-9cd1-172dcf7af653.png)
This IP is on [AbuseIPDB](https://www.abuseipdb.com/check/185.172.148.96).
I also built a client and ran it on my laptop, pointing it to itself (localhost), and the same IP showed up on that list right as the client prepared itself.
The confusing part is that none of the clients are configured to connect over the internet... just locally. 
What may be happening here? Thanks?

**Comment by BurntDog** [comment]
I think I've asked this in the past and nothing to be concerned about but, I wouldn't mind a reminder.

I get a different connection each time
ec2-54-243-119-179.compute-1.amazonaws.com
ec2-50-19-243-236.compute-1.amazonaws.com
ec2-23-21-252-4.compute-1.amazonaws.com

Could be a stay alive thing or to get a geolocation

**Comment by MaxXor** [comment]
These connections are HTTP requests to retrieve geo IP location, see here https://github.com/quasar/Quasar/issues/637

**Comment by jbmorris289** [comment]
Guess I didn't search enough terms on here before making this issue... sorry for the duplicate!
