### ISSUE TITLE
connections not popping up

### ISSUE THREAD

**Issue by ryanclemmer** [quasar/Quasar#909]
i download quasar 14 on my pc then i built  it and put the client on my windows 10 vm on virtual box and when i went back to see if it had popped up there was nothing i played around with the settings and rebuilt it a couple of times and there was no change i also used other rats like nanocore and it also would not pop up i opened port 49811 and i checked and it is for sure open plz help

**System**
 - Server OS Windows 10
 - Client OS: Windows 10

**Comment by BurntDog** [comment]
Are you using noip or portmap.io? Does 127.0.0.1 or localhost loopback work?

**Comment by ryanclemmer** [comment]
thanks for trying to help me i just figured it out it 
it just wasn't working on my computer if i opened the file on another computer it worked i was opening it on my vm but any ways thanks again :)
