### ISSUE TITLE
quasar no connection 

### ISSUE THREAD

**Issue by ryanclemmer** [quasar/Quasar#910]
i installed quasar a couple of days ago and i cant seem to get the client to pop up in quasar every time that i open ithe client it pops up and the bottom of my screen the it has no connection any idea how to fix it 
![Screenshot 2021-01-06 034307](https://user-images.githubusercontent.com/76997638/103748140-a7fbfa80-4fd1-11eb-87f3-c3133d436e66.png)

**Comment by BurntDog** [comment]
Did you first try loopback? ip 127.0.0.1 port "your choice" ie.. 8080 did it connect? Are you using noip or other? Running client on a VM? Running client and server at same time on the same machine(use loopback if so)?

**Comment by ryanclemmer** [comment]
thanks for trying to help but i used someone else pc and it worked fine thanks
