### ISSUE TITLE
Trojan: MSIL/Perseus.AKR!rfn

### ISSUE THREAD

**Issue by yezz123** [quasar/Quasar#912]
**Is your feature request related to a problem? Please describe.**
You Need to make it more Secure for a user to trust Cause _Windows Defender_ detected.

**Describe the solution you'd like**
Encrypt the code or use the Clean Version with packages.

**Comment by BurntDog** [comment]
You're calling yourself a programmer and hacker but, you don't seem to understand how coding and releasing software works. 
First, this tool is FREE-for educational use. You're a programmer (make it more Secure) make it so
Second, Windows Defender detects it- helps prevent no skill script kiddies from abusing

And, to be removed from AV companies hot list one needs to summit their software (at the least) to major AV companies
Then to help avoid future detection purchase a certificate. However not full proof if code is often updated
Purchase a next level Certificate (more expensive) again not full proof if code is often updated

So inconclusion, if you offer your hard work for FREE would you Pay to go through all this?
It's opensource you're a programmer (make it more Secure) make it so

FYI, for a free tool as this, it is very secure, if you would take the time to read the code
you should have no reason to not trust this software..

**Comment by BurntDog** [comment]
FYI,      Trojan: MSIL/Perseus.AKR!rfn The "!"  means it was detected by  a A.I. learning detection method not a actual listed virus.

**Comment by yezz123** [comment]
Okay dude thank you for all what you said and i will told u that I'm respecting all the efforts.
I just said that if Windows defender detect that as trojan what can be helpful to use it and the Defender work or the Antivirus work that what i mean from this issue that all 🙏
