### ISSUE TITLE
 validate  form one  key 

### ISSUE THREAD

**Issue by dirkhe1051931999** [quasar/Quasar#914]
**Describe the bug**
i want validate  form one key not validate all key 
now api is `this.$refs.retrieveForm.validate().then(async (valid: boolean) => {});`
![image](https://user-images.githubusercontent.com/22389976/104708121-3e5db800-5758-11eb-821b-1d8fa539168f.png)

**System**
 - Server OS: [e.g. Windows 10] win10
 - Client OS: [e.g. Windows 7]
 - Server installed .NET Framework version: [e.g. v4.8]
 - Client installed .NET Framework version: [e.g. v4.8]
 - Quasar Version: [e.g. 1.3.0 or commit-id]  1.15.0
 - Build configuration: [e.g. Debug/Release]

**Additional context**

**Comment by MaxXor** [comment]
Wrong repo: https://github.com/quasarframework/quasar
