### ISSUE TITLE
Strange ip coneection

### ISSUE THREAD

**Issue by sevenleo** [quasar/Quasar#915]
I created an executable for the client computer (ip x.x.10.23) and called it portable.exe

When I connected to the server (ip x.x.10.5) I noticed that it opens a connection with the ip 185.172.148.96

But I do not recognize this ip and it is from outside my country.

Could you tell me what it is about? I don't see it in the source code

![image](https://user-images.githubusercontent.com/5843634/105042681-490f9a00-5a43-11eb-87ed-0f08bb76b68a.png)

https://www.ip-tracker.org/locator/ip-lookup.php?ip=185.172.148.96

**Comment by BurntDog** [comment]
This has been answered several times. It is for geolocation so server can display your clients general location. Read the code its opensource....

**Comment by sevenleo** [comment]
Thank you for the explanation.
