### ISSUE TITLE
Compilation issue in visual studio 2017

### ISSUE THREAD

**Issue by tajiknomi** [quasar/Quasar#916]
I'm trying to compile the solution but VS-17 doesn't load the Quasar.Client & Quasar.Server. Here is the screenshot
![Capture](https://user-images.githubusercontent.com/41329824/105574752-84360400-5d88-11eb-9d91-f5684eebeefd.PNG)

By right-clicking on the solution and executing the "Restore Nuget packages", VS says "All packages are already installed and there is nothing to restore"

Whats the issue ?

**Comment by BurntDog** [comment]
You need to use Visual Studio 2019..

**Comment by tajiknomi** [comment]
Thanks for the reply. I will install VS-19 and get back here if i get an issue.

**Comment by tajiknomi** [comment]
I've loaded the project solution in VS-19, same problem

**Comment by BurntDog** [comment]
What errors are showing? Look at bottom of IDE, it should tell you.

**Comment by tajiknomi** [comment]
There are no errors, The problem is , Quasar.Client and Quasar.Server doesn't load.
![Capture](https://user-images.githubusercontent.com/41329824/106724463-10b6b100-662a-11eb-9a3c-3d7282a8c5e9.PNG)

When i build the project, Only these files exist in the Debug folder

![Capture2](https://user-images.githubusercontent.com/41329824/106724509-1dd3a000-662a-11eb-86f2-0282db6d7674.PNG)


![Capture3](https://user-images.githubusercontent.com/41329824/106724612-38a61480-662a-11eb-8a59-92f63a100cc3.PNG)

**Comment by tajiknomi** [comment]
The problem is resolved after updating VS.

thank you.
