### ISSUE TITLE
Error Building Client (The system cannot find the file specified.)

### ISSUE THREAD

**Issue by anothergithubuser2** [quasar/Quasar#917]
**Describe the bug**
Attempting to build a client (for the first time) results in the given error

**Screenshots**
![image](https://user-images.githubusercontent.com/78054167/105917432-ea748e00-5ff7-11eb-8d9c-8ababd706d7d.png)

**System**
 - Server OS: Windows 10
 - Server installed .NET Framework version: 4.8.03752
 - Quasar Version: 1.4.0

**Additional context**
I reinstalled .NET Framework since I was having issues with it earlier but that doesn't seem to be the issue. Different settings, including connection hosts, don't resolve the issue either. No installed antiviruses, Windows Defender is disabled & excepting all directories containing the program.

**Comment by BurntDog** [comment]
Your using VS 2019?
