### ISSUE TITLE
Suggestion to make this RAT better!

### ISSUE THREAD

**Issue by SuperSnake802** [quasar/Quasar#918]
Hello,

In the beginning, I want to say thanks for this cool tool. Some features are not available like remote webcam, remote microphone, chatting with the clients and change desktop wallpaper.

Best wishes.

**Comment by BurntDog** [comment]
Please do a search and you will find that this has been posted and answered before, numerous times. I was removed in a previous release. You can add it back but, I don't think dev will. Also if you did a search you would find a link to such a version that still works except for password tool.
