### ISSUE TITLE
What ip should I put if I want to use my client on another network?

### ISSUE THREAD

**Issue by Korto9** [quasar/Quasar#920]
I configured port forwarding and no ip.

Thank you

**Comment by BurntDog** [comment]
Best to use noip or portmap when building client. If you forwarded ports needed all should be fine.

**Comment by Korto9** [comment]
I tried to put my no ip host and it doesn't work. The only thing that work is when I use my local ip 192.168.2.13.

What should I do?

**Comment by Korto9** [comment]
![image](https://user-images.githubusercontent.com/78448424/106684943-6b51fd80-6595-11eb-8af4-ed1b8a8af809.png)
this is how I set up my port forwarding.

**Comment by BurntDog** [comment]
Test with firewall on server side off.

**Comment by Korto9** [comment]
How do I do that?
I Turned my firewall off in the 2 pc.

**Comment by BurntDog** [comment]
Can you confirm that client is trying to connect using ProcessHacker or other?

**Comment by Korto9** [comment]
![image](https://user-images.githubusercontent.com/78448424/106814274-2505a880-6640-11eb-812c-bd6984d7203e.png)
That what I got.

**Comment by BurntDog** [comment]
what does it say in the network tab? Does it show it trying to connect to a port?

**Comment by BurntDog** [comment]
You should see the ip/noip address and port it is attempting to connect to.

**Comment by BurntDog** [comment]
Also just to be sure, you forwarded your port thru your router correct?

**Comment by Korto9** [comment]
![image](https://user-images.githubusercontent.com/78448424/106822665-808a6300-664d-11eb-849e-340e3b4d4a54.png)
It says SYN send but I doesn't connect to quasarat.
The rat is on the same computer as the client just to mention.

**Comment by Korto9** [comment]
Btw, Yes, I forwarded the port using 192.168.2.1

**Comment by Korto9** [comment]
And I don't see the no ip adress only the client.

**Comment by BurntDog** [comment]
OK, try using this https://portmap.io/  It's like noip but better cause no need to forward ports. I had same issue when trying to use my public ip so I use https://portmap.io/ and problem solved. Yes, it will also work from outside your own net work of course.  Install openvpn https://openvpn.net/community-downloads/  then import your config file you'll get from https://portmap.io Remember to have the server listen to the port you set up with portmap and your client will be set up with a address that looks like "Name-youchoose-33464.portmap.host" and for client port you use ????? for me it's "33464" yea same you'll see in the address  "Name-youchoose-33464.portmap.host" sounds confusing when I say it but it's easy.
