### ISSUE TITLE
Find the reverse ip in the exe?

### ISSUE THREAD

**Issue by CaptainFallaway** [quasar/Quasar#922]
Hello!

So as said in the title I want to find the reverse IP address and port. I have decompiled the exe file and wondering where to navigate to locate the IP?

back then I was using quasar 1.3.0 for extra information. 

![image](https://user-images.githubusercontent.com/69320425/106943196-68861280-6725-11eb-8f13-088af9f0e7e6.png)

**Comment by CaptainFallaway** [comment]
Sorry for doing this is "issues" i didn't know where to contact y'all.

**Comment by BurntDog** [comment]
Why are you doing it the hard way? If IP and port is all you need why not just run the exe in a VM or on old windows pc? Then use processes hacker or cports to get that info.

**Comment by MaxXor** [comment]
Check out the build process: https://github.com/quasar/Quasar/blob/master/Quasar.Server/Build/ClientBuilder.cs

However renaming is applied afterwards.

**Comment by CaptainFallaway** [comment]
well i was doing it to find an old VPNstaticIP ip adress and see if i can rebuy that specific one since there's some rats broadcating to that ip.
