### ISSUE TITLE
Multiple sessions are opened on the same client machine

### ISSUE THREAD

**Issue by ClearlyDev** [quasar/Quasar#923]
**Describe the bug**
Running the client.exe on a machine more than once (sometimes just once) can create multiple sessions connected to the server.
If there is more than one connection, the one that works will be assigned ADMIN privileges whereas the rest will just be USER. The connections with USER will connect to the server but will be uncontrollable by Quasar Server and will only report their connection status.

**To Reproduce**
I believe simply running the client more than once can reproduce this bug.

**Expected behavior**
The client should check if an instance of Quasar is already running on the machine before executing another instance.

**Screenshots**
These 3 clients are the same machine:
![image](https://user-images.githubusercontent.com/19656591/107144620-50381280-6934-11eb-9cc9-9c1132284c2b.png)

**Comment by BurntDog** [comment]
Never had this happen. Are you using the same or different Mutex?

**Comment by ClearlyDev** [comment]
I believe it was a Mutex issue after all. However, the server doesn't let you uninstall or disconnect from the extra connections once you have them open. Perhaps this could be fixed.

**Comment by BurntDog** [comment]
Have you tried deleting old clients thru server file manager? I don't think this is a bug issue more of why there is the mutex to avoid such things.

**Comment by ClearlyDev** [comment]
I just ran the same file with the same mutex multiple times in a row and it kept adding new clients to my server list.

**Comment by BurntDog** [comment]
Hmm, was under the impression that the mutex would prevent that. I will have to see if making the client run one instance only should solve that.

**Comment by BurntDog** [comment]
Looking at the code that is what the mutex should do, however testing it and watching the files run in process hacker I see client get killed but, it leaves a instance of cmd.exe doing a ping and that second client keeps restarting. I never get a connection in server but, that still shouldn't happen. I guess a fix is still needed.

**Comment by BurntDog** [comment]
OK, here's what I'm thinking. The mutex does stop the second client from running and the reason for the cmd.exe/ping then second client restart may have something to do with how/if you update client the new will need to run and if it has same mutex will only connect after you disconnect/uninstall from old/existing client

**Comment by MaxXor** [comment]
@ClearlyDev @BurntDog Thanks :+1:
