### ISSUE TITLE
How do I set up portmap.io to use quasar in an external network?

### ISSUE THREAD

**Issue by Korto9** [quasar/Quasar#926]
I have been strusggling for the past 2 weeks. Need help.

**Comment by BurntDog** [comment]
several good videos on YouTube

**Comment by MaxXor** [comment]
Please explain which steps you tried so far and where you are struggling.

**Comment by Korto9** [comment]
fh

**Comment by Korto9** [comment]
It doesn't work when I put the portmaphost.
