### ISSUE TITLE
Server went from 580K to 2MB

### ISSUE THREAD

**Issue by XUnderShadow** [quasar/Quasar#927]
**Describe the bug**
Recompiled the latest project and found that server.bin now is 2MB in size

**To Reproduce**
1. Clone Git
2. Load Projects
3. Rebuild Project Release mode
4. Go to ..\bin\Release\net452\  and see the size of server.bin/server.exe

**Expected behavior**
Maybe a size around 600k

**System**
-  Compiling on Windows 10

**Comment by XUnderShadow** [comment]
My bad
should have been client.exe/client.bin is 2mb now

in the release folder the size of client.bin is 2mb but the debug folder it's 177k

however building a client is only allowed in release configuration

**Comment by BurntDog** [comment]
That's a question for Max,,

**Comment by XUnderShadow** [comment]
i sort of fixed it by going to : publish client

the client goes down to about 130k and seems to work  ok

but i don't think that's the intended use

**Comment by BurntDog** [comment]
Why do you need the file to be that small? 2MB is a small file size for a legit app. Sounds like you want to bind to another exe for illegal purposes. That's not the intention of this project.

**Comment by XUnderShadow** [comment]
quasar is detected by every av on earth

so what accusing me of is virtually impossible

**Comment by MaxXor** [comment]
Dependencies unfortunately increased in favor of a properly secured connection with BouncyCastle. The library is the largest part of the 2MB.

**Comment by BurntDog** [comment]
@XUnderShadow Impossible, no but, this is not the place to talk about such things and won't say how I do it anyways.
