### ISSUE TITLE
Can't connect to client after pc reboot

### ISSUE THREAD

**Issue by BezMemow** [quasar/Quasar#928]
I have setup the Quasar program on the client and myself as always, everything worked fine, I use our common internet to connect (port forwarding), it was fine until I rebooted their computer, the Client doesn't connect anymore, the port is open i checked through the site canyouseeme.com or something like that. At first i thought the issue was due to the build not actually opening on startup, but as it happens, even when i doubleclicked on it twice again, it didn't connect either. Not sure why and what happened but I'm guessing the Build program just stopped working

 - Server OS: Windows 10
 - Client OS: Windows 10
 - Quasar Version: 1.4.0
 - Build configuration: Release
 
 I shutdown their computer through the shutdown option on Quasar, since i was too lazy to do it in real life. After that, it never connected since. (It connected only once and it was when I put the build file in the client pc)

**Comment by BurntDog** [comment]
What startup options did you use when building client thru server interface?

**Comment by BezMemow** [comment]
> What startup options did you use when building client thru server interface?

I chose for it to startup the moment the PC would, and the startup name i left it on default pretty sure.

**Comment by BurntDog** [comment]
And you did confirm that client did install correctly, in chosen location and left needed registry/other entries? Did it ever work after a reboot for you? Is a antivirus/spyware software running? Windows Defender will turn back on after a short while or reboot. Did you add client to exclusion list?

**Comment by MaxXor** [comment]
> I shutdown their computer through the shutdown option on Quasar, since i was too lazy to do it in real life. After that, it never connected since. (It connected only once and it was when I put the build file in the client pc)

When you shutdown the PC remotely it doesn't come online again until it's manually turned on again.
