### ISSUE TITLE
Device connected to my router and has no IP

### ISSUE THREAD

**Issue by Korto9** [quasar/Quasar#929]
Hi,

I have been struggling for the past 3 weeks with a device that is connected to my router and has no IP adress. I changed my router 3 times and this device still managed to connect to my router. I even rebooted my 2 pc. When I write the MAC adress of the device trojan/spyware and all kind of virus pop up. I think that the problem come from Quasar because it connected to my router just after I used Quasar. I think that Quasar is a malilcious program. What should I do I need help!!!

Thank you in advance

**Comment by BurntDog** [comment]
It's not Quasar not sure what your issue is. Cab you scan your router for backdoor? I have no issue myself.

**Comment by Korto9** [comment]
I just put the MAC adress and there is some weird site and I can see trojan in the text.

**Comment by Korto9** [comment]
I can't scan my router for backdoors.

**Comment by BurntDog** [comment]
Did you change your WIFI password? That suspicious device connected using WIFI I'm guessing.

**Comment by Korto9** [comment]
That's what I am telliing you I changed my router 3 times and changed de pasword mutiple times and it managed to connecte to my router.

**Comment by BurntDog** [comment]
I've been using this software for years and never had that happen and just check and no issues with unknown device connect to my router. Make sure your router's software is flashed with any latest updates/patches Quasar is not the issue.

**Comment by Korto9** [comment]
Alright thank you for your help.

**Comment by Korto9** [comment]
I have one last question. How I device with no local IP adress can connect to my router?

**Comment by MaxXor** [comment]
Use NAT/portforwarding in your router settings.
