### ISSUE TITLE
Port is Listening but no connections are popping up.

### ISSUE THREAD

**Issue by Kekwdrahul** [quasar/Quasar#930]
Quasar v1.3 works normally and pops up all clients, but quasar v1.4 is not, I'm using another port in quasar 1.4, everything is correct in the builder but it does not go up the victims.

I'm using IPV6 ip to open ports
Configs:
https://i.imgur.com/8r9D2Fi.png
https://i.imgur.com/XrfZqta.png
https://i.imgur.com/eUnwtCs.png

**Comment by Kekwdrahul** [comment]
I'm using IPV6 ip to open ports
Configs:
https://i.imgur.com/8r9D2Fi.png
https://i.imgur.com/XrfZqta.png
https://i.imgur.com/XrfZqta.png

**Comment by MaxXor** [comment]
You need to check "Enable IPv6 support" for IPv6 connections.

**Comment by Kekwdrahul** [comment]
In quasar v1.3 is not enabled and still works, I tested enable in 1.4 and remains without working

**Comment by MaxXor** [comment]
Do you want to allow connections from the internet? if you have a router you need to set up NAT/port forwarding. Check if the port is allowed in windows firewall too. Otherwise the router can't forward the connection to your PC:
