### ISSUE TITLE
it installed malware

### ISSUE THREAD

**Issue by dsfdsdwcdsfsdf** [quasar/Quasar#932]
it was fine until it started working, i forwarded the port, and i ran the build client and it worked, but few minutes after running the build client my pc started slowing down, i thought its no problem, but then my internet slowed, thought ok thats weird, but websites wouldnt load and it said i had no connection, so i ran malwarebytes and what the fuck do you know, there were 3 WORMS and get this shit, ANOTHER RAT it was njrat, i ran the scan after installing quasar and it didnt show that shit
im on windows 10 and had all the shit required for it

**Comment by MaxXor** [comment]
Only download Quasar from this place here: https://github.com/quasar/Quasar/releases/tag/v1.4.0 or build it from source by following this guide: https://github.com/quasar/Quasar#compiling

**Comment by dsfdsdwcdsfsdf** [comment]
i did i downloaded it from here, i ran the build and it gave me malware after forwarding the port

**Comment by BurntDog** [comment]
@dsfdsdwcdsfsdf You just make this account to troll repositories or are you that clueless? I think you should not use these types of tools. Quasar is 100% safe and has been around for years. Sounds like you opened a port that was previously compromised, Lol. You don't know what you're talking about. Please don't use these types of tools.

**Comment by dsfdsdwcdsfsdf** [comment]
no i made this account because i didn't have a fucking github account, and i forwarded the port that is the default port

**Comment by BurntDog** [comment]
Exactly, using default port noob 101 and that other rat just happened to be using it? You don't know enough to be using these apps and then you falsely accuse this tool when you infected yourself at a earlier point. Quasar has nothing to do with your problem. You don't even take the time to make a decent account username and you most likely run any software without caution. Quasar around and used for many years you, not so much.

**Comment by dsfdsdwcdsfsdf** [comment]
did you not read the fucking post, i scanned my pc before installing it and it was clean, i scanned after installing it it was clean except for the false positive, i forwarded the default port IN the fucking Port section of quasar not port 101 or some dumb shit, i used the recommended port, and you keep bringing up my name like it matters, i only made this account to get support on why i got a fucking rat after forwarding the RECOMMENDED port, and everytime i run something i do my research, i virustotal scan everything, i search around the web for hours if its not verified, i ask people who use it, and after i saw a fucking 500k youtuber using this on his main pc, i decided to give it a try,   i bet your one of those people who think that since youve been using it for a while that everyone who tries it should know how to do it all instantly of they are retards who dont deserve to use it

**Comment by BurntDog** [comment]
You come here accusing Quasar and you don't know what caused your issue not all new to Quasar or other apps make false claims. You don't even get the reference to noob 101, you think it's a port. You mostly tried some other app that infected you and just realized it. Blame yourself for using apps you know little about. Try using a sandbox/VM next time. Also please clean up your language it really shows your level of ignorance.

**Comment by dsfdsdwcdsfsdf** [comment]
1 why wouldn't i accuse a app that as soon as i used i had malware, i had run no other app, i scanned my pc before installing it and after installing it, everything was fine, as soon as i forwarded the recommended port i had malware,yes i know little about quasar, thats why i tried to be careful when using it, i followed all the steps correctly i used the correct port, and i got malware, and when i try to setup a vm it always blue screens as soon as i set it up, and the fact your using my language as an excuse for ignorance is kinda pathetic, not only does spelling have nothing to do with ignorance, it makes you look like you ran out of arguments, so your repeating the same thing you already said because you have nothing to go by anymore

**Comment by BurntDog** [comment]
How young are you? I am referring to you cursing like a child. And if you were getting bluescreens with setting up a VM that should tell you, you have other issues well before using Quasar I'm willing to bet. I am done with you, your like a child throwing a tantrum.
You got you answer now please stop trolling. Good bye..

**Comment by MaxXor** [comment]
@dsfdsdwcdsfsdf What file did you download? Please attach the zip file here in the comments.

@dsfdsdwcdsfsdf @BurntDog Please stay on topic. No childish fights.

**Comment by dsfdsdwcdsfsdf** [comment]
[Quasar.v1.4.0.zip](https://github.com/quasar/Quasar/files/6051917/Quasar.v1.4.0.zip)
this is the one i downloaded, it was fine, i was running the builds to test it it was working, once i finally got it working my pc started having problems, i know quasar itself is safe but i think it had something to do with the builds? or the port, but i used the recommended port so i dont know why i would have gotten the malware if it was something to do with the port

**Comment by MaxXor** [comment]
Maybe it's unrelated to Quasar. But please upload the zip file here, not just the link to the download.

**Comment by dsfdsdwcdsfsdf** [comment]
it wont let me upload the zip it says it cant process the file, but this is where i downloaded the file from, if needed i can upload the file to mediafire

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> Maybe it's unrelated to Quasar. But please upload the zip file here, not just the link to the download.

i think i got it working, im using it on a different machine for now, i dont understand building the clients, do i have to build just 1 to activate quasar or do i need to build all of them?

**Comment by BurntDog** [comment]
Open Quasar.sln with VS2019+ change from Debug to Release build. Then build the project. No need to build anything else in project(If by build you mean using VS2019). Then build/setup your client(s) using Server GUI

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> Open Quasar.sln with VS2019+ change from Debug to Release build. Then build the project. No need to build anything else in project(If by build you mean using VS2019). Then build/setup your client(s) using Server GUI

i mean by using the builder, i dont know if i have to build the basic client, or the surveillance client or the connection client, do i have to just build one for quasar to work if executed

**Comment by MaxXor** [comment]
There is only one client. It contains all the functionality needed. Please check out this guide: https://github.com/quasar/Quasar/wiki/Getting-Started

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> There is only one client. It contains all the functionality needed. Please check out this guide: https://github.com/quasar/Quasar/wiki/Getting-Started

i managed to get it semi working, i forwarded the port and everything, now when i try to listen, no connections are popping up, i just ran the build, i went to canyouseeme and it said the port wasnt working   is this temporary or do i have to use another port

**Comment by BurntDog** [comment]
If you forwarded the port it should show as open.

**Comment by dsfdsdwcdsfsdf** [comment]
i got it working, i had to add a new rule, now there are just no connections
