### ISSUE TITLE
Soundcapture

### ISSUE THREAD

**Issue by Ral721chanel** [quasar/Quasar#935]
Put a soundcapture to be able to listen the client

**Comment by BurntDog** [comment]
It was removed but, available in version 1.3, look through threads to find link.

**Comment by Ral721chanel** [comment]
An the remote chat?

**Comment by BurntDog** [comment]
Did you look at the roadmap to see if it is being looked at? Max may consider that.

**Comment by MaxXor** [comment]
Duplicate of https://github.com/quasar/Quasar/issues/135
