### ISSUE TITLE
no connection is popping up

### ISSUE THREAD

**Issue by dsfdsdwcdsfsdf** [quasar/Quasar#937]
i port forwarded, and set everything up, but when i run the build no connections show up, i use a no ip ddns.net hostname with the no ip dns updater canyouseeme   says the port is open, but sometimes when i run the build no connections pop up

**Comment by MaxXor** [comment]
Check that you've entered the correct hostname in the client builder.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> Check that you've entered the correct hostname in the client builder.
i copied the ddns.net hostname and put it in connections, and i put it in the no ip dns updater along with my user and password to no ip
