### ISSUE TITLE
ILRepack.targets(13,3): error : Failed to resolve assembly:

### ISSUE THREAD

**Issue by muhadese** [quasar/Quasar#938]
Hey
 
in Debugg Mod i dont get any issues but if i try  to compile in  release  i get this error 
Failed to resolve assembly: 'protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67'	

i updated the nuget packages 

i tried  it with installing protobuf-net.Core package too but same 
 
in Release I also dont  get client.bin 
AV MS Defender turn off  with exceptions etc

**Comment by BurntDog** [comment]
You're using VS 2019 yes?

**Comment by muhadese** [comment]
> You're using VS 2019 yes?

Yes VS 2019 Community Version

**Comment by MaxXor** [comment]
Don't update the Nuget packages, just download them.

**Comment by muhadese** [comment]
> Don't update the Nuget packages, just download them.

Ok thank u guys 
it worked

**Comment by MaxXor** [comment]
Glad it worked!
