### ISSUE TITLE
no connections popping up except host

### ISSUE THREAD

**Issue by dsfdsdwcdsfsdf** [quasar/Quasar#940]
when i try to run the build on my host pc i get a connection, but the ip of my machine says my local ip
when  i run the build on another pc i dont get a connection, i have the no ip dns updater on with my no ip user and pass along with ddns.net  in the host section   and my local ip and my no ip hostname in the connections settings, but my no ip hostname exposes my real ip when running

**Comment by MaxXor** [comment]
Check if you set up a firewall rule for the Quasar server: https://github.com/quasar/Quasar/wiki/Getting-Started#4-adding-a-firewall-rule

If you use a router, set up NAT/portforwarding.
