### ISSUE TITLE
Error in 1.4.0

### ISSUE THREAD

**Issue by Dazmed707** [quasar/Quasar#943]
1.-In file manager:
download option does not work

2.- Password Recovery does not work

3.- review and correct "run" option

using Quasar 1.4.0

**Comment by MaxXor** [comment]
1. It works, but here is a bug for files > 2 GB https://github.com/quasar/Quasar/commit/9520cd70ffff747e04ce34c606ebfca1043929c7

2. Chromium-based and Firefox browser recovery is fixed here https://github.com/quasar/Quasar/commit/a8213ae5cd04dae133cebc184c0bc79fa1b0551e

3. what?
