### ISSUE TITLE
Error 10013

### ISSUE THREAD

**Issue by lefty73** [quasar/Quasar#945]
I was using Quasar just fine until yesterday, when I updated my Windows 10 to the new 20H2 version (OS Build 19042.868).
Since then I keep getting the following error when opening the program - 

"An unexpected socket error occured: An attempt was made to access a socket in a way forbidden by its access permissions
Error Code: 10013"

I have tried looking to see if any other applications are using the same ports etc using netstat, but I can't see anything conflicting.

Any ideas what could be causing this?

![quasar error](https://user-images.githubusercontent.com/80961050/111779984-b490af00-88ae-11eb-80bb-b5d46ac71fc2.png)

Out of curiosity, I rolled back to a previous version of Windows 10 v1909 (OS Build 18363.1440) and Quasar once again worked fine, so the issue must lie somewhere within the update to the latest win10 release.

**Comment by BurntDog** [comment]
I have updated my Windows to the latest and Quasar works fine. Did you compile the whole project on the newly updated windows as I did?

**Comment by MaxXor** [comment]
It seems to be related to your antivirus blocking quasar from using that port. https://answers.microsoft.com/en-us/windows/forum/windows_7-networking/socket-10013-error-when-trying-to-connect-some/2cc71cb6-24b2-4b63-8f60-32bb444eb8fd

**Comment by MaxXor** [comment]
https://github.com/quasar/Quasar/issues/651
