### ISSUE TITLE
No connections appear, even when listening

### ISSUE THREAD

**Issue by UP929312** [quasar/Quasar#949]
**Describe the bug**
I am not able to connect or even "see" the device I have Quasar running on. Although it's partially possible that I have installed it incorrectly as I found the installation steps confusing. Would anyone be able to walk me though it just incase I have done what was said prior?

**System**
 - Server OS: Windows 10
 - Client OS: Windows 10
 - Server installed .NET Framework version: [e.g. v4.8]
 - Client installed .NET Framework version: [e.g. v4.8]
 - Quasar Version: Newest
 - Build configuration: Release

**Additional context**

**Comment by MaxXor** [comment]
Please read the [getting started page](https://github.com/quasar/Quasar/wiki/Getting-Started).
