### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by maxim207** [quasar/Quasar#952]
Hello is this safe to use bc my anti virus says its a virus but I need it to look up my child's safety on the internet

**Comment by BurntDog** [comment]
Yes, I have been using it for years. It is safe and I find it to be very secure. Yes, Anti Virus will detect a false positive as it does no harm to your PC but, has been misused in the past.

**Comment by sandord** [comment]
Edge and Chrome currently don't allow the download of the release .zip file so things have gotten a bit harsh for that matter. I guess I'll have to revert to using curl.

**Comment by BurntDog** [comment]
Why are you using either one of those browsers when there are better more secure and faster ones to use, like Brave or Palemoon. Remember to turn off Defender or other Antivirus.
