### ISSUE TITLE
Quasar on V-Windows Server Strato

### ISSUE THREAD

**Issue by Evolgate** [quasar/Quasar#953]
**Describe the bug**
I wanted to ask if someone could tell me how to control quasar connected clients if the quasar control center is run on a v-windows server (hosted on strato)

When I "infect" my V-Server with the .exe created by quasar on my v-server it is shown in the clients list. But it can't find clients I run on for example my laptops(to track them).  I have entered my v-servers domain/Ip but it won't work for clients not on the v-server. TLDR Locally it works but not over the internet. What am I doing wrong/what do I have to configure differently?

**Expected behavior**
On v-server: I hit build and send the exe to my laptop. Execute it there. And my Laptop appears on my v-server.

**System**
 - Server OS: [Windows Server 2019 Standard Edition 64bit]
 - Client OS: [Windows Server 2019 Standard Edition 64bit]
 - Quasar Version: [1.4.0]
 - Build configuration: [Release]

**Additional context**
I have the package Windows V25-49 (1.de)

**Comment by MaxXor** [comment]
You have to allow the port in your windows firewall. Please see here: https://github.com/quasar/Quasar/wiki/Getting-Started#4-adding-a-firewall-rule
