### ISSUE TITLE
I dont see on list

### ISSUE THREAD

**Issue by Syntetik008** [quasar/Quasar#954]
When I run the rat on my pc then I see my pc on the list but when my friend runs it then I don't see him on the list.

**Comment by AleGor1902** [comment]
open port, and set public ip in setting builder

**Comment by Syntetik008** [comment]
open ports in firewall?

**Comment by MaxXor** [comment]
You need to open the ports in your local PC firewall and router if you want to allow access from the internet, see here https://github.com/quasar/Quasar/wiki/Getting-Started
