### ISSUE TITLE
Cant get the nuget packages

### ISSUE THREAD

**Issue by Queirbeer** [quasar/Quasar#955]
When I download the files from github and then try to restore the nuget packages visual studio code says that there are no packages to be restored. Can anyone help me with this issue?

**Comment by BurntDog** [comment]
Did you try to compile the project, NuGet packages may already be up to date.

**Comment by MaxXor** [comment]
Please use Visual Studio 2019+.

**Comment by Queirbeer** [comment]
I am using Visual Studio 2019

**Comment by Queirbeer** [comment]
Why close the issue immediatelly after commenting lol

**Comment by MaxXor** [comment]
Cause there are numerous issues about this:
- https://github.com/quasar/Quasar/issues/938
- https://github.com/quasar/Quasar/issues/916

**Comment by Queirbeer** [comment]
Now the Visual code says that it cant load these files
![afbeelding](https://user-images.githubusercontent.com/74499233/114191607-e1cffa80-994c-11eb-8b2c-7e3c3953baa7.png)
![afbeelding](https://user-images.githubusercontent.com/74499233/114191646-ee545300-994c-11eb-9b6c-7e86f4633490.png)

**Comment by Queirbeer** [comment]
I have .NET 4.5.2 and 5.0.0 installed on my pc

**Comment by MaxXor** [comment]
> I have .NET 4.5.2 and 5.0.0 installed on my pc

Try modifying the Visual Studio installation and add the .NET desktop package.

**Comment by Queirbeer** [comment]
How would u suggest me doing that?

**Comment by MaxXor** [comment]
https://docs.microsoft.com/en-us/visualstudio/install/modify-visual-studio?view=vs-2019

**Comment by Queirbeer** [comment]
Thanks Ill try that and reply after trying

**Comment by Queirbeer** [comment]
I already have .NET desktop package installed
![afbeelding](https://user-images.githubusercontent.com/74499233/114194154-7dfb0100-994f-11eb-8c90-b671847b3ec9.png)

**Comment by MaxXor** [comment]
Select .net framework 4.5.2 sdk under individual components maybe?

**Comment by Queirbeer** [comment]
Let me try that

**Comment by Queirbeer** [comment]
The only thing I could do was remove it and that didnt work

**Comment by Queirbeer** [comment]
@MaxXor any further things I can do???
