### ISSUE TITLE
im not getting connections after doing everything right

### ISSUE THREAD

**Issue by dsfdsdwcdsfsdf** [quasar/Quasar#959]
ive tried for so long to get a connection, but i get nothing when running the build
https://ibb.co/zVd8yyg     --my settings
https://ibb.co/R3F552f   my connection settings

i followed the steps to set it up, i made a rule in windows defender, my no ip hostnames are updated,   and just to be sure are you supposed to put your no-ip email and password along with a random hostname in the no-ip dns updater section

**Comment by MaxXor** [comment]
What's missing is probably the forwarded port in your router. Please search for "<your-router-model> port forwarding" and add a port forwarding for TCP 4782 to your local PC.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> What's missing is probably the forwarded port in your router. Please search for " port forwarding" and add a port forwarding for TCP 4782 to your local PC.

i searched windows firewall on my pc and added a rule just to be sure and i still get no connections
i did all the steps

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> What's missing is probably the forwarded port in your router. Please search for " port forwarding" and add a port forwarding for TCP 4782 to your local PC.

am i supposed to do this logged into my router?  i already added a rule in windows firewall like in the tutorial on how to set it up

**Comment by MaxXor** [comment]
> > What's missing is probably the forwarded port in your router. Please search for " port forwarding" and add a port forwarding for TCP 4782 to your local PC.
> 
> am i supposed to do this logged into my router? i already added a rule in windows firewall like in the tutorial on how to set it up

Yes you need access to your router if you are behind NAT.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> > > What's missing is probably the forwarded port in your router. Please search for " port forwarding" and add a port forwarding for TCP 4782 to your local PC.
> > 
> > 
> > am i supposed to do this logged into my router? i already added a rule in windows firewall like in the tutorial on how to set it up
> 
> Yes you need access to your router if you are behind NAT.

i just did that, and still no connections, canyouseeme says the port is working
