### ISSUE TITLE
how do i hide my ip with noip

### ISSUE THREAD

**Issue by dsfdsdwcdsfsdf** [quasar/Quasar#960]
i put the hostname with my gateway ip, but its not working, i tried running the build, but i only get connections when i use my public ip, but i dont want anyone to get my ip

**Comment by MaxXor** [comment]
Look into VPNs.

**Comment by dsfdsdwcdsfsdf** [comment]
> 
> 
> Look into VPNs.

will i have to have the ip on all the time?

**Comment by MaxXor** [comment]
Only if you want to access the connected PCs. They will automatically reconnect once the VPN is running again. But you need to make sure you use the same IP again or use a dyn DNS provider.
