### ISSUE TITLE
Add an option to enable/disable notifications?

### ISSUE THREAD

**Issue by ratt0274** [quasar/Quasar#962]
I use quasar at my office workspace to make sure my team is on task and doing what is needed to be done.  I'd like there to be an option to enable/disable notifications when I start viewing their screen to see if they're staying on task.

**Comment by MaxXor** [comment]
It's already there, please check out the client deployment setting called "Unattended mode": https://github.com/quasar/Quasar/wiki/Client-deployment-settings#unattended-mode
