### ISSUE TITLE
paramètres de connexion

### ISSUE THREAD

**Issue by sapkiki** [quasar/Quasar#963]
Bonjour j'ai un petit problème j'ai essayer plusieurs ip et autre pour la configuration du fichier exe mais quand je le génére la n'est pas le probléme mais quand je lance le fichier rien ne s'affiche dans le tableau et je ne c'est pas comment m'y prendre pouvez vous m'aidez svp merci d'avance
![Sans titre](https://user-images.githubusercontent.com/82831277/115618155-945f7000-a2f2-11eb-8bde-a8c60040af80.png)

**Comment by sapkiki** [comment]
bien sur je sais qu'il faut que ca soit écrit listé sur le port .................... pour que ca marche je l'avais juste désactivez sans faire exprés

**Comment by MaxXor** [comment]
Please keep the discussion in English only.
