### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by sapkiki** [quasar/Quasar#964]
Hello I have a small problem I have tried several ip and other for the configuration of the exe file but when I generate it it is not the problem but when I run the file nothing is displayed in the table and I do not that's not how to go about it can you help me please thank you in advance
![Sans titre](https://user-images.githubusercontent.com/82831277/115735737-01bedf80-a38b-11eb-86cc-40aeade0de82.png)

**Comment by MaxXor** [comment]
Please use your WAN IP if you want to allow connections from the internet. Next open your port in your local windows firewall and then set up NAT/port forwarding in your router.

**Comment by sapkiki** [comment]
help me please

**Comment by BurntDog** [comment]
There are plenty of videos on YouTube that you will find helpful.
