### ISSUE TITLE
The ability to remove all traces of the RAT remotely

### ISSUE THREAD

**Issue by AwesomeAsh313** [quasar/Quasar#965]
**Is your feature request related to a problem? Please describe.**
Nope. Besides the fact that I infected myself with the rat on my own machine and want to remove it.

**Describe the solution you'd like**
The ability to right-click a machine and be able to uninstall it remotely. Removing all traces of the RAT.

**Additional context**
Nothing else. Just a request, but doesn't have to be done.

Edit: I'm wondering if this was already done. If it is, just close the issue. Sorry for wasting time.

**Comment by BurntDog** [comment]
It has a uninstall feature in menu.
