### ISSUE TITLE
0byte file download error

### ISSUE THREAD

**Issue by qwer0123456** [quasar/Quasar#966]
When downloading a file with a file size of 0, an error in the program

ex) null byte.txt file down crash Quasar

If the file contains even one byte, it is downloaded normally.

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Feature Suggestion

It would be nice if there was a function to select folder and download

I wish I had the ability to download the entire folder

**Comment by MaxXor** [comment]
Thanks for the bug report. Downloading all folders is tracked here: https://github.com/quasar/Quasar/issues/262
