### ISSUE TITLE
Large File Read Error When Transferring Remotely

### ISSUE THREAD

**Issue by Connor-Corp** [quasar/Quasar#968]
Target OS: Windows 10 Enterprise x64
Client OS: Windows 10 Enterprise x64

**To Reproduce**
1. Initiate a file download on client system with any file above 2.0GB in size
2. Wait for partial download, usually 1/5 of the way
3. Error triggers, redownload required. 

**Attempts to Resolve**
Reinstallation of .Net framework - No change
Usage of different client OS - No change
Recompilation of tool - No change
Attempt to use Internet Loopback via 127.0.0.1 - No change

**Notes**
Bug persists even after 1.4.0 update, quick glance at the code does not suggest anything obviously wrong.

**Comment by MaxXor** [comment]
It's fixed in this commit: https://github.com/quasar/Quasar/commit/9520cd70ffff747e04ce34c606ebfca1043929c7

Clone the latest master branch and compile in release mode. This way you have the fix included.

**Comment by Boos1688** [comment]
> It's fixed in this commit: [9520cd7](https://github.com/quasar/Quasar/commit/9520cd70ffff747e04ce34c606ebfca1043929c7)
> 
> Clone the latest master branch and compile in release mode. This way you have the fix included. No official updated release is out yet.

How to edit it, I don't understand it for newbies？

**Comment by ErickDaGamer** [comment]
> > It's fixed in this commit: [9520cd7](https://github.com/quasar/Quasar/commit/9520cd70ffff747e04ce34c606ebfca1043929c7)
> 
> > 
> 
> > Clone the latest master branch and compile in release mode. This way you have the fix included. No official updated release is out yet.
> 
> 
> 
> How to edit it, I don't understand it for newbies？

SEARCH FUNCTION. Look at #1044 for compilation instructions, as well as the README.MD file.
