### ISSUE TITLE
Antivirus detecting it as a Trojan

### ISSUE THREAD

**Issue by Bush8** [quasar/Quasar#970]
So I downloaded the zip file from releases and chrome showed a message saying it was dangerous, I allowed it anyway because I saw that other people had the same problem but after bypassing chrome's filter, windows security said it took action on the file due to being malicious and it classifies it as a Trojan. Is this normal? Should I just allow it anyway in the antivirus? Is it safe to use this program? Why would the antivirus remove it and why would chrome also say it's dangerous?

![image](https://user-images.githubusercontent.com/84467118/118852000-ba077700-b8a8-11eb-92c7-ec996dd3f808.png)
![image](https://user-images.githubusercontent.com/84467118/118852057-c8ee2980-b8a8-11eb-8041-37c15201012c.png)

**Comment by BurntDog** [comment]
As long as you download from here you're safe. Do a Search this topic has been answered several times.

**Comment by Bush8** [comment]
yeah I downloaded it from there but do you know why would it say it's a virus or something?

**Comment by BurntDog** [comment]
> yeah I downloaded it from there but do you know why would it say it's a virus or something?

Do a Search Here, this topic has been answered several times.

**Comment by BurntDog** [comment]
https://github.com/quasar/Quasar/issues/952

**Comment by Bush8** [comment]
Ok, so it's just a false reading due to the program having a lot of power basically, right?

**Comment by Bush8** [comment]
I keep allowing but eveytime I try to downoad it it finds a different type of malware so I keep allowing, downloading, allowing, downloading, etc.

**Comment by BurntDog** [comment]
You can turn off Windows Defender and after you add Quasar(folder you have it in) to your exclusion list within Defender turn it back on.

**Comment by MaxXor** [comment]
> Ok, so it's just a false reading due to the program having a lot of power basically, right?

Correct. It's a false positive.
