### ISSUE TITLE
Why other softwares of remote control aren't detected by antivirus like Quasar?

### ISSUE THREAD

**Issue by SuporteEQ** [quasar/Quasar#972]
Why Teamviewer, Anydesk, Google Remote Desktop aren't detected by antivirus like a vulnerability?

**Comment by BurntDog** [comment]
The short answer: They pay/register with Anti Virus companies and typically don't update their code a lot like smaller free projects like Quasar. And you have to pay this fee every time you change your code to avoid detection.

**Comment by gmiwoj** [comment]
because teamviewer is not specifically made to hide and run silently on someones computer, letting you connect any time and giving you full control while staying fairly undetectable.

or at least it's not that simple. believe me i tried.
