### ISSUE TITLE
[Question] How to add a new option in Profile Builder ?

### ISSUE THREAD

**Issue by mehroz1** [quasar/Quasar#973]
Sorry for opening an issue here but I am stuck on this problem for two days. I am trying add to new option to allow client to connect to a website. I have connected the client to website but the link of the website is hard coded in client at the moment. Now I want to add link of the website to profile builder so it can be changed when a new client is generated. The problem is I can't seem to figure out how Quasar\Server\Build\ClientBuilder.cs is injecting values Client.bin and how Quasar\Client\Config\Settings.cs is able to read them.

Here is my ClientBuilder.cs:

![Client-Builder](https://user-images.githubusercontent.com/9348863/120508138-e959d000-c3e0-11eb-80da-31bf2bc560d1.jpg)

Here is my Settings.cs:
![Settings](https://user-images.githubusercontent.com/9348863/120508149-eb239380-c3e0-11eb-8cea-27081e95e821.jpg)

Can anyone tell me what I am doing wrong here? I am trying to send unencrypted url link to Client.bin but when client is executed i receive an empty string. Any help would be much appreciated.

**Comment by MaxXor** [comment]
Looks correct. Check out this commit: https://github.com/quasar/Quasar/commit/053890b9338875d2f75c78c82659bef94b86ed00#diff-0de2da8eed089f3fd8923fb3446ef6caae89c4f02c1355b85490e0d7164ee3f2

In this commit a new option (boolean) was added, but string is almost the same.

**Comment by mehroz1** [comment]
Thank you

**Comment by mehroz1** [comment]
Here is an update
in Quasar\Client\Settings.cs I moved this line 
`public static string CONTROLDOMAIN = "";`
from line 73 to 70 and placed it above install path and log path it started working.

I don't understand how Quasar is mapping variables. I mean I can't see any pattern here. Is there any way I can know for sure that I am disturbing any other static member?

I thoroughly studied your commit and you were able to add UNATTENDEDMODE without any changes in line order.

**Comment by MaxXor** [comment]
Glad you got it working. The order of the properties in the `Settings.cs` file is important. As you can see in the `WriteSettings` method in your first screenshot it uses the order of the strings/bools/ints there too. You can check out the order by viewing the decompiled code in ilSpy/dnSpy. Not sure why you had to move `CONTROLDOMAIN` above `INSTALLPATH` as that mixes the settings of the last 3 strings. :thinking:

**Comment by mehroz1** [comment]
@MaxXor Yes it should mix up the string that was my initial preception but the output I was getting via Release & Debug showed that each variable was being assigned correct value unless the INSTALLPATH is malfunctioning. I will still inspect the project with ilSpy.
