### ISSUE TITLE
Is there a updated version of quasar or you stopped updating it on 2020 ?

### ISSUE THREAD

**Issue by AbdouDzGamer** [quasar/Quasar#974]
Is there a updated version of quasar or you stopped updating it on 2020 ?

**Comment by ErickDaGamer** [comment]
Pretty sure MaxXor is working on another update.

**Comment by AbdouDzGamer** [comment]
> Pretty sure MaxXor is working on another update.

So there is new another version after 1.4.0 ?

**Comment by BurntDog** [comment]
[Roadmap](https://github.com/quasar/Quasar/blob/master/ROADMAP.md) and the [associated discussion](https://github.com/quasar/Quasar/issues/674).

**Comment by ErickDaGamer** [comment]
> > Pretty sure MaxXor is working on another update.
> 
> So there is new another version after 1.4.0 ?

Yes. You can check other issues as evidence that MaxXor is working on 1.5. It's going to take a long time because they need to rework the entire GUI into something more modern.

**Comment by MaxXor** [comment]
It's progressing slowly, but not stopped. See also the roadmap linked by @BurntDog .
