### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by ruud05** [quasar/Quasar#975]
![image](https://user-images.githubusercontent.com/72221264/121425669-f5aad380-c972-11eb-84cf-102e1b3560ea.png)
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(3161,5): error MSB3821: Couldn't process file Forms\FrmVisitWebsite.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files.

**Comment by SteakySteaks** [comment]
brain issue

**Comment by Esquimen** [comment]
Hello i have this same problem, what is the solution for that ?

**Comment by MaxXor** [comment]
This error seems to occur when you download the Quasar repository as a ZIP file on Github. Please [see here](https://docs.microsoft.com/en-us/visualstudio/msbuild/errors/msb3821) and unblock the downloaded repository or clone the repository.

**Comment by Esquimen** [comment]
I cloned and it works now, nice work!
