### ISSUE TITLE
Add Pastebin support for the connection

### ISSUE THREAD

**Issue by Rafo124** [quasar/Quasar#976]
So that you can create a new Pastebin with a IP:port and then add the URL of that Pastebin in the client and have the client check that Pastebin URL for the IP:port it should connect to at launch

**Comment by persistence0x1** [comment]
I use a port-forwarded VPN to achieve a similar result. It allows me to setup a server anywhere from any supported device and still access my clients normally. You can look into different paid services or even setup your own port-forwarding VPN within a datacenter
