### ISSUE TITLE
Quasar rat is not working in client system 

### ISSUE THREAD

**Issue by Noone1614** [quasar/Quasar#977]
I was using version 1.4 nd i build client exe when i started it  in my own pc it connects but when i use it in client system over different network it was not sending any connection port is working correctly i checked using tcping firewall is disable on both client n host system everything as needed but dont know why is it happening, can anyone help me with it.

**Comment by BurntDog** [comment]
I use https://portmap.io/. This way I don't have to worry about port forwarding and can access my client from any WIFI hot spot.
Are you using no-ip? Try portmap.io. There are videos on YouTube to help you set it up.

**Comment by Noone1614** [comment]
But my port is already open i dont understand what this has to do with it.

**Comment by BurntDog** [comment]
Just a test. Process of elimination.

**Comment by Noone1614** [comment]
Can u suggest any specific video that will help.

**Comment by BurntDog** [comment]
Do Not use a temp email, they look for that and it can cause your account to be closed (use real email).
https://www.youtube.com/watch?v=AcbRpDX5NIo

https://openvpn.net/community-downloads/

**Comment by Noone1614** [comment]
bro i tried but it didn't worked, this time not even in my own pc maybe i did something wrong but not able to get that

**Comment by BurntDog** [comment]
It should work on your own pc and other. You have a other issue not sure what it can be.
Try cleaning your stacks
Reset Network TCP/IP stack
If your TCP/IP stack is corrupted it can be reseted with the following commands.

Windows XP:
1. Search for Command Prompt > Run As Administrator
2. netsh winsock reset
3. netsh int ip reset
4. ipconfig /flushdns
5. Restart computer

Windows Vista, 7, 8, 10:
1. Search for Command Prompt > Run As Administrator
2. netsh winsock reset catalog
3. netsh int ipv4 reset reset.log
4. netsh int ipv6 reset reset.log
5. Restart computer

**Comment by Noone1614** [comment]
But it was working fine on my pc before, when i build by opening port in firewall
and also "tcp://Noone1416-58487.portmap.host:58487 => 4782" this is d rule that i created in portmap.io can u please confirm what will be  hostname, port and listening port.

**Comment by BurntDog** [comment]
Noone1416-58487.portmap.host
port 4782

**Comment by BurntDog** [comment]
I made a mistake should be:
build client:
Noone1416-58487.portmap.host
port= 58487
Server listen port:
Make sure "server is listening for port 4782" the one you configured on portmap site

**Comment by BurntDog** [comment]
If still no connect do this:
Windows Vista, 7, 8, 10:

Search for Command Prompt > Run As Administrator
netsh winsock reset catalog
netsh int ipv4 reset reset.log
netsh int ipv6 reset reset.log
Restart computer

And of course make sure OpenVPN is running and connected

**Comment by BurntDog** [comment]
I have to do the same (clean my stacks)I'm not connecting myself.
I can't reboot at this time in the middle of something.

**Comment by Noone1614** [comment]
> I made a mistake should be:
> build client:
> Noone1416-58487.portmap.host
> port= 58487
> Server listen port:
> Make sure "server is listening for port 4782" the one you configured on portmap site

bro i did this first time 
still not working i did reset all
again not working not even in my pc

**Comment by BurntDog** [comment]
Ok, so you reset all stacks and Rebooted computer and OpenVPN's tray icon is green  meaning it's connected to portmap.io

**Comment by BurntDog** [comment]
I'm having the same issue now as well. Not sure why but, now I got to figure this out later.

**Comment by BurntDog** [comment]
I can loop back but, still same issue as you. Well figure this out, it's got to be something simple, makes no sense.

**Comment by Noone1614** [comment]
yeah bro, please let me know if u find something i dont wanna give this up like that

**Comment by BurntDog** [comment]
It was a site issue, it's working now

**Comment by BurntDog** [comment]
When you go to your mappings rules page https://portmap.io/mappings you should see a check mark by your mappings rule. That confirms that OpenVPN is correctly connected. It wasn't connecting before but it is now. I also reset my stacks like three times but more then likely all issues was site related. I'm guessing you tried no-ip and did that work for you?

**Comment by Noone1614** [comment]
On portmap.io check box is showing "Not Active. Restart Vpn Session" i already did but still same .

**Comment by Noone1614** [comment]
hey bro, thanks a lot for helping now its working good i tested on different pc also. you were right i think it was some issue wth portmap.io i didn't change anything just build another exe and that worked but what if it will happen again is there is any other alternative and also when i was testing in client pc, there was a notification saying that quasar client is connected for remote access something like that. will it come everytime on startup or can if u know a way to make it stop.

**Comment by Noone1614** [comment]
And bro is there any same kind of RAT for android also if u know any pls let me know that will give remote access or screen sharing.

**Comment by BurntDog** [comment]
Other then using No-ip or portmap.io are the only two I've used. And that message you get "connected for remote access" sounds like the option for try icon is on when building Quasar client, just unselect it. 

The only free Android Remote Admin tool I had any luck with is "Spy MAX v2.0"

**Comment by Noone1614** [comment]
Yeah but spy max is not compatible with android 10 or higher maybe in future.
Any keylogger that will work on android 10 or 11 if you know?

**Comment by BurntDog** [comment]
Nothing, I don't really use android tools other then controlling my one old phone.

**Comment by MaxXor** [comment]
Thanks for the help @BurntDog :+1:

**Comment by BurntDog** [comment]
> Thanks for the help @BurntDog 👍

You're welcome.

**Comment by AwesomeShellyYt** [comment]
hi I'm trying to do this too its not quite working for me either

**Comment by Noone1614** [comment]
What problem u r facing?

**Comment by AwesomeShellyYt** [comment]
when i got my target to open the file i didnt see him on the list

**Comment by Noone1614** [comment]
I was facing same issue, something was wrong with port forwarding how did u enable it.?

**Comment by AwesomeShellyYt** [comment]
i use portmap.io 
could you make a video about how to do it?

**Comment by Noone1614** [comment]
Yeah thats same thing bro u can use portmp.io, did you put hostname and ip correctly why building exe

**Comment by AwesomeShellyYt** [comment]
i dont know if i did it correct can make a video on it?

**Comment by BurntDog** [comment]
YouTube has a few already.

**Comment by AwesomeShellyYt** [comment]
I cant find any 
could one of u make it for me

**Comment by Noone1614** [comment]
https://m.youtube.com/watch?v=AcbRpDX5NIo

Watch this video this will help u understand then 
Bro just send your two screenshots first your portmap page where u have created mapping rule and second when you build exe hostname and ip page.

**Comment by AwesomeShellyYt** [comment]
it kinda works it will show up if i run it but if someone else runs then it wont work

**Comment by Noone1614** [comment]
How is that different anyone just has to click on it.

**Comment by AwesomeShellyYt** [comment]
if i run it my pc shows up in it but if someone else runs it then nothing pops up 
can you help me?

**Comment by Noone1614** [comment]
Bro i have given d link watch that video, and when u build exe just be sure to put hostname and ip correctly also send screenshots of mapping rule and of builder then i'll try to help properly because i was facing d same issue.

**Comment by AwesomeShellyYt** [comment]
i watched the video about 3 - 4 times and i cant understand

**Comment by Noone1614** [comment]
Then how will u able to do, its one of d simplest video i found on youtube.
Have you created account on portmap.io ? 
What did you not understand? 
Any other way, we can chat telegram or something?

**Comment by AwesomeShellyYt** [comment]
i can chat on discord
