### ISSUE TITLE
Connectio nnot showing up

### ISSUE THREAD

**Issue by XxFadedKnight** [quasar/Quasar#978]
**Describe the bug**
I infected my computer with the rat and i port forwarded on windows defender and my router and the connection is not showing up. I pinged my port and it says the port is working but the connection is not

**Comment by BurntDog** [comment]
Do a search we have several answers to this question.

**Comment by XxFadedKnight** [comment]
I have done a search but i couldnt find anything that had usefull information for me in it, i use my home ip because i am using this for different purposes, i am not worried about getting reverse engineered

> Do a search we have several answers to this question.

**Comment by BurntDog** [comment]
Explain what you've done how is computer and client set up? ports forwarded and such?

**Comment by XxFadedKnight** [comment]
i port forwarded it on my router and the firewall, i dont know what you mean by how is it set up

**Comment by XxFadedKnight** [comment]
anyone?

**Comment by BurntDog** [comment]
Does loopback work?

**Comment by XxFadedKnight** [comment]
What's loopback?

**Comment by BurntDog** [comment]
build client using:
ip= 127.0.0.1
port= whatever you use
You can not run client and server on some ip/machine using your public ip unless you use no-ip or portmap.io
other then using (on same computer) loopback "127.0.0.1"

**Comment by BurntDog** [comment]
https://github.com/quasar/Quasar/issues/862

**Comment by XxFadedKnight** [comment]
ill right ill try it now.

**Comment by XxFadedKnight** [comment]
do i listen for the ip using 127.0.0.1?

**Comment by XxFadedKnight** [comment]
It isnt working, should i just use no-ip?

**Comment by BurntDog** [comment]
If loopback doesn't work you have other issues but you can try no-ip maybe your client just isn't configured correctly. You need to give some non-private details of how you're setting things up.
However I'm sure the answer to your problem has already been answered you need to take the time to look thru our data base of issues resolved. The best way to learn is hands on trial and error, you learn very little if you just receive answers and still have little to no understanding how things work.

**Comment by ld199611** [comment]
Why can I only connect on the local network, please tell me

**Comment by ld199611** [comment]
> 如果环回不起作用，您还有其他问题，但您可以尝试 no-ip，也许您的客户端配置不正确。你需要提供一些关于你如何设置的非私人细节。 但是，我确信您的问题的答案已经得到解答，您需要花时间查看我们已解决问题的数据库。最好的学习方法是动手试错，如果你只是得到答案，但仍然很少或根本不了解事情是如何运作的，那么你学到的东西很少。

**Comment by ErickDaCoder** [comment]
> Why can I only connect on the local network, please tell me
> 
> 
> 
>  

you didn't port forward. port forwarding is required to connect to devices outside of your network.

**Comment by ld199611** [comment]
> 如果您需要设置，但您需要提供一些其他问题，但您可以尝试不， 我的客户端配置可能不正确。答案已经得到答案，需要花时间查看问题的数据库。最好的解决方法是你动手试错，如果你的答案是错误的，但仍然很少或根本不知道我们如何处理这样的事情，你学到的东西很少。

Poseidon#9777 Add my Discord:

**Comment by Sindoes** [comment]
> you didn't port forward. port forwarding is required to connect to devices outside of your network.

Yo whats your discord welp me
