### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by Smurfboi007** [quasar/Quasar#980]
So I got a Windows 10 Pro VM, and after I Uninstallaled the client in Quasar, I can't reconnect it. I've tried using the same build that did work and a couple of new ones, but none of them is working... I am listening on the same port as the client and the connection tap is correct.

 - Server OS: Windows 10 pro
 - Client OS: Windows 10 pro
 - Quasar Version: 1.4.0
 - Build configuration: Release

**Comment by ErickDaGamer** [comment]
So you uninstalled a client from Quasar and you tried reinstalling it, and after you've reinstalled it, it doesn't give you a connection?

**Comment by BurntDog** [comment]
For anyone New to Quasar having connection issues after confirming Client and Server is set up correctly. Always check your firewall settings to confirm "Quasar Server" isn't being blocked.
Go from this:
![Screenshot_5](https://user-images.githubusercontent.com/62985894/225436078-783389b9-bd47-40ba-bb64-63165ff0c5ed.png)
To This:
![Screenshot_4](https://user-images.githubusercontent.com/62985894/225436114-48a7f477-5d2f-42d6-b2e9-7b97d85bcd72.png)
By checking these Firewall settings (Clicking Allow on first run of "Quasar Server" doesn't always work correctly for some reason):
![Screenshot_1](https://user-images.githubusercontent.com/62985894/225436895-655196b5-26f0-40eb-9d6c-cd22a8ea7941.png)
To Fix Click on properties of offending rule(s) and Allow if Blocked:
![Screenshot_2](https://user-images.githubusercontent.com/62985894/225436950-887fadad-5788-4f3a-98b1-b3e67f987081.png)
Change to this (Allow and click apply)
![Screenshot_3](https://user-images.githubusercontent.com/62985894/225437057-cdd6db76-b44f-4885-82b4-9949ebc40cae.png)

I hope this was helpful.

**Comment by MaxXor** [comment]
@BurntDog Thanks!
