### ISSUE TITLE
Disable Windows Defender

### ISSUE THREAD

**Issue by DexterityLmao** [quasar/Quasar#983]
**Is your feature request related to a problem? Please describe.**
No. 

**Describe the solution you'd like**
I would like a feature that makes it so when you are in a clients pc you can disable their windows antivirus forever.

**Comment by ErickDaGamer** [comment]
As far as I know, this is completely impossible. You can't even write a value into Window Defender's exceptions key.

**Comment by DexterityLmao** [comment]
> As far as I know, this is completely impossible. You can't even write a value into Window Defender's exceptions key.

What about Regediting? It’s hella annoying to have to turn off windows defender every time I restart my pc to connect the rat.

**Comment by ErickDaGamer** [comment]
> > As far as I know, this is completely impossible. You can't even write a value into Window Defender's exceptions key.
> 
> 
> 
> What about Regediting? It’s hella annoying to have to turn off windows defender every time I restart my pc to connect the rat.

If you want to disable Windows Defender detecting the client you need to open Windows Security and go to Virus & threat protection >> Manage settings (below virus and threat protection settings) >> Add or remove exclusions (at the bottom) and press "Add an exclusion". Then, find the Quasar client path and add it. Now the client won't get detected by Windows Defender.

Same thing with the server except you select Quasar's folder, not just Quasar.exe.
