### ISSUE TITLE
Decrypt Logs

### ISSUE THREAD

**Issue by KcioX** [quasar/Quasar#984]
**Describe the bug**
When I try to recover key logs from a users computer (i even tried my own) I get the error Failed to decrypt and write logs. It looks Like this ò}¿•4s$Ãù¾)!P|k³–Ž in the logs.

**Screenshots**
https://gyazo.com/ee49a715aea891cd2ad5577d2379ec4d

Please help. Thank you

**Comment by KcioX** [comment]
Fixed! All i had to do was goto the folder - clients - and deleted all .html files before that!

**Comment by BurntDog** [comment]
Ok, just tested and it's working fine for me. Glad you figured it out.
