### ISSUE TITLE
where do I see hidden websites

### ISSUE THREAD

**Issue by rotary6666** [quasar/Quasar#987]
where do I see hidden websites?

**Comment by BurntDog** [comment]
You don't their Hidden.... If you want to test just go to a web address/server that auto plays a audio file when visited.

**Comment by rotary6666** [comment]
What’s the point of hidden websites then 

Sent from Windows 3

**Comment by BurntDog** [comment]
Think about it.. If you don't know then it's just an option you don't need at this time but may in the future.

**Comment by MaxXor** [comment]
When the client visits a website visibly it'll open up in their browser. If you just want some URL to be accessed by the quasar client without any visibility to the user, you should use the hidden website option.

**Comment by rotary6666** [comment]
how do i access the hidden link in the client
