### ISSUE TITLE
Quasar Not working on other computers not connceted to my network

### ISSUE THREAD

**Issue by KcioX** [quasar/Quasar#988]
Hello, I have tested the RAT on my own computer and my other computer on my network and are both successful. Yet when I have someone who is not on my network download it it does not work. He was showing his screen the entire time, had all Anti-virus's deactivated and run the program and nothing shows up on my end. Had him run as admin and still nothing. Any idea why?

**Comment by BurntDog** [comment]
Please use our search option under Issues as this topic has been discussed several times with solutions. 

Thank
