### ISSUE TITLE
The operation has timed out

### ISSUE THREAD

**Issue by UnknownUser1789** [quasar/Quasar#992]
![image](https://user-images.githubusercontent.com/81835566/123992622-030f1880-d989-11eb-9b28-de8fdc8f3a18.png)

Displays this error when I run quasar. I have a windows 10 operating system, 64 bit. Here's how to recreate the error:

I used the default port (4782), then i built a client that with both my private and public ip as the hostname, see below image. Then I manually port forwarded 4782 to be safe, and i started listening on quasar. Then I ran the client I built, and killed quasar server with process hacker. Then i ran it again, and then the error happened

![image](https://user-images.githubusercontent.com/81835566/123993473-afe99580-d989-11eb-8841-c4295d027e52.png)

**Comment by BurntDog** [comment]
Well don't do that, lol just kidding. I'll let MaxXor handle this one. I have nothing off the top of my head on this one. I will see If I can reproduce this error as well and comment back.

**Comment by MaxXor** [comment]
Does Quasar.exe throw this exception or the client?

**Comment by BurntDog** [comment]
I could not recreate the error, client and server works as it should.
