### ISSUE TITLE
Does not know how to use (im new 2 github)+cant find quasar exe

### ISSUE THREAD

**Issue by p0shopig** [quasar/Quasar#993]

**Comment by BurntDog** [comment]
There are two different projects which Quasar are you looking? This project is a Remote Administrator Tool allowing one to control a computer over Lan or internet.

If this is the project you're interested in you need to have Visual Studio 2019+ and will need to compile it.

**Comment by p0shopig** [comment]
the latest one and i already have studio

**Comment by p0shopig** [comment]
wait cased closed i accedentally data shred it amd i found its broken shortcut
