### ISSUE TITLE
client not responding to Quarserrat

### ISSUE THREAD

**Issue by Abhay-2412** [quasar/Quasar#998]
i installed client in other laptop which has windows 10 it responded intially but i donno why after some time i tried again and its not responding i reinstalled the client and again its working can any one suggest where did i went wrong
lemme know if u need aditional proofs

**Comment by BurntDog** [comment]
Did you add it to your Anti-Virus exclusion list?

**Comment by Abhay-2412** [comment]
yes i have and iam a newbie to all this stuff do we need to run the client in my PC as well?

**Comment by BurntDog** [comment]
The "Client" would run on the machine being controlled/monitored and the "Server" would run on the system administrator's pc so, no you don't run the client on your end.

**Comment by Abhay-2412** [comment]
hey it worked this morning but when i tried now it again not connecting should i disable my anti virus

**Comment by BurntDog** [comment]
As long as you have the client exe file listed correctly within your Anti-Virus exclusion list, you can and should keep Anti-Virus running and is recommended to help keep you clear of other unrelated issues.

**Comment by Abhay-2412** [comment]
![image](https://user-images.githubusercontent.com/86143871/127537983-224397fe-10c6-4961-8b7d-8e68c4872b91.png)
it is in exceptionlist

**Comment by Abhay-2412** [comment]
still i cant connect to the client any suggestion!!!

**Comment by BurntDog** [comment]
The "client" "exe" also needs to be in the list on the machine it is running on. Quasar.exe "Server" is what you use to control client pc.

**Comment by Abhay-2412** [comment]
client.exe is not on my laptop it is installed in other computer
