### ISSUE TITLE
not sending the message thing

### ISSUE THREAD

**Issue by heyehyey** [quasar/Quasar#999]
when they open  nothing happens and i dont get a message

**Comment by BurntDog** [comment]
Have you tried anything on your end to find the issue? It works fine on my two year old system running the latest Windows 10.
You need to include more details on your issue ie. Windows version, Quasar version are you running anti bloatware that may have altered certain system settings ect. ?

**Comment by heyehyey** [comment]
latest version 
windows 10 pro

**Comment by BurntDog** [comment]
Do you get any error message? If so a screenshot would be helpful. Did you try it on another machine or virtual box? You're not giving very much information, I have no ideal why it doesn't work for you. Did you do a search in our issues section? There may be something helpful there.

**Comment by heyehyey** [comment]
so im using virtuial box to create it and when i open the file it works for me but when other people open the file and im listening it doesnt send the log

**Comment by BurntDog** [comment]
When you say you're using virtual box to create it meaning build it using the server it works for you but not others did you try building in on your normal system (it's safe to do)? Also, I'm sure your compiling from code within the normal OSW and not on a VM.

**Comment by heyehyey** [comment]
could we call on discord and show u?

**Comment by BurntDog** [comment]
I don't really do Discord or any messaging type stuff.

MaXxor should be in this thread soon, he has a lot to do so be patient he'll be quicker in helping you figure this out.

**Comment by MaxXor** [comment]
Sounds like a firewall problem to me. Make sure all ports are correctly opened and if you use Quasar over the internet check the NAT settings on your router.
